import * as path from "node:path";
import { readFile as fsReadFile } from "node:fs/promises";
import * as t from "@babel/types";
import { normalize } from "./babel/transform.ts";
import { emitComponentType } from "./emit/component.ts";
import { analyzeContexts, analyzeProvider, analyzeSignals, analyzeUseContext } from "./model/symbols.ts";
import { hParts, isComponentIdentifier, isHCall } from "./ast/h.ts";
import { isBareSpecifier, isRuntimeOnlyImport, mirrorNodeImports, resolveNodeImport } from "./resolve/node.ts";
import { emitStmt } from "./emit/stmt.ts";

export interface GeneratedApp {
  /** The entry (app-root) component's QML type. */
  entry: string;
  /** Other referenced component types, QML-type-name → QML source. Includes verbatim-copied
   *  custom `.qml` files imported from TSX (`import Fancy from "./Fancy.qml"`) — they are written
   *  as `<name>.qml` next to the generated output and instantiated by type name like any component. */
  components: Record<string, string>;
  /** Concatenated CSS from every `import "./x.css"` side-effect import across the module graph (in
   *  discovery order, deduped). The dev loop / vite plugin loads this as the app's base layer. */
  css: string;
  /** Mirrored npm/Node ESM modules, path relative to the QML output directory → source. */
  modules: Record<string, string>;
}

export interface GenerateOptions {
  /** Read a module's source by absolute path. Defaults to fs. Override in tests. */
  readFile?: (absPath: string) => Promise<string>;
}

const HEADER = [
  "// Generated by the transpiler. Do not edit by hand.",
  "import QtQuick",
  "import qmlcss 1.0 as Css", // C++ types registered by the loader (no qrc QML anymore)
];

interface CompInfo { fn: t.Function; render: t.CallExpression; exported: boolean; }
interface ImportInfo { spec: string; imported: string; } // imported === "default" for default imports
interface Mod {
  comps: Map<string, CompInfo>;
  imports: Map<string, ImportInfo>;
  dir: string;
  contexts: Set<string>;
  /** The normalized module AST — needed to collect a resource fetcher's module-level decls (inlined). */
  file: t.File;
  /** local binding name → QML expression for a mirrored JS import (`Js0.default`, `Js1.name`, …). */
  jsImports: Record<string, string>;
  /** mirror path → QML import alias, for this source module's mirrored dependencies. */
  qmlImports: Map<string, string>;
  /** Module-level runtime-config statements (e.g. `tabstop.enabled = false`), already emitted as
   *  QML statements. Import-time semantics: they run once at app boot, hoisted into the entry
   *  component's Component.onCompleted. */
  moduleInit: string[];
}

/** Every component function (returns an h() call) declared at module top level. */
function findComponents(ast: t.File): Map<string, CompInfo> {
  const out = new Map<string, CompInfo>();
  const consider = (fn: t.Function | null | undefined, name: string | null, exported: boolean) => {
    if (!fn || !name || !t.isBlockStatement(fn.body)) return;
    for (const s of fn.body.body) {
      if (t.isReturnStatement(s) && isHCall(s.argument)) {
        out.set(name, { fn, render: s.argument, exported });
        return;
      }
    }
  };
  for (const node of ast.program.body) {
    if (t.isFunctionDeclaration(node) && node.id) consider(node, node.id.name, false);
    if (t.isExportNamedDeclaration(node) && node.declaration && t.isFunctionDeclaration(node.declaration) && node.declaration.id)
      consider(node.declaration, node.declaration.id.name, true);
    if (t.isExportDefaultDeclaration(node) && t.isFunctionDeclaration(node.declaration) && node.declaration.id)
      consider(node.declaration, node.declaration.id.name, true);
  }
  return out;
}

/** local binding name → import origin, for named + default imports. */
function collectImports(ast: t.File): Map<string, ImportInfo> {
  const out = new Map<string, ImportInfo>();
  for (const node of ast.program.body) {
    if (!t.isImportDeclaration(node)) continue;
    const spec = node.source.value;
    for (const s of node.specifiers) {
      if (t.isImportSpecifier(s)) out.set(s.local.name, { spec, imported: t.isIdentifier(s.imported) ? s.imported.name : s.imported.value });
      else if (t.isImportDefaultSpecifier(s)) out.set(s.local.name, { spec, imported: "default" });
      else if (t.isImportNamespaceSpecifier(s)) out.set(s.local.name, { spec, imported: "*" });
    }
  }
  return out;
}

/** Component tags (Identifiers in `known`) used in a render tree. */
function usedComponentTags(render: t.CallExpression, known: Set<string>): string[] {
  const tags = new Set<string>();
  // Full recursive descent over every child node, so component tags are discovered even inside
  // <For>/<Index> delegate arrow bodies (`{(item) => <TodoRow .../>}`), conditionals, etc.
  const walk = (n: t.Node): void => {
    if (isHCall(n)) {
      const { tag } = hParts(n);
      // `Window` is a built-in primitive (emitQml emits a real QML Window), not a followed component —
      // don't mirror the runtime's web-only Window component for it.
      if (isComponentIdentifier(tag, known)) tags.add(tag.name);
    }
    for (const key of Object.keys(n)) {
      const v = (n as Record<string, unknown>)[key];
      if (Array.isArray(v)) { for (const c of v) if (c && typeof (c as t.Node).type === "string") walk(c as t.Node); }
      else if (v && typeof (v as t.Node).type === "string") walk(v as t.Node);
    }
  };
  walk(render);
  return [...tags];
}

/** Resolve a relative specifier to an on-disk module; null for npm/unresolved specifiers. */
async function resolveModule(dir: string, spec: string, readFile: NonNullable<GenerateOptions["readFile"]>): Promise<{ path: string; source: string } | null> {
  if (!spec.startsWith(".")) return null; // npm — a later plan, not an author component
  const base = path.resolve(dir, spec);
  for (const cand of [`${base}.tsx`, `${base}.ts`, path.join(base, "index.tsx"), path.join(base, "index.ts")]) {
    try { return { path: cand, source: await readFile(cand) }; } catch { /* next */ }
  }
  return null;
}

/** The default-exported component's declared name (for `import X from "./x"`). */
function defaultComponentName(mod: Mod): string | null {
  for (const [name, c] of mod.comps) if (c.exported) return name;
  return [...mod.comps.keys()][0] ?? null;
}

/** A short, stable, identifier-safe segment from a module path, to disambiguate name collisions. */
function pathPrefix(absPath: string): string {
  const seg = path.basename(path.dirname(absPath)) || "root";
  return seg.replace(/[^A-Za-z0-9]/g, "_").replace(/^(\d)/, "_$1");
}

/** Transpile a module + every component it (transitively) instantiates, following relative imports. */
export async function generate(source: string, filename: string, opts: GenerateOptions = {}): Promise<GeneratedApp> {
  const readFile = opts.readFile ?? ((p) => fsReadFile(p, "utf8"));
  const modules = new Map<string, Mod>();
  const cssFiles: string[] = []; // resolved abs paths of imported .css, in load order, deduped
  const seenCss = new Set<string>();
  const mirroredModules = new Map<string, string>();

  const load = async (absPath: string, src: string): Promise<Mod> => {
    const hit = modules.get(absPath);
    if (hit) return hit;
    const { ast } = await normalize(src, absPath);
    const file = ast as t.File;
    // Side-effect `import "./x.css"` (no specifiers) → collect for the CSS sidecar, in discovery order.
    for (const node of file.program.body) {
      if (t.isImportDeclaration(node) && node.specifiers.length === 0 && node.source.value.endsWith(".css")) {
        const abs = path.resolve(path.dirname(absPath), node.source.value);
        if (!seenCss.has(abs)) { seenCss.add(abs); cssFiles.push(abs); }
      }
    }
    const imports = collectImports(file);
    const jsImports: Record<string, string> = {};
    const qmlImports = new Map<string, string>();
    // `tabstop` from "qml-solid" (or the runtime module) is the loader's solidTabstop context
    // property — the identifier rewrites in place, the import compiles away.
    for (const [local, imp] of imports) {
      if (isRuntimeOnlyImport(imp.spec) && imp.imported === "tabstop") jsImports[local] = "solidTabstop";
    }
    const bareImports = [...imports.values()].filter((imp) => isBareSpecifier(imp.spec) && !isRuntimeOnlyImport(imp.spec));
    if (bareImports.length > 0) {
      const mirrored = await mirrorNodeImports(bareImports, path.dirname(absPath), readFile);
      for (const [outPath, mirroredSource] of mirrored.modules) mirroredModules.set(outPath, mirroredSource);
      let importIndex = 0;
      for (const [local, imp] of imports) {
        if (!isBareSpecifier(imp.spec) || isRuntimeOnlyImport(imp.spec)) continue;
        const resolved = await resolveNodeImport(path.dirname(absPath), imp.spec, readFile);
        const outPath = mirrored.byAbsPath.get(resolved);
        if (!outPath) throw new Error(`internal error: mirrored import not found for ${imp.spec}`);
        let alias = qmlImports.get(outPath);
        if (!alias) {
          alias = `Js${importIndex++}`;
          qmlImports.set(outPath, alias);
        }
        jsImports[local] = imp.imported === "*"
          ? alias
          : imp.imported === "default"
            ? `${alias}.Default`
            : `${alias}.${imp.imported}`;
      }
    }
    // Module-level writes to a runtime-config import (`tabstop.enabled = false` at top level):
    // emitted here, with THIS module's import scope, and hoisted to the entry's onCompleted.
    const moduleInit: string[] = [];
    for (const node of file.program.body) {
      if (!t.isExpressionStatement(node) || !t.isAssignmentExpression(node.expression)) continue;
      const lhs = node.expression.left;
      if (t.isMemberExpression(lhs) && t.isIdentifier(lhs.object) && lhs.object.name in jsImports
        && imports.get(lhs.object.name) && isRuntimeOnlyImport(imports.get(lhs.object.name)!.spec)) {
        moduleInit.push(emitStmt(node, { table: new Map(), mode: "handler", jsImports }));
      }
    }
    const mod: Mod = { comps: findComponents(file), imports, dir: path.dirname(absPath), contexts: analyzeContexts(file), file, jsImports, qmlImports, moduleInit };
    modules.set(absPath, mod);
    return mod;
  };

  const entryPath = path.resolve(filename);
  const entryMod = await load(entryPath, source);
  if (entryMod.comps.size === 0) throw new Error(`No component found in ${filename}`);
  const entryName = [...entryMod.comps].findLast(([, c]) => c.exported)?.[0] ?? [...entryMod.comps.keys()].at(-1)!;

  // Phase 1 — discover: DFS the component graph, deduped by `${absPath}#${declName}`.
  interface Node { absPath: string; declName: string; mod: Mod; edges: Map<string, string>; } // useName → target key
  const nodes = new Map<string, Node>();
  const keyOf = (absPath: string, name: string) => `${absPath}#${name}`;
  // Custom `.qml` imports (the native escape hatch): copied VERBATIM to the output and
  // instantiated by type name. Keyed `qml:<abs>` in the edge graph; never transpiled.
  const qmlForeign = new Map<string, { typeName: string; source: string }>();

  const visit = async (absPath: string, mod: Mod, declName: string): Promise<void> => {
    const key = keyOf(absPath, declName);
    if (nodes.has(key)) return;
    if (!mod.comps.has(declName)) throw new Error(`component ${declName} not found in ${absPath}`);
    const edges = new Map<string, string>();
    nodes.set(key, { absPath, declName, mod, edges });
    const known = new Set<string>([...mod.comps.keys(), ...mod.imports.keys()]);
    for (const tag of usedComponentTags(mod.comps.get(declName)!.render, known)) {
      if (mod.comps.has(tag)) { edges.set(tag, keyOf(absPath, tag)); await visit(absPath, mod, tag); continue; }
      const imp = mod.imports.get(tag)!;
      // A `.qml` specifier is a hand-written QML component — copy it verbatim, instantiate by
      // type name (QML resolves a sibling `<Base>.qml` file automatically, like our own emitted
      // components). NOT transpiled; not recursed. Deep local `.qml` deps are a follow-up —
      // for now import each helper `.qml` you reference, or keep the file self-contained.
      if (imp.spec.endsWith(".qml")) {
        const qabs = path.resolve(mod.dir, imp.spec);
        const base = path.basename(qabs, ".qml");
        if (!/^[A-Z][A-Za-z0-9_]*$/.test(base))
          throw new Error(`custom QML import needs a Capitalized, identifier-safe filename (a QML type name): ${imp.spec}`);
        const qkey = `qml:${qabs}`;
        if (!qmlForeign.has(qkey)) qmlForeign.set(qkey, { typeName: base, source: await readFile(qabs) });
        edges.set(tag, qkey);
        continue;
      }
      const res = await resolveModule(mod.dir, imp.spec, readFile);
      if (!res) continue;
      const childMod = await load(res.path, res.source);
      const childName = imp.imported === "default" ? defaultComponentName(childMod) : imp.imported;
      if (!childName) throw new Error(`no component for import ${tag} from ${imp.spec}`);
      edges.set(tag, keyOf(res.path, childName)); // <Hello> → greet.tsx#Greeting
      await visit(res.path, childMod, childName);
    }
  };
  await visit(entryPath, entryMod, entryName);

  // Assign unique QML type names: declared name, or path-prefixed on collision.
  const byDecl = new Map<string, string[]>(); // declName → [node keys]
  for (const [key, n] of nodes) (byDecl.get(n.declName) ?? byDecl.set(n.declName, []).get(n.declName)!).push(key);
  const typeName = new Map<string, string>(); // node key → QML type name
  for (const [decl, keys] of byDecl) {
    if (keys.length === 1) typeName.set(keys[0], decl);
    else for (const key of keys) typeName.set(key, `${decl}_${pathPrefix(nodes.get(key)!.absPath)}`);
  }
  // Foreign `.qml` nodes carry their filename basename as the QML type name.
  for (const [qkey, { typeName: tn }] of qmlForeign) typeName.set(qkey, tn);

  // Phase 1b — context roles: classify each node as a provider (provides a ctx + value shape) and/or
  // a consumer (useContext bindings). Build the cross-graph ctx → value-shape table that consumers
  // resolve member access through. Defer multi-context cases per the scope guard.
  interface CtxRole { provider: ReturnType<typeof analyzeProvider>; consumes: { local: string; ctx: string }[]; }
  const ctxRole = new Map<string, CtxRole>(); // node key → role
  const ctxValueShape: Record<string, Record<string, "accessor" | "fn">> = {};
  for (const [key, node] of nodes) {
    const info = node.mod.comps.get(node.declName)!;
    const provider = node.mod.contexts.size ? analyzeProvider(info.fn, analyzeSignals(info.fn), node.mod.contexts) : null;
    const consumes = node.mod.contexts.size ? analyzeUseContext(info.fn, node.mod.contexts) : [];
    ctxRole.set(key, { provider, consumes });
    if (provider) {
      if (ctxValueShape[provider.ctx]) throw new Error(`multiple providers for context ${provider.ctx} — not supported in this plan`);
      ctxValueShape[provider.ctx] = provider.valueShape;
    }
  }

  // Phase 2 — emit: one QML type per node.
  const components: Record<string, string> = {};
  let entry = "";
  const entryKey = keyOf(entryPath, entryName);
  for (const [key, node] of nodes) {
    const typeMap = new Map<string, string>(); // use-name → emitted type name (from this node's edges)
    const componentMeta = new Map<string, { provides?: string; consumes?: string[] }>(); // use-name → ctx role
    for (const [useName, targetKey] of node.edges) {
      typeMap.set(useName, typeName.get(targetKey)!);
      const role = ctxRole.get(targetKey);
      if (role && (role.provider || role.consumes.length)) {
        componentMeta.set(useName, {
          ...(role.provider ? { provides: role.provider.ctx } : {}),
          ...(role.consumes.length ? { consumes: role.consumes.map((c) => c.ctx) } : {}),
        });
      }
    }
    const info = node.mod.comps.get(node.declName)!;
    const role = ctxRole.get(key)!;
    const ctxWiring = {
      useContext: role.consumes,
      componentMeta: componentMeta.size ? componentMeta : undefined,
      ctxValueShape,
    };
    // Import-time module statements across the whole graph run once, at the entry's boot.
    const moduleInit = key === entryKey ? [...modules.values()].flatMap((m) => m.moduleInit) : undefined;
    const foreignQml = new Set([...qmlForeign.values()].map((q) => q.typeName));
    const qml = [...headerFor(node.mod), ...emitComponentType(info.fn, info.render, typeMap, node.mod.contexts, role.provider, ctxWiring, node.mod.file, node.mod.jsImports, moduleInit, foreignQml), ""].join("\n");
    if (key === entryKey) entry = qml;
    else components[typeName.get(key)!] = qml;
  }
  // Custom `.qml` files ride `components` verbatim — gen.mjs writes each as `<name>.qml`.
  for (const [, { typeName: tn, source }] of qmlForeign) components[tn] = source;
  // CSS sidecar: concatenate every imported .css across the graph, in discovery order.
  let css = "";
  for (const f of cssFiles) {
    try { css += (css ? "\n\n" : "") + await readFile(f); } catch { /* a missing/unreadable css is skipped */ }
  }
  return { entry, components, css, modules: Object.fromEntries([...mirroredModules].sort(([a], [b]) => a.localeCompare(b))) };
}

function headerFor(mod: Mod): string[] {
  return [
    ...HEADER,
    ...[...mod.qmlImports].map(([outPath, alias]) => `import "${outPath}" as ${alias}`),
    "",
  ];
}
