// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Window {
    id: __self
    visible: true
    width: 760
    height: 520
    title: "solid-qml"
    Css.CssRect {
        anchors.fill: parent
        cssClass: ["qml-window"]
        cssPrimitive: "window"
        Gallery {
        }
    }
}
