// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets.Chart 1.0 as WChart
import solidqml.Widgets.Media 1.0 as WMedia
import solidqml.Widgets.Scene3D 1.0 as WScene3D
import solidqml.Widgets.Surface 1.0 as WSurface

import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    readonly property var isNative: typeof process !== "undefined" && !!process.versions && process.versions.solidQml
    cssClass: ["dv"]
    W.Text {
        cssClass: ["dv-h"]
        text: "Charts & 3D"
    }
    W.Text {
        cssClass: ["dv-sub"]
        text: "Optional opt-in modules — QtGraphs & Qt Quick 3D, imported only when used."
    }
    W.Div {
        cssClass: ["dv-card"]
        visible: !!(isNative)
        W.Text {
            cssClass: ["dv-label"]
            text: "Complex plot — area · splines · scatter, hover for values (QtGraphs)"
        }
        WChart.Chart {
            cssClass: ["dv-chart"]
        }
    }
    W.Div {
        cssClass: ["dv-card"]
        visible: !!(isNative)
        W.Text {
            cssClass: ["dv-label"]
            text: "Blender monkey · three-point lighting, spinning (Qt Quick 3D)"
        }
        WScene3D.Scene3D {
            cssClass: ["dv-scene"]
        }
    }
    W.Div {
        cssClass: ["dv-card"]
        visible: !!(isNative)
        W.Text {
            cssClass: ["dv-label"]
            text: "Media player — video + play/seek/clock (QtMultimedia)"
        }
        WMedia.MediaPlayer {
            cssClass: ["dv-media"]
            src: Qt.resolvedUrl("assets/media-demo.mp4")
            autoplay: true
        }
    }
    W.Div {
        cssClass: ["dv-card"]
        visible: !!(isNative)
        W.Text {
            cssClass: ["dv-label"]
            text: "Walker Lake topography — heat-mapped 3D surface, mouse-driven (QtGraphs Surface3D)"
        }
        WSurface.Surface {
            cssClass: ["dv-surface"]
        }
    }
    W.Div {
        visible: !(isNative)
        cssClass: ["dv-fallback"]
        W.Text {
            cssClass: ["dv-fallback-t"]
            text: "charts & 3D — run this view in the QML loader"
        }
    }
}
