// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    cssClass: ["app"]
    cssPrimitive: "div"
    Card {
        Css.CssText {
            cssClass: ["title"]
            cssPrimitive: "text"
            text: "Inside the card"
        }
        Css.CssText {
            cssPrimitive: "text"
            text: "slotted via props.children"
        }
    }
}
