// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import QtQuick.Templates 6.0 as T
Css.CssRect {
    id: __self
    property var tab: 0
    property var drawerOpen: false
    property var page: 0
    cssClass: ["nv-section", "containers"]
    cssPrimitive: "div"
    Css.CssText {
        cssClass: ["nv-title"]
        cssPrimitive: "text"
        text: "Containers"
    }
    Css.CssText {
        cssClass: ["nv-label"]
        cssPrimitive: "text"
        text: "ToolBar"
    }
    Css.CssFill {
        cssClass: ["ct-toolbar"]
        cssPrimitive: "toolbar"
        T.ToolBar {
            anchors.fill: parent
            background: null
            contentItem: Item { }
        }
        Css.CssFill {
            cssClass: ["ct-tool"]
            cssState: __hover0.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "☰ Menu"
            }
            MouseArea {
                id: __hover0
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: drawerOpen = true
            }
        }
        Css.CssFill {
            cssClass: ["ct-tool"]
            cssState: __hover1.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Home"
            }
            MouseArea {
                id: __hover1
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: tab = 0
            }
        }
        Css.CssFill {
            cssClass: ["ct-tool"]
            cssState: __hover2.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Reset pages"
            }
            MouseArea {
                id: __hover2
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: page = 0
            }
        }
    }
    Css.CssText {
        cssClass: ["nv-label"]
        cssPrimitive: "text"
        text: "TabBar + StackView"
    }
    Css.CssFill {
        cssClass: ["ct-tabs"]
        cssPrimitive: "tabbar"
        implicitWidth: __tabbar0.implicitWidth
        implicitHeight: __tabbar0.implicitHeight
        T.TabBar {
            id: __tabbar0
            anchors.fill: parent
            implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
            implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
            background: null
            contentItem: ListView {
                model: __tabbar0.contentModel
                currentIndex: __tabbar0.currentIndex
                spacing: __tabbar0.spacing
                orientation: ListView.Horizontal
                boundsBehavior: Flickable.StopAtBounds
                flickableDirection: Flickable.AutoFlickIfNeeded
                snapMode: ListView.SnapToItem
                highlightMoveDuration: 0
            }
            onCurrentIndexChanged: { tab = __tabbar0.currentIndex }
            T.TabButton {
                id: __tab0_0
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
                padding: 8
                activeFocusOnTab: solidTabstop.enabled
                background: Css.CssFill {
                    cssPrimitive: "div"
                    cssClass: ["tab"]
                    cssState: (__tab0_0.checked ? ["selected"] : []).concat(__tab0_0.hovered ? ["hover"] : [])
                }
                contentItem: Css.CssText {
                    cssPrimitive: ""
                    cssClass: ["tab-label"]
                    cssState: (__tab0_0.checked ? ["selected"] : []).concat(__tab0_0.hovered ? ["hover"] : [])
                    text: "Overview"
                }
            }
            T.TabButton {
                id: __tab0_1
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
                padding: 8
                activeFocusOnTab: solidTabstop.enabled
                background: Css.CssFill {
                    cssPrimitive: "div"
                    cssClass: ["tab"]
                    cssState: (__tab0_1.checked ? ["selected"] : []).concat(__tab0_1.hovered ? ["hover"] : [])
                }
                contentItem: Css.CssText {
                    cssPrimitive: ""
                    cssClass: ["tab-label"]
                    cssState: (__tab0_1.checked ? ["selected"] : []).concat(__tab0_1.hovered ? ["hover"] : [])
                    text: "Details"
                }
            }
            T.TabButton {
                id: __tab0_2
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
                padding: 8
                activeFocusOnTab: solidTabstop.enabled
                background: Css.CssFill {
                    cssPrimitive: "div"
                    cssClass: ["tab"]
                    cssState: (__tab0_2.checked ? ["selected"] : []).concat(__tab0_2.hovered ? ["hover"] : [])
                }
                contentItem: Css.CssText {
                    cssPrimitive: ""
                    cssClass: ["tab-label"]
                    cssState: (__tab0_2.checked ? ["selected"] : []).concat(__tab0_2.hovered ? ["hover"] : [])
                    text: "Settings"
                }
            }
        }
        Binding {
            target: __tabbar0
            property: "currentIndex"
            value: tab
            restoreMode: Binding.RestoreNone
        }
    }
    Css.CssRect {
        cssClass: ["ct-stack"]
        cssPrimitive: "stack"
        Css.CssRect {
            cssClass: ["ct-page"]
            visible: !!((tab) === 0)
            cssPrimitive: "div"
            Css.CssText {
                cssClass: ["ct-page-t"]
                cssPrimitive: "text"
                text: "Overview — the first tab's page."
            }
        }
        Css.CssRect {
            cssClass: ["ct-page"]
            visible: !!((tab) === 1)
            cssPrimitive: "div"
            Css.CssText {
                cssClass: ["ct-page-t"]
                cssPrimitive: "text"
                text: "Details — swap tabs above to switch this content."
            }
        }
        Css.CssRect {
            cssClass: ["ct-page"]
            visible: !!((tab) === 2)
            cssPrimitive: "div"
            Css.CssText {
                cssClass: ["ct-page-t"]
                cssPrimitive: "text"
                text: "Settings — page three of the stack."
            }
        }
    }
    Css.CssText {
        cssClass: ["nv-label"]
        cssPrimitive: "text"
        text: "SplitView"
    }
    Css.CssFill {
        cssClass: ["ct-split"]
        id: __split1W
        cssPrimitive: "splitview"
        T.SplitView {
            id: __split1
            anchors.fill: parent
            orientation: Qt.Horizontal
            handle: SplitHandle {
                cssAncestor: __split1W
                horizontal: __split1.orientation === Qt.Horizontal
            }
            Css.CssRect {
                T.SplitView.fillWidth: true
                cssClass: ["ct-pane"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["ct-pane-t"]
                    cssPrimitive: "text"
                    text: "Left pane — drag the handle."
                }
            }
            Css.CssRect {
                T.SplitView.fillWidth: true
                cssClass: ["ct-pane", "ct-pane-alt"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["ct-pane-t"]
                    cssPrimitive: "text"
                    text: "Right pane."
                }
            }
        }
    }
    Css.CssText {
        cssClass: ["nv-label"]
        cssPrimitive: "text"
        text: "Drawer"
    }
    Css.CssRect {
        cssClass: ["nv-row"]
        cssPrimitive: "div"
        Css.CssFill {
            cssClass: ["ct-open"]
            cssState: __hover3.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Open drawer"
            }
            MouseArea {
                id: __hover3
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: drawerOpen = true
            }
        }
        Css.CssText {
            cssClass: ["ct-state"]
            cssPrimitive: "text"
            text: "" + (drawerOpen ? "open" : "closed")
        }
    }
    Css.CssItem {
        cssClass: ["ct-drawer"]
        id: __drawer2W
        cssPrimitive: "drawer"
        T.Drawer {
            id: __drawer2
            parent: T.Overlay.overlay
            edge: Qt.LeftEdge
            dragMargin: 0
            width: parent ? parent.width * (0.34) : 0
            height: parent ? parent.height : 0
            enter: Transition { NumberAnimation { property: "position"; to: 1.0; duration: 220; easing.type: Easing.OutCubic } }
            exit: Transition { NumberAnimation { property: "position"; to: 0.0; duration: 180; easing.type: Easing.InCubic } }
            T.Overlay.modal: Rectangle { color: "#66000000" }
            background: Css.CssFill {
                property Item cssAncestor: __drawer2W
                cssPrimitive: "div"
                cssClass: ["panel"]
            }
            contentItem: Css.CssFill {
                property Item cssAncestor: __drawer2W
                cssPrimitive: "div"
                cssClass: ["content"]
                Css.CssText {
                    cssClass: ["ct-drawer-title"]
                    cssPrimitive: "text"
                    text: "Navigation"
                }
                Css.CssText {
                    cssClass: ["ct-drawer-item"]
                    cssPrimitive: "text"
                    text: "Home"
                }
                Css.CssText {
                    cssClass: ["ct-drawer-item"]
                    cssPrimitive: "text"
                    text: "Profile"
                }
                Css.CssText {
                    cssClass: ["ct-drawer-item"]
                    cssPrimitive: "text"
                    text: "Preferences"
                }
                Css.CssFill {
                    cssClass: ["ct-close"]
                    cssState: __hover4.containsMouse ? ["hover"] : []
                    cssPrimitive: "button"
                    Css.CssText {
                        cssPrimitive: "text"
                        text: "Close"
                    }
                    MouseArea {
                        id: __hover4
                        anchors.fill: parent
                        hoverEnabled: true
                        cursorShape: Qt.PointingHandCursor
                        onClicked: drawerOpen = false
                    }
                }
            }
            onClosed: { drawerOpen = false }
        }
        Binding {
            target: __drawer2
            property: "visible"
            value: !!(drawerOpen)
            restoreMode: Binding.RestoreNone
        }
    }
    Css.CssText {
        cssClass: ["nv-label"]
        cssPrimitive: "text"
        text: "SwipeView"
    }
    Css.CssFill {
        cssClass: ["ct-swipe"]
        cssPrimitive: "swipeview"
        implicitWidth: __swipe3.implicitWidth
        implicitHeight: __swipe3.implicitHeight
        T.SwipeView {
            id: __swipe3
            anchors.fill: parent
            implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
            implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
            background: null
            contentItem: ListView {
                model: __swipe3.contentModel
                interactive: __swipe3.interactive
                currentIndex: __swipe3.currentIndex
                spacing: __swipe3.spacing
                orientation: __swipe3.orientation
                snapMode: ListView.SnapOneItem
                boundsBehavior: Flickable.StopAtBounds
                highlightRangeMode: ListView.StrictlyEnforceRange
                preferredHighlightBegin: 0
                preferredHighlightEnd: 0
                highlightMoveDuration: 250
                clip: true
            }
            onCurrentIndexChanged: { page = __swipe3.currentIndex }
            Css.CssRect {
                cssClass: ["ct-slide", "ct-slide-a"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["ct-slide-t"]
                    cssPrimitive: "text"
                    text: "Page one — swipe or use the buttons."
                }
            }
            Css.CssRect {
                cssClass: ["ct-slide", "ct-slide-b"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["ct-slide-t"]
                    cssPrimitive: "text"
                    text: "Page two."
                }
            }
            Css.CssRect {
                cssClass: ["ct-slide", "ct-slide-c"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["ct-slide-t"]
                    cssPrimitive: "text"
                    text: "Page three."
                }
            }
        }
        Binding {
            target: __swipe3
            property: "currentIndex"
            value: page
            restoreMode: Binding.RestoreNone
        }
    }
    Css.CssRect {
        cssClass: ["nv-row"]
        cssPrimitive: "div"
        Css.CssFill {
            cssClass: ["ct-nav"]
            cssState: __hover5.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "‹ Prev"
            }
            MouseArea {
                id: __hover5
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: page = (page + 2) % 3
            }
        }
        Css.CssFill {
            cssClass: ["ct-dots"]
            cssPrimitive: "pageindicator"
            implicitWidth: __dots4.implicitWidth
            implicitHeight: __dots4.implicitHeight
            T.PageIndicator {
                id: __dots4
                anchors.fill: parent
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
                background: null
                count: 3
                currentIndex: page
                spacing: 6
                delegate: Css.CssRect {
                    required property int index
                    cssPrimitive: "div"
                    cssClass: ["dot"]
                    cssState: index === __dots4.currentIndex ? ["selected"] : []
                    implicitWidth: 8
                    implicitHeight: 8
                }
                contentItem: Row {
                    spacing: __dots4.spacing
                    Repeater {
                        model: __dots4.count
                        delegate: __dots4.delegate
                    }
                }
            }
        }
        Css.CssFill {
            cssClass: ["ct-nav"]
            cssState: __hover6.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Next ›"
            }
            MouseArea {
                id: __hover6
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: page = (page + 1) % 3
            }
        }
    }
}
