// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    cssClass: ["app"]
    cssPrimitive: "div"
    Counter {
        label: "A"
    }
    Counter {
        label: "B"
    }
    Counter {
        label: "C"
    }
}
