// Generated by the transpiler. Do not edit by hand.
import QtQuick
import "qrc:/qmlcss" as Css

Css.CssRect {
    id: __self
    property var count: 0
    property var increment: function() { return count = count + 1 }
    cssPrimitive: "div"
}
