// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    cssClass: ["app"]
    Counter {
        label: "A"
    }
    Counter {
        label: "B"
    }
    Counter {
        label: "C"
    }
}
