// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    cssClass: ["gaps"]
    W.Div {
        cssClass: ["stack"]
        W.Div {
            cssClass: ["z", "z1"]
            Css.CssText {
                cssPrimitive: ""
                text: "1"
            }
        }
        W.Div {
            cssClass: ["z", "z2"]
            Css.CssText {
                cssPrimitive: ""
                text: "2"
            }
        }
        W.Div {
            cssClass: ["z", "z3"]
            Css.CssText {
                cssPrimitive: ""
                text: "3"
            }
        }
    }
    W.Div {
        cssClass: ["row"]
        W.Div {
            cssClass: ["cell", "op"]
            Css.CssText {
                cssPrimitive: ""
                text: "op .4"
            }
        }
        W.Div {
            cssClass: ["cell", "rot"]
            Css.CssText {
                cssPrimitive: ""
                text: "rot"
            }
        }
        W.Div {
            cssClass: ["cell", "scl"]
            Css.CssText {
                cssPrimitive: ""
                text: "scale"
            }
        }
        W.Div {
            cssClass: ["cell", "vis"]
            Css.CssText {
                cssPrimitive: ""
                text: "vis"
            }
        }
        W.Div {
            cssClass: ["cell", "hid"]
            Css.CssText {
                cssPrimitive: ""
                text: "hidden"
            }
        }
        W.Div {
            cssClass: ["cell", "none"]
            Css.CssText {
                cssPrimitive: ""
                text: "none"
            }
        }
        W.Div {
            cssClass: ["cell", "clip"]
            Css.CssText {
                cssPrimitive: ""
                text: "overflow"
            }
            W.Div {
                cssClass: ["spill"]
                Css.CssText {
                    cssPrimitive: ""
                    text: "spill"
                }
            }
        }
    }
    W.Div {
        cssClass: ["flex"]
        W.Div {
            cssClass: ["fi", "a"]
            Css.CssText {
                cssPrimitive: ""
                text: "A·1"
            }
        }
        W.Div {
            cssClass: ["fi", "b"]
            Css.CssText {
                cssPrimitive: ""
                text: "B·2"
            }
        }
        W.Div {
            cssClass: ["fi", "c"]
            Css.CssText {
                cssPrimitive: ""
                text: "C·0"
            }
        }
    }
    W.Div {
        cssClass: ["shrink"]
        W.Div {
            cssClass: ["si"]
            Css.CssText {
                cssPrimitive: ""
                text: "shrink 220"
            }
        }
        W.Div {
            cssClass: ["si"]
            Css.CssText {
                cssPrimitive: ""
                text: "shrink 220"
            }
        }
        W.Div {
            cssClass: ["si"]
            Css.CssText {
                cssPrimitive: ""
                text: "shrink 220"
            }
        }
    }
    W.Div {
        cssClass: ["row"]
        W.Div {
            cssClass: ["bs", "border"]
            Css.CssText {
                cssPrimitive: ""
                text: "border-box 120"
            }
        }
        W.Div {
            cssClass: ["bs", "content"]
            Css.CssText {
                cssPrimitive: ""
                text: "content-box →160"
            }
        }
    }
    W.Div {
        cssClass: ["grid"]
        W.Div {
            cssClass: ["g", "head"]
            Css.CssText {
                cssPrimitive: ""
                text: "header"
            }
        }
        W.Div {
            cssClass: ["g", "side"]
            Css.CssText {
                cssPrimitive: ""
                text: "side"
            }
        }
        W.Div {
            cssClass: ["g", "main"]
            Css.CssText {
                cssPrimitive: ""
                text: "main"
            }
        }
    }
    W.Div {
        cssClass: ["textbox"]
        W.Text {
            cssClass: ["t", "wrap"]
            text: "max-width 260: this sentence must wrap onto a second line instead of overflowing"
        }
        W.Text {
            cssClass: ["t", "underline"]
            text: "underline"
        }
        W.Text {
            cssClass: ["t", "strike"]
            text: "line-through"
        }
        W.Text {
            cssClass: ["t", "nowrap"]
            text: "white-space:nowrap keeps this on one clipped line no matter what"
        }
        W.Text {
            cssClass: ["t", "ellipsis"]
            text: "text-overflow ellipsis truncates this long line with a trailing…"
        }
        W.Text {
            cssClass: ["t", "upper"]
            text: "text-transform uppercase"
        }
        W.Text {
            cssClass: ["t", "spaced"]
            text: "letter + word spacing"
        }
    }
}
