// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    cssClass: ["gaps"]
    cssPrimitive: "div"
    Css.CssRect {
        cssClass: ["stack"]
        cssPrimitive: "div"
        Css.CssRect {
            cssClass: ["z", "z1"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "1"
            }
        }
        Css.CssRect {
            cssClass: ["z", "z2"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "2"
            }
        }
        Css.CssRect {
            cssClass: ["z", "z3"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "3"
            }
        }
    }
    Css.CssRect {
        cssClass: ["row"]
        cssPrimitive: "div"
        Css.CssRect {
            cssClass: ["cell", "op"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "op .4"
            }
        }
        Css.CssRect {
            cssClass: ["cell", "rot"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "rot"
            }
        }
        Css.CssRect {
            cssClass: ["cell", "scl"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "scale"
            }
        }
        Css.CssRect {
            cssClass: ["cell", "vis"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "vis"
            }
        }
        Css.CssRect {
            cssClass: ["cell", "hid"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "hidden"
            }
        }
        Css.CssRect {
            cssClass: ["cell", "none"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "none"
            }
        }
        Css.CssRect {
            cssClass: ["cell", "clip"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "overflow"
            }
            Css.CssRect {
                cssClass: ["spill"]
                cssPrimitive: "div"
                Css.CssText {
                    cssPrimitive: ""
                    text: "spill"
                }
            }
        }
    }
    Css.CssRect {
        cssClass: ["flex"]
        cssPrimitive: "div"
        Css.CssRect {
            cssClass: ["fi", "a"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "A·1"
            }
        }
        Css.CssRect {
            cssClass: ["fi", "b"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "B·2"
            }
        }
        Css.CssRect {
            cssClass: ["fi", "c"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "C·0"
            }
        }
    }
    Css.CssRect {
        cssClass: ["shrink"]
        cssPrimitive: "div"
        Css.CssRect {
            cssClass: ["si"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "shrink 220"
            }
        }
        Css.CssRect {
            cssClass: ["si"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "shrink 220"
            }
        }
        Css.CssRect {
            cssClass: ["si"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "shrink 220"
            }
        }
    }
    Css.CssRect {
        cssClass: ["row"]
        cssPrimitive: "div"
        Css.CssRect {
            cssClass: ["bs", "border"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "border-box 120"
            }
        }
        Css.CssRect {
            cssClass: ["bs", "content"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "content-box →160"
            }
        }
    }
    Css.CssRect {
        cssClass: ["grid"]
        cssPrimitive: "div"
        Css.CssRect {
            cssClass: ["g", "head"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "header"
            }
        }
        Css.CssRect {
            cssClass: ["g", "side"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "side"
            }
        }
        Css.CssRect {
            cssClass: ["g", "main"]
            cssPrimitive: "div"
            Css.CssText {
                cssPrimitive: ""
                text: "main"
            }
        }
    }
    Css.CssRect {
        cssClass: ["textbox"]
        cssPrimitive: "div"
        Css.CssText {
            cssClass: ["t", "wrap"]
            cssPrimitive: "text"
            text: "max-width 260: this sentence must wrap onto a second line instead of overflowing"
        }
        Css.CssText {
            cssClass: ["t", "underline"]
            cssPrimitive: "text"
            text: "underline"
        }
        Css.CssText {
            cssClass: ["t", "strike"]
            cssPrimitive: "text"
            text: "line-through"
        }
        Css.CssText {
            cssClass: ["t", "nowrap"]
            cssPrimitive: "text"
            text: "white-space:nowrap keeps this on one clipped line no matter what"
        }
        Css.CssText {
            cssClass: ["t", "ellipsis"]
            cssPrimitive: "text"
            text: "text-overflow ellipsis truncates this long line with a trailing…"
        }
        Css.CssText {
            cssClass: ["t", "upper"]
            cssPrimitive: "text"
            text: "text-transform uppercase"
        }
        Css.CssText {
            cssClass: ["t", "spaced"]
            cssPrimitive: "text"
            text: "letter + word spacing"
        }
    }
}
