// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    property var clicks: 0
    property var stars: 0
    cssClass: ["nv-section"]
    cssPrimitive: "div"
    Css.CssText {
        cssClass: ["nv-title"]
        cssPrimitive: "text"
        text: "Custom QML (escape hatch)"
    }
    Css.CssRect {
        cssClass: ["nv-row"]
        cssPrimitive: "div"
        Css.CssRect {
            cssPrimitive: "div"
            Badge {
                label: "clicks"
                count: clicks
                onBumped: function() { return clicks = clicks + 1 }
            }
        }
        Css.CssRect {
            cssPrimitive: "div"
            Badge {
                label: "stars"
                count: stars
                onBumped: function() { return stars = stars + 1 }
            }
        }
        Css.CssText {
            cssClass: ["nv-echo"]
            cssPrimitive: "text"
            text: "imported straight from Badge.qml"
        }
    }
}
