// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var clicks: 0
    property var stars: 0
    cssClass: ["nv-section"]
    W.Text {
        cssClass: ["nv-title"]
        text: "Custom QML (escape hatch)"
    }
    W.Div {
        cssClass: ["nv-row"]
        Css.CssRect {
            cssPrimitive: "div"
            Badge {
                anchors.fill: parent
                label: "clicks"
                count: clicks
                onBumped: function() { return clicks = clicks + 1 }
            }
        }
        Css.CssRect {
            cssPrimitive: "div"
            Badge {
                anchors.fill: parent
                label: "stars"
                count: stars
                onBumped: function() { return stars = stars + 1 }
            }
        }
        W.Text {
            cssClass: ["nv-echo"]
            text: "imported straight from Badge.qml"
        }
    }
}
