// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    property var page: "overview"
    property var slide: 0
    property var collapsed: false
    readonly property var __const_MENU: [({ id: "overview", label: "Overview", icon: "▤", badge: "" }), ({ id: "analytics", label: "Analytics", icon: "◔", badge: "3" }), ({ id: "projects", label: "Projects", icon: "▦", badge: "12" }), ({ id: "settings", label: "Settings", icon: "✦", badge: "" })]
    readonly property var __const_STATS: [({ label: "Revenue", value: "48.2k", delta: "+12.4%", up: true }), ({ label: "Active users", value: "1 284", delta: "+3.1%", up: true }), ({ label: "Churn", value: "2.4%", delta: "-0.8%", up: false }), ({ label: "Uptime", value: "99.98%", delta: "+0.01%", up: true })]
    readonly property var __const_SLIDES: [({ src: "../../assets/slide-aurora.png", caption: "Aurora — GPU scene graph" }), ({ src: "../../assets/slide-ocean.png", caption: "Ocean — CSS gradient engine" }), ({ src: "../../assets/slide-ember.png", caption: "Ember — @keyframes driver" })]
    readonly property var __const_FEED: [({ who: "AC", name: "Ana Costa", what: "deployed dashboard v2 to production", when: "2 min", tag: "deploy", ok: true }), ({ who: "RM", name: "Rui Matos", what: "opened PR #142 — carousel easing", when: "18 min", tag: "review", ok: true }), ({ who: "LS", name: "Lia Souza", what: "pipeline failed on test-css step", when: "41 min", tag: "ci", ok: false }), ({ who: "JP", name: "João Prado", what: "published qml-css-engine 0.2.0", when: "1 h", tag: "release", ok: true })]
    readonly property var __const_PROJECTS: [({ name: "qml-css-engine", desc: "CSS cascade, paint & layout in C++", pct: "p80", status: "active" }), ({ name: "transpiler v2", desc: "Solid JSX → structural QML", pct: "p65", status: "active" }), ({ name: "npm mirror", desc: "node modules on the V4 engine", pct: "p45", status: "beta" }), ({ name: "AOT C++ target", desc: "QtQuick C++ 1:1 generation", pct: "p10", status: "design" })]
    property var __cleanups: []
    Component.onCompleted: { var timer = setInterval(function() { return slide = (slide + 1) % 3 }, 4000); __cleanups.push(function() { return clearInterval(timer) }); }
    Component.onDestruction: { for (var i = 0; i < __cleanups.length; i++) __cleanups[i](); }
    cssClass: ["dash"]
    cssPrimitive: "div"
    Css.CssRect {
        cssClass: ["dash-side"].concat(collapsed ? ["collapsed"] : [])
        cssPrimitive: "div"
        Css.CssRect {
            cssClass: ["dash-brand"]
            cssPrimitive: "div"
            Css.CssRect {
                cssClass: ["dash-logo"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["dash-logo-q"]
                    cssPrimitive: "text"
                    text: "Q"
                }
            }
            Css.CssText {
                cssClass: ["dash-name"]
                cssPrimitive: "text"
                text: "solid-qml"
            }
        }
        Repeater {
            model: __const_MENU
            Css.CssRect {
                cssClass: ["dash-item"].concat(page === modelData.id ? ["active"] : [])
                cssState: __hover0.containsMouse ? ["hover"] : []
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["dash-icon"]
                    cssPrimitive: "text"
                    text: "" + (modelData.icon)
                }
                Css.CssText {
                    cssClass: ["dash-label"]
                    cssPrimitive: "text"
                    text: "" + (modelData.label)
                }
                Css.CssRect {
                    cssClass: ["dash-badge"]
                    visible: !!(modelData.badge !== "")
                    cssPrimitive: "div"
                    Css.CssText {
                        cssClass: ["dash-badge-n"]
                        cssPrimitive: "text"
                        text: "" + (modelData.badge)
                    }
                }
                MouseArea {
                    id: __hover0
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor
                    onClicked: page = modelData.id
                }
            }
        }
        Css.CssRect {
            cssClass: ["dash-spring"]
            cssPrimitive: "div"
        }
        Css.CssRect {
            cssClass: ["side-toggle"]
            cssState: __hover1.containsMouse ? ["hover"] : []
            cssPrimitive: "div"
            Css.CssText {
                cssClass: ["side-toggle-t"]
                cssPrimitive: "text"
                text: "" + (collapsed ? "»" : "«")
            }
            MouseArea {
                id: __hover1
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: collapsed = !collapsed
            }
        }
        Css.CssRect {
            cssClass: ["dash-foot"]
            cssPrimitive: "div"
            Css.CssText {
                cssClass: ["dash-foot-t"]
                cssPrimitive: "text"
                text: "engine stress test"
            }
        }
    }
    Css.CssRect {
        cssClass: ["dash-main"]
        cssPrimitive: "div"
        Css.CssRect {
            cssClass: ["dash-top"]
            cssPrimitive: "div"
            Css.CssRect {
                cssClass: ["dash-title-wrap"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["dash-title"]
                    cssPrimitive: "text"
                    text: "" + (page)
                }
                Css.CssRect {
                    cssClass: ["dash-title-accent"]
                    cssPrimitive: "div"
                }
            }
            Css.CssRect {
                cssClass: ["dash-user"]
                cssPrimitive: "div"
                Css.CssRect {
                    cssClass: ["dash-avatar-ring"]
                    cssPrimitive: "div"
                    Css.CssRect {
                        cssClass: ["dash-avatar"]
                        cssPrimitive: "div"
                        Css.CssText {
                            cssClass: ["dash-avatar-t"]
                            cssPrimitive: "text"
                            text: "AL"
                        }
                    }
                }
                Css.CssText {
                    cssClass: ["dash-user-n"]
                    cssPrimitive: "text"
                    text: "ada"
                }
            }
        }
        Repeater {
            model: (page === "overview") ? 1 : 0
            Css.CssRect {
                cssClass: ["dash-page"]
                cssPrimitive: "div"
                Css.CssRect {
                    cssClass: ["stat-row"]
                    cssPrimitive: "div"
                    Repeater {
                        model: __const_STATS
                        Css.CssRect {
                            cssClass: ["stat"]
                            cssPrimitive: "div"
                            Css.CssText {
                                cssClass: ["stat-label"]
                                cssPrimitive: "text"
                                text: "" + (modelData.label)
                            }
                            Css.CssText {
                                cssClass: ["stat-value"]
                                cssPrimitive: "text"
                                text: "" + (modelData.value)
                            }
                            Css.CssRect {
                                cssClass: ["stat-delta"].concat(!modelData.up ? ["down"] : [])
                                cssPrimitive: "div"
                                Css.CssText {
                                    cssClass: ["stat-delta-t"]
                                    cssPrimitive: "text"
                                    text: "" + (modelData.delta)
                                }
                            }
                        }
                    }
                }
                Css.CssRect {
                    cssClass: ["carousel"]
                    cssPrimitive: "div"
                    Repeater {
                        model: __const_SLIDES
                        Css.CssRect {
                            cssClass: ["slide"].concat(slide === index ? ["current"] : [])
                            cssPrimitive: "div"
                            Css.CssImage {
                                cssClass: ["slide-img"]
                                source: modelData.src || ""
                            }
                            Css.CssRect {
                                cssClass: ["slide-cap"]
                                cssPrimitive: "div"
                                Css.CssText {
                                    cssClass: ["slide-cap-t"]
                                    cssPrimitive: "text"
                                    text: "" + (modelData.caption)
                                }
                            }
                        }
                    }
                    Css.CssFill {
                        cssClass: ["c-nav", "c-prev"]
                        cssState: __hover2.containsMouse ? ["hover"] : []
                        cssPrimitive: "button"
                        Css.CssText {
                            cssPrimitive: "text"
                            text: "‹"
                        }
                        MouseArea {
                            id: __hover2
                            anchors.fill: parent
                            hoverEnabled: true
                            cursorShape: Qt.PointingHandCursor
                            onClicked: slide = (slide + 2) % 3
                        }
                    }
                    Css.CssFill {
                        cssClass: ["c-nav", "c-next"]
                        cssState: __hover3.containsMouse ? ["hover"] : []
                        cssPrimitive: "button"
                        Css.CssText {
                            cssPrimitive: "text"
                            text: "›"
                        }
                        MouseArea {
                            id: __hover3
                            anchors.fill: parent
                            hoverEnabled: true
                            cursorShape: Qt.PointingHandCursor
                            onClicked: slide = (slide + 1) % 3
                        }
                    }
                    Css.CssRect {
                        cssClass: ["dots"]
                        cssPrimitive: "div"
                        Repeater {
                            model: __const_SLIDES
                            Css.CssRect {
                                cssClass: ["dot"].concat(slide === index ? ["on"] : [])
                                cssState: __hover4.containsMouse ? ["hover"] : []
                                cssPrimitive: "div"
                                MouseArea {
                                    id: __hover4
                                    anchors.fill: parent
                                    hoverEnabled: true
                                    cursorShape: Qt.PointingHandCursor
                                    onClicked: slide = index
                                }
                            }
                        }
                    }
                }
                Css.CssRect {
                    cssClass: ["feed"]
                    cssPrimitive: "div"
                    Css.CssText {
                        cssClass: ["feed-h"]
                        cssPrimitive: "text"
                        text: "Recent activity"
                    }
                    Repeater {
                        model: __const_FEED
                        Css.CssRect {
                            cssClass: ["feed-row"]
                            cssPrimitive: "div"
                            Css.CssRect {
                                cssClass: ["feed-avatar"]
                                cssPrimitive: "div"
                                Css.CssText {
                                    cssClass: ["feed-avatar-t"]
                                    cssPrimitive: "text"
                                    text: "" + (modelData.who)
                                }
                            }
                            Css.CssRect {
                                cssClass: ["feed-body"]
                                cssPrimitive: "div"
                                Css.CssText {
                                    cssClass: ["feed-name"]
                                    cssPrimitive: "text"
                                    text: "" + (modelData.name)
                                }
                                Css.CssText {
                                    cssClass: ["feed-what"]
                                    cssPrimitive: "text"
                                    text: "" + (modelData.what)
                                }
                            }
                            Css.CssRect {
                                cssClass: ["feed-tag"]
                                cssPrimitive: "div"
                                Css.CssText {
                                    cssClass: ["feed-tag-t"]
                                    cssPrimitive: "text"
                                    text: "" + (modelData.tag)
                                }
                            }
                            Css.CssRect {
                                cssClass: ["feed-alert"]
                                visible: !!(!modelData.ok)
                                cssPrimitive: "div"
                                Css.CssText {
                                    cssClass: ["feed-alert-t"]
                                    cssPrimitive: "text"
                                    text: "!"
                                }
                            }
                            Css.CssText {
                                cssClass: ["feed-when"]
                                cssPrimitive: "text"
                                text: "" + (modelData.when)
                            }
                        }
                    }
                }
            }
        }
        Repeater {
            model: ((page === "analytics") && !((page === "overview"))) ? 1 : 0
            Css.CssRect {
                cssClass: ["dash-page"]
                cssPrimitive: "div"
                Css.CssRect {
                    cssClass: ["panel"]
                    cssPrimitive: "div"
                    Css.CssText {
                        cssClass: ["panel-h"]
                        cssPrimitive: "text"
                        text: "Weekly renders"
                    }
                    Css.CssRect {
                        cssClass: ["chart"]
                        cssPrimitive: "div"
                        Css.CssRect {
                            cssClass: ["bar", "b0"]
                            cssPrimitive: "div"
                        }
                        Css.CssRect {
                            cssClass: ["bar", "b1"]
                            cssPrimitive: "div"
                        }
                        Css.CssRect {
                            cssClass: ["bar", "b2"]
                            cssPrimitive: "div"
                        }
                        Css.CssRect {
                            cssClass: ["bar", "b3"]
                            cssPrimitive: "div"
                        }
                        Css.CssRect {
                            cssClass: ["bar", "b4"]
                            cssPrimitive: "div"
                        }
                        Css.CssRect {
                            cssClass: ["bar", "b5"]
                            cssPrimitive: "div"
                        }
                        Css.CssRect {
                            cssClass: ["bar", "b6"]
                            cssPrimitive: "div"
                        }
                    }
                    Css.CssRect {
                        cssClass: ["chart-x"]
                        cssPrimitive: "div"
                        Css.CssText {
                            cssClass: ["axis"]
                            cssPrimitive: "text"
                            text: "mon"
                        }
                        Css.CssText {
                            cssClass: ["axis"]
                            cssPrimitive: "text"
                            text: "tue"
                        }
                        Css.CssText {
                            cssClass: ["axis"]
                            cssPrimitive: "text"
                            text: "wed"
                        }
                        Css.CssText {
                            cssClass: ["axis"]
                            cssPrimitive: "text"
                            text: "thu"
                        }
                        Css.CssText {
                            cssClass: ["axis"]
                            cssPrimitive: "text"
                            text: "fri"
                        }
                        Css.CssText {
                            cssClass: ["axis"]
                            cssPrimitive: "text"
                            text: "sat"
                        }
                        Css.CssText {
                            cssClass: ["axis"]
                            cssPrimitive: "text"
                            text: "sun"
                        }
                    }
                }
                Css.CssRect {
                    cssClass: ["panel"]
                    cssPrimitive: "div"
                    Css.CssText {
                        cssClass: ["panel-h"]
                        cssPrimitive: "text"
                        text: "Pipeline health"
                    }
                    Repeater {
                        model: __const_PROJECTS
                        Css.CssRect {
                            cssClass: ["prog-row"]
                            cssPrimitive: "div"
                            Css.CssText {
                                cssClass: ["prog-name"]
                                cssPrimitive: "text"
                                text: "" + (modelData.name)
                            }
                            Css.CssRect {
                                cssClass: ["prog-track"]
                                cssPrimitive: "div"
                                Css.CssRect {
                                    cssClass: ["prog-fill"].concat(modelData.pct === "p80" ? ["p80"] : []).concat(modelData.pct === "p65" ? ["p65"] : []).concat(modelData.pct === "p45" ? ["p45"] : []).concat(modelData.pct === "p10" ? ["p10"] : [])
                                    cssPrimitive: "div"
                                }
                            }
                        }
                    }
                }
            }
        }
        Repeater {
            model: ((page === "projects") && !((page === "overview") || (page === "analytics"))) ? 1 : 0
            Css.CssRect {
                cssClass: ["dash-page"]
                cssPrimitive: "div"
                Css.CssRect {
                    cssClass: ["proj-grid"]
                    cssPrimitive: "div"
                    Repeater {
                        model: __const_PROJECTS
                        Css.CssRect {
                            cssClass: ["proj-card"]
                            cssPrimitive: "div"
                            Css.CssRect {
                                cssClass: ["proj-head"]
                                cssPrimitive: "div"
                                Css.CssText {
                                    cssClass: ["proj-name"]
                                    cssPrimitive: "text"
                                    text: "" + (modelData.name)
                                }
                                Css.CssRect {
                                    cssClass: ["proj-pill"].concat(modelData.status === "beta" ? ["beta"] : []).concat(modelData.status === "design" ? ["design"] : [])
                                    cssPrimitive: "div"
                                    Css.CssText {
                                        cssClass: ["proj-pill-t"]
                                        cssPrimitive: "text"
                                        text: "" + (modelData.status)
                                    }
                                }
                            }
                            Css.CssText {
                                cssClass: ["proj-desc"]
                                cssPrimitive: "text"
                                text: "" + (modelData.desc)
                            }
                            Css.CssRect {
                                cssClass: ["prog-track"]
                                cssPrimitive: "div"
                                Css.CssRect {
                                    cssClass: ["prog-fill"].concat(modelData.pct === "p80" ? ["p80"] : []).concat(modelData.pct === "p65" ? ["p65"] : []).concat(modelData.pct === "p45" ? ["p45"] : []).concat(modelData.pct === "p10" ? ["p10"] : [])
                                    cssPrimitive: "div"
                                }
                            }
                        }
                    }
                }
            }
        }
        Repeater {
            model: ((page === "settings") && !((page === "overview") || (page === "analytics") || (page === "projects"))) ? 1 : 0
            Css.CssRect {
                cssClass: ["dash-page"]
                cssPrimitive: "div"
                Css.CssRect {
                    cssClass: ["panel"]
                    cssPrimitive: "div"
                    Css.CssText {
                        cssClass: ["panel-h"]
                        cssPrimitive: "text"
                        text: "Workspace"
                    }
                    Css.CssRect {
                        cssClass: ["set-row"]
                        cssPrimitive: "div"
                        Css.CssText {
                            cssClass: ["set-label"]
                            cssPrimitive: "text"
                            text: "Display name"
                        }
                        Css.CssFill {
                            cssClass: ["set-input"]
                            TextInput {
                                id: __input0
                                anchors.fill: parent
                                anchors.leftMargin: 12
                                anchors.rightMargin: 12
                                verticalAlignment: TextInput.AlignVCenter
                                clip: true
                                selectByMouse: true
                                activeFocusOnTab: true
                                color: parent.style && parent.style["color"] ? cssTheme.parseColor(parent.style["color"]) : "#2b2b2b"
                                font.family: parent.style && parent.style["font-family"] ? cssTheme.resolveFontFamily(parent.style["font-family"], "Sans Serif") : cssTheme.resolveFontFamily("Sans Serif")
                                font.pointSize: parent.style && parent.style["font-size"] ? cssTheme.parseFontSize(parent.style["font-size"], 13) : 13
                                Component.onCompleted: text = ""
                                Text {
                                    anchors.verticalCenter: parent.verticalCenter
                                    anchors.left: parent.left
                                    visible: parent.text.length === 0
                                    text: "ada"
                                    color: "#9aa0a6"
                                    font: parent.font
                                }
                            }
                        }
                    }
                    Css.CssRect {
                        cssClass: ["set-row"]
                        cssPrimitive: "div"
                        Css.CssText {
                            cssClass: ["set-label"]
                            cssPrimitive: "text"
                            text: "Theme"
                        }
                        Css.CssRect {
                            cssClass: ["set-opts"]
                            cssPrimitive: "div"
                            Css.CssFill {
                                cssClass: ["set-opt", "active"]
                                cssState: __hover5.containsMouse ? ["hover"] : []
                                cssPrimitive: "button"
                                Css.CssText {
                                    cssPrimitive: "text"
                                    text: "dark"
                                }
                                MouseArea {
                                    id: __hover5
                                    anchors.fill: parent
                                    hoverEnabled: true
                                    cursorShape: Qt.PointingHandCursor
                                }
                            }
                            Css.CssFill {
                                cssClass: ["set-opt"]
                                cssState: __hover6.containsMouse ? ["hover"] : []
                                cssPrimitive: "button"
                                Css.CssText {
                                    cssPrimitive: "text"
                                    text: "light"
                                }
                                MouseArea {
                                    id: __hover6
                                    anchors.fill: parent
                                    hoverEnabled: true
                                    cursorShape: Qt.PointingHandCursor
                                }
                            }
                            Css.CssFill {
                                cssClass: ["set-opt"]
                                cssState: __hover7.containsMouse ? ["hover"] : []
                                cssPrimitive: "button"
                                Css.CssText {
                                    cssPrimitive: "text"
                                    text: "system"
                                }
                                MouseArea {
                                    id: __hover7
                                    anchors.fill: parent
                                    hoverEnabled: true
                                    cursorShape: Qt.PointingHandCursor
                                }
                            }
                        }
                    }
                    Css.CssRect {
                        cssClass: ["set-row"]
                        cssPrimitive: "div"
                        Css.CssText {
                            cssClass: ["set-label"]
                            cssPrimitive: "text"
                            text: "GPU vsync"
                        }
                        Css.CssFill {
                            cssClass: ["set-opt", "active"]
                            cssState: __hover8.containsMouse ? ["hover"] : []
                            cssPrimitive: "button"
                            Css.CssText {
                                cssPrimitive: "text"
                                text: "on"
                            }
                            MouseArea {
                                id: __hover8
                                anchors.fill: parent
                                hoverEnabled: true
                                cursorShape: Qt.PointingHandCursor
                            }
                        }
                    }
                }
            }
        }
    }
}
