// Generated by the transpiler. Do not edit by hand.
import QtQuick
import "qrc:/qmlcss" as Css

Css.CssRect {
    id: __self
    property var count: 0
    cssClass: ["app"]
    cssPrimitive: "div"
    Css.CssFill {
        cssPrimitive: "button"
        Css.CssText {
            cssPrimitive: "text"
            text: "increment"
        }
        MouseArea {
            anchors.fill: parent
            cursorShape: Qt.PointingHandCursor
            onClicked: count = count + 1
        }
    }
    Css.CssText {
        cssPrimitive: "text"
        text: "" + (count) + " doubled is " + ((count * 2))
    }
}
