// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var count: 0
    cssClass: ["app"]
    W.Button {
        text: "increment"
        onClicked: count = count + 1
    }
    W.Text {
        text: "" + (count) + " doubled is " + ((count * 2))
    }
}
