// Generated by the transpiler. Do not edit by hand.
import QtQuick
import "qrc:/qmlcss" as Css

Css.CssText {
    id: __self
    property var __ctx_CounterContext
    cssPrimitive: "text"
    text: "Count: " + (__ctx_CounterContext.count)
}
