// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Text {
    id: __self
    property var __ctx_CounterContext
    text: "Count: " + (__ctx_CounterContext.count)
}
