// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
Css.CssRect {
    id: __self
    property var tag: "h1"
    cssClass: ["app"]
    cssPrimitive: "div"
    W.Button {
        text: "render as: <" + (tag) + ">"
        onClicked: tag = tag === "h1" ? "bio" : "h1"
    }
    Css.CssText {
        cssPrimitive: tag
        text: "Polymorphic element"
    }
}
