// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W

import QtQuick.Templates 6.0 as T
W.Div {
    id: __self
    property var lo: 20
    property var hi: 80
    property var angle: 30
    property var size: "M"
    property var armed: false
    property var busy: true
    property var clicks: 0
    cssClass: ["nv-section"]
    W.Text {
        cssClass: ["nv-title"]
        text: "Extra inputs"
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "range " + (lo) + "–" + (hi)
        }
        Css.CssFill {
            cssClass: ["ni-range"]
            cssPrimitive: "input"
            cssState: (__input0.activeFocus ? ["focus"] : []).concat(!__input0.enabled ? ["disabled"] : [])
            implicitWidth: __input0.implicitWidth
            implicitHeight: __input0.implicitHeight
            T.RangeSlider {
                id: __input0
                anchors.fill: parent
                activeFocusOnTab: solidTabstop.enabled
                from: 0
                to: 100
                stepSize: 1
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, first.implicitHandleWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, first.implicitHandleHeight + topPadding + bottomPadding)
                background: Css.CssFill {
                    cssPrimitive: ""
                    cssClass: ["track"]
                    x: __input0.leftPadding
                    y: __input0.topPadding + (__input0.availableHeight - height) / 2
                    width: __input0.availableWidth
                    height: 6
                    implicitWidth: 200
                    implicitHeight: 6
                    Item {
                        anchors.fill: parent
                        Css.CssRect {
                            cssClass: ["track-fill"]
                            x: __input0.first.visualPosition * parent.width
                            width: (__input0.second.visualPosition - __input0.first.visualPosition) * parent.width
                            height: parent.height
                        }
                    }
                }
                first.handle: Css.CssRect {
                    cssClass: ["handle"]
                    width: 18
                    height: 18
                    implicitWidth: 18
                    implicitHeight: 18
                    x: __input0.leftPadding + __input0.first.visualPosition * (__input0.availableWidth - width)
                    y: __input0.topPadding + __input0.availableHeight / 2 - height / 2
                }
                second.handle: Css.CssRect {
                    cssClass: ["handle"]
                    width: 18
                    height: 18
                    implicitWidth: 18
                    implicitHeight: 18
                    x: __input0.leftPadding + __input0.second.visualPosition * (__input0.availableWidth - width)
                    y: __input0.topPadding + __input0.availableHeight / 2 - height / 2
                }
                WheelHandler {
                    property real __acc: 0
                    enabled: __input0.activeFocus
                    acceptedDevices: PointerDevice.Mouse | PointerDevice.TouchPad
                    onWheel: (ev) => { __acc += ev.angleDelta.y !== 0 ? ev.angleDelta.y : ev.pixelDelta.y * 8; var s = 0; while (__acc >= 120) { __acc -= 120; s++ } while (__acc <= -120) { __acc += 120; s-- } if (s !== 0) { __input0.first.value = Math.max(__input0.from, Math.min(__input0.to, __input0.first.value + s * __input0.stepSize)); __input0.first.moved() } }
                }
                first.onMoved: { __self.lo = __input0.first.value; __self.hi = __input0.second.value; }
                second.onMoved: { __self.lo = __input0.first.value; __self.hi = __input0.second.value; }
            }
            Binding {
                target: __input0.first
                property: "value"
                value: lo
                restoreMode: Binding.RestoreNone
            }
            Binding {
                target: __input0.second
                property: "value"
                value: hi
                restoreMode: Binding.RestoreNone
            }
        }
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "dial " + (angle)
        }
        W.Dial {
            id: __input1
            cssClass: ["ni-dial"]
            from: 0
            to: 100
            stepSize: 5
            onMoved: { __self.angle = __input1.value }
            Binding {
                target: __input1
                property: "value"
                value: angle
                restoreMode: Binding.RestoreNone
            }
        }
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "size " + (size)
        }
        Css.CssFill {
            cssClass: ["ni-tumbler"]
            cssPrimitive: ""
            cssState: (__input2.activeFocus ? ["focus"] : []).concat(!__input2.enabled ? ["disabled"] : [])
            implicitWidth: __input2.implicitWidth
            implicitHeight: __input2.implicitHeight
            T.Tumbler {
                id: __input2
                anchors.fill: parent
                activeFocusOnTab: solidTabstop.enabled
                model: ["S", "M", "L", "XL"]
                wrap: false
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
                delegate: Item {
                    width: __input2.availableWidth
                    height: __input2.availableHeight / __input2.visibleItemCount
                    property real __disp: T.Tumbler.displacement
                    Css.CssText {
                        cssPrimitive: ""
                        cssClass: ["item"]
                        cssState: Math.abs(__disp) < 0.5 ? ["selected"] : []
                        text: modelData
                        anchors.centerIn: parent
                    }
                }
                contentItem: ListView {
                    implicitWidth: 60
                    implicitHeight: 180
                    model: __input2.model
                    delegate: __input2.delegate
                    snapMode: ListView.SnapToItem
                    highlightRangeMode: ListView.StrictlyEnforceRange
                    preferredHighlightBegin: height / 2 - height / __input2.visibleItemCount / 2
                    preferredHighlightEnd: height / 2 + height / __input2.visibleItemCount / 2
                    clip: true
                }
                onCurrentIndexChanged: { __self.size = __input2.model[__input2.currentIndex] }
            }
            Binding {
                target: __input2
                property: "currentIndex"
                value: (["S", "M", "L", "XL"]).indexOf(size)
                restoreMode: Binding.RestoreNone
            }
        }
    }
    W.Div {
        cssClass: ["nv-row"]
        W.DelayButton {
            cssClass: ["ni-delay"]
            delay: 1200
            text: "Hold to arm"
            onActivated: { __self.armed = true }
        }
        W.Text {
            cssClass: ["nv-label"]
            text: "" + (armed ? "armed!" : "idle")
        }
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Button {
            cssClass: ["ni-btn"]
            text: "" + (busy ? "stop" : "start")
            onClicked: busy = !busy
        }
        W.BusyIndicator {
            cssClass: ["ni-busy"]
            running: busy
        }
    }
    W.Div {
        cssClass: ["nv-row"]
        W.RoundButton {
            cssClass: ["ni-round", "round"]
            text: "+1"
            onClicked: { __self.clicks = clicks + 1 }
        }
        W.ToolSeparator {
            cssClass: ["ni-sep"]
        }
        W.ToolButton {
            cssClass: ["ni-tool", "tool"]
            text: "reset"
            onClicked: { __self.clicks = 0 }
        }
        W.Text {
            cssClass: ["nv-label"]
            text: "clicks " + (clicks)
        }
    }
}
