// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import QtQuick.Templates 6.0 as T
Css.CssRect {
    id: __self
    property var lo: 20
    property var hi: 80
    property var angle: 30
    property var size: "M"
    property var armed: false
    property var busy: true
    property var clicks: 0
    cssClass: ["nv-section"]
    cssPrimitive: "div"
    Css.CssText {
        cssClass: ["nv-title"]
        cssPrimitive: "text"
        text: "Extra inputs"
    }
    Css.CssRect {
        cssClass: ["nv-row"]
        cssPrimitive: "div"
        Css.CssText {
            cssClass: ["nv-label"]
            cssPrimitive: "text"
            text: "range " + (lo) + "–" + (hi)
        }
        Css.CssFill {
            cssClass: ["ni-range"]
            cssPrimitive: "input"
            cssState: (__input0.activeFocus ? ["focus"] : []).concat(!__input0.enabled ? ["disabled"] : [])
            implicitWidth: __input0.implicitWidth
            implicitHeight: __input0.implicitHeight
            T.RangeSlider {
                id: __input0
                anchors.fill: parent
                activeFocusOnTab: solidTabstop.enabled
                from: 0
                to: 100
                stepSize: 1
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, first.implicitHandleWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, first.implicitHandleHeight + topPadding + bottomPadding)
                background: Css.CssFill {
                    cssPrimitive: ""
                    cssClass: ["track"]
                    x: __input0.leftPadding
                    y: __input0.topPadding + (__input0.availableHeight - height) / 2
                    width: __input0.availableWidth
                    height: 6
                    implicitWidth: 200
                    implicitHeight: 6
                    Item {
                        anchors.fill: parent
                        Css.CssRect {
                            cssClass: ["track-fill"]
                            x: __input0.first.visualPosition * parent.width
                            width: (__input0.second.visualPosition - __input0.first.visualPosition) * parent.width
                            height: parent.height
                        }
                    }
                }
                first.handle: Css.CssRect {
                    cssClass: ["handle"]
                    width: 18
                    height: 18
                    implicitWidth: 18
                    implicitHeight: 18
                    x: __input0.leftPadding + __input0.first.visualPosition * (__input0.availableWidth - width)
                    y: __input0.topPadding + __input0.availableHeight / 2 - height / 2
                }
                second.handle: Css.CssRect {
                    cssClass: ["handle"]
                    width: 18
                    height: 18
                    implicitWidth: 18
                    implicitHeight: 18
                    x: __input0.leftPadding + __input0.second.visualPosition * (__input0.availableWidth - width)
                    y: __input0.topPadding + __input0.availableHeight / 2 - height / 2
                }
                WheelHandler {
                    property real __acc: 0
                    enabled: __input0.activeFocus
                    acceptedDevices: PointerDevice.Mouse | PointerDevice.TouchPad
                    onWheel: (ev) => { __acc += ev.angleDelta.y !== 0 ? ev.angleDelta.y : ev.pixelDelta.y * 8; var s = 0; while (__acc >= 120) { __acc -= 120; s++ } while (__acc <= -120) { __acc += 120; s-- } if (s !== 0) { __input0.first.value = Math.max(__input0.from, Math.min(__input0.to, __input0.first.value + s * __input0.stepSize)); __input0.first.moved() } }
                }
                first.onMoved: { __self.lo = __input0.first.value; __self.hi = __input0.second.value; }
                second.onMoved: { __self.lo = __input0.first.value; __self.hi = __input0.second.value; }
            }
            Binding {
                target: __input0.first
                property: "value"
                value: lo
                restoreMode: Binding.RestoreNone
            }
            Binding {
                target: __input0.second
                property: "value"
                value: hi
                restoreMode: Binding.RestoreNone
            }
        }
    }
    Css.CssRect {
        cssClass: ["nv-row"]
        cssPrimitive: "div"
        Css.CssText {
            cssClass: ["nv-label"]
            cssPrimitive: "text"
            text: "dial " + (angle)
        }
        Css.CssFill {
            cssClass: ["ni-dial"]
            cssPrimitive: ""
            cssState: (__input1.activeFocus ? ["focus"] : []).concat(__input1.pressed ? ["active"] : []).concat(!__input1.enabled ? ["disabled"] : [])
            implicitWidth: __input1.implicitWidth
            implicitHeight: __input1.implicitHeight
            T.Dial {
                id: __input1
                anchors.fill: parent
                activeFocusOnTab: solidTabstop.enabled
                from: 0
                to: 100
                stepSize: 5
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
                background: Css.CssFill {
                    cssPrimitive: ""
                    cssClass: ["dial"]
                    x: __input1.width / 2 - width / 2
                    y: __input1.height / 2 - height / 2
                    width: Math.max(32, Math.min(__input1.width, __input1.height))
                    height: width
                    implicitWidth: 96
                    implicitHeight: 96
                }
                handle: Css.CssRect {
                    cssClass: ["handle"]
                    width: 12
                    height: 12
                    implicitWidth: 12
                    implicitHeight: 12
                    x: __input1.background.x + __input1.background.width / 2 - width / 2 + Math.sin(__input1.angle * Math.PI / 180) * (__input1.background.width / 2 - 12)
                    y: __input1.background.y + __input1.background.height / 2 - height / 2 - Math.cos(__input1.angle * Math.PI / 180) * (__input1.background.width / 2 - 12)
                }
                onMoved: { __self.angle = __input1.value }
            }
            Binding {
                target: __input1
                property: "value"
                value: angle
                restoreMode: Binding.RestoreNone
            }
        }
    }
    Css.CssRect {
        cssClass: ["nv-row"]
        cssPrimitive: "div"
        Css.CssText {
            cssClass: ["nv-label"]
            cssPrimitive: "text"
            text: "size " + (size)
        }
        Css.CssFill {
            cssClass: ["ni-tumbler"]
            cssPrimitive: ""
            cssState: (__input2.activeFocus ? ["focus"] : []).concat(!__input2.enabled ? ["disabled"] : [])
            implicitWidth: __input2.implicitWidth
            implicitHeight: __input2.implicitHeight
            T.Tumbler {
                id: __input2
                anchors.fill: parent
                activeFocusOnTab: solidTabstop.enabled
                model: ["S", "M", "L", "XL"]
                wrap: false
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
                delegate: Item {
                    width: __input2.availableWidth
                    height: __input2.availableHeight / __input2.visibleItemCount
                    property real __disp: T.Tumbler.displacement
                    Css.CssText {
                        cssPrimitive: ""
                        cssClass: ["item"]
                        cssState: Math.abs(__disp) < 0.5 ? ["selected"] : []
                        text: modelData
                        anchors.centerIn: parent
                    }
                }
                contentItem: ListView {
                    implicitWidth: 60
                    implicitHeight: 180
                    model: __input2.model
                    delegate: __input2.delegate
                    snapMode: ListView.SnapToItem
                    highlightRangeMode: ListView.StrictlyEnforceRange
                    preferredHighlightBegin: height / 2 - height / __input2.visibleItemCount / 2
                    preferredHighlightEnd: height / 2 + height / __input2.visibleItemCount / 2
                    clip: true
                }
                onCurrentIndexChanged: { __self.size = __input2.model[__input2.currentIndex] }
            }
            Binding {
                target: __input2
                property: "currentIndex"
                value: (["S", "M", "L", "XL"]).indexOf(size)
                restoreMode: Binding.RestoreNone
            }
        }
    }
    Css.CssRect {
        cssClass: ["nv-row"]
        cssPrimitive: "div"
        Css.CssFill {
            cssClass: ["ni-delay"]
            cssPrimitive: ""
            cssState: (__input3.hovered ? ["hover"] : []).concat(__input3.pressed ? ["active"] : []).concat(__input3.checked ? ["checked"] : []).concat(__input3.activeFocus ? ["focus"] : []).concat(!__input3.enabled ? ["disabled"] : [])
            implicitWidth: __input3.implicitWidth
            implicitHeight: __input3.implicitHeight
            T.DelayButton {
                id: __input3
                anchors.fill: parent
                activeFocusOnTab: solidTabstop.enabled
                hoverEnabled: true
                delay: 1200
                horizontalPadding: 16
                verticalPadding: 8
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
                background: Css.CssFill {
                    cssPrimitive: ""
                    cssClass: ["delay"]
                    cssState: (__input3.hovered ? ["hover"] : []).concat(__input3.pressed ? ["active"] : []).concat(__input3.checked ? ["checked"] : []).concat(__input3.activeFocus ? ["focus"] : []).concat(!__input3.enabled ? ["disabled"] : [])
                    implicitWidth: 120
                    implicitHeight: 36
                    Item {
                        anchors.fill: parent
                        Css.CssRect {
                            cssClass: ["delay-fill"]
                            width: __input3.progress * parent.width
                            height: parent.height
                        }
                    }
                }
                contentItem: Css.CssText {
                    cssPrimitive: "text"
                    text: "Hold to arm"
                }
                onActivated: { __self.armed = true }
            }
        }
        Css.CssText {
            cssClass: ["nv-label"]
            cssPrimitive: "text"
            text: "" + (armed ? "armed!" : "idle")
        }
    }
    Css.CssRect {
        cssClass: ["nv-row"]
        cssPrimitive: "div"
        Css.CssFill {
            cssClass: ["ni-btn"]
            cssState: __hover0.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "" + (busy ? "stop" : "start")
            }
            MouseArea {
                id: __hover0
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: busy = !busy
            }
        }
        Css.CssFill {
            cssClass: ["ni-busy"]
            cssPrimitive: ""
            implicitWidth: __input4.implicitWidth
            implicitHeight: __input4.implicitHeight
            T.BusyIndicator {
                id: __input4
                anchors.fill: parent
                running: busy
                visible: running
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
                contentItem: Item {
                    implicitWidth: 40
                    implicitHeight: 40
                    property real __r: Math.min(width, height) / 2 - 5
                    RotationAnimation on rotation {
                        from: 0
                        to: 360
                        duration: 900
                        loops: Animation.Infinite
                        running: busy
                    }
                    Rectangle {
                        width: 6
                        height: 6
                        radius: 3
                        color: "#176b87"
                        opacity: 0.125
                        x: parent.width / 2 + Math.cos(0 * Math.PI / 4) * parent.__r - width / 2
                        y: parent.height / 2 + Math.sin(0 * Math.PI / 4) * parent.__r - height / 2
                        Css.CssItem { cssPrimitive: "rect"; cssClass: ["spoke"] }
                    }
                    Rectangle {
                        width: 6
                        height: 6
                        radius: 3
                        color: "#176b87"
                        opacity: 0.25
                        x: parent.width / 2 + Math.cos(1 * Math.PI / 4) * parent.__r - width / 2
                        y: parent.height / 2 + Math.sin(1 * Math.PI / 4) * parent.__r - height / 2
                        Css.CssItem { cssPrimitive: "rect"; cssClass: ["spoke"] }
                    }
                    Rectangle {
                        width: 6
                        height: 6
                        radius: 3
                        color: "#176b87"
                        opacity: 0.375
                        x: parent.width / 2 + Math.cos(2 * Math.PI / 4) * parent.__r - width / 2
                        y: parent.height / 2 + Math.sin(2 * Math.PI / 4) * parent.__r - height / 2
                        Css.CssItem { cssPrimitive: "rect"; cssClass: ["spoke"] }
                    }
                    Rectangle {
                        width: 6
                        height: 6
                        radius: 3
                        color: "#176b87"
                        opacity: 0.5
                        x: parent.width / 2 + Math.cos(3 * Math.PI / 4) * parent.__r - width / 2
                        y: parent.height / 2 + Math.sin(3 * Math.PI / 4) * parent.__r - height / 2
                        Css.CssItem { cssPrimitive: "rect"; cssClass: ["spoke"] }
                    }
                    Rectangle {
                        width: 6
                        height: 6
                        radius: 3
                        color: "#176b87"
                        opacity: 0.625
                        x: parent.width / 2 + Math.cos(4 * Math.PI / 4) * parent.__r - width / 2
                        y: parent.height / 2 + Math.sin(4 * Math.PI / 4) * parent.__r - height / 2
                        Css.CssItem { cssPrimitive: "rect"; cssClass: ["spoke"] }
                    }
                    Rectangle {
                        width: 6
                        height: 6
                        radius: 3
                        color: "#176b87"
                        opacity: 0.75
                        x: parent.width / 2 + Math.cos(5 * Math.PI / 4) * parent.__r - width / 2
                        y: parent.height / 2 + Math.sin(5 * Math.PI / 4) * parent.__r - height / 2
                        Css.CssItem { cssPrimitive: "rect"; cssClass: ["spoke"] }
                    }
                    Rectangle {
                        width: 6
                        height: 6
                        radius: 3
                        color: "#176b87"
                        opacity: 0.875
                        x: parent.width / 2 + Math.cos(6 * Math.PI / 4) * parent.__r - width / 2
                        y: parent.height / 2 + Math.sin(6 * Math.PI / 4) * parent.__r - height / 2
                        Css.CssItem { cssPrimitive: "rect"; cssClass: ["spoke"] }
                    }
                    Rectangle {
                        width: 6
                        height: 6
                        radius: 3
                        color: "#176b87"
                        opacity: 1
                        x: parent.width / 2 + Math.cos(7 * Math.PI / 4) * parent.__r - width / 2
                        y: parent.height / 2 + Math.sin(7 * Math.PI / 4) * parent.__r - height / 2
                        Css.CssItem { cssPrimitive: "rect"; cssClass: ["spoke"] }
                    }
                }
            }
        }
    }
    Css.CssRect {
        cssClass: ["nv-row"]
        cssPrimitive: "div"
        Css.CssFill {
            cssClass: ["ni-round", "round"]
            cssPrimitive: "button"
            cssState: (__input5.hovered ? ["hover"] : []).concat(__input5.pressed ? ["active"] : []).concat(__input5.activeFocus ? ["focus"] : []).concat(!__input5.enabled ? ["disabled"] : [])
            Css.CssText {
                cssPrimitive: "text"
                text: "+1"
            }
            T.RoundButton {
                id: __input5
                anchors.fill: parent
                activeFocusOnTab: solidTabstop.enabled
                hoverEnabled: true
                background: null
                contentItem: null
                onClicked: { __self.clicks = clicks + 1 }
            }
        }
        Css.CssFill {
            cssClass: ["ni-sep"]
            cssPrimitive: ""
            implicitWidth: __input6.implicitWidth
            implicitHeight: __input6.implicitHeight
            T.ToolSeparator {
                id: __input6
                anchors.fill: parent
                background: null
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
                contentItem: Item {
                    implicitWidth: 9
                    implicitHeight: 28
                    Css.CssRect {
                        cssClass: ["sep"]
                        anchors.horizontalCenter: parent.horizontalCenter
                        anchors.verticalCenter: parent.verticalCenter
                        width: 1
                        height: parent.height * 0.6
                    }
                }
            }
        }
        Css.CssFill {
            cssClass: ["ni-tool", "tool"]
            cssPrimitive: "button"
            cssState: (__input7.hovered ? ["hover"] : []).concat(__input7.pressed ? ["active"] : []).concat(__input7.activeFocus ? ["focus"] : []).concat(!__input7.enabled ? ["disabled"] : [])
            Css.CssText {
                cssPrimitive: "text"
                text: "reset"
            }
            T.ToolButton {
                id: __input7
                anchors.fill: parent
                activeFocusOnTab: solidTabstop.enabled
                hoverEnabled: true
                background: null
                contentItem: null
                onClicked: { __self.clicks = 0 }
            }
        }
        Css.CssText {
            cssClass: ["nv-label"]
            cssPrimitive: "text"
            text: "clicks " + (clicks)
        }
    }
}
