// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var login: "solidjs"
    property var user
    property bool user_loading: true
    property var user_error
    property var __load_user
    property var __cleanups: []
    Component.onCompleted: { function _await(value, then, direct) { if (direct) { return then ? then(value) : value; } if (!value || !value.then) { value = Promise.resolve(value); } return then ? value.then(then) : value; } const fetchUser = _async(function (login) { return _await(fetch(`https://api.github.com/users/${login}`), function (_fetch) { return _fetch.json(); }); }); function _async(f) { return function () { for (var args = [], i = 0; i < arguments.length; i++) { args[i] = arguments[i]; } try { return Promise.resolve(f.apply(this, args)); } catch (e) { return Promise.reject(e); } }; } __load_user = function() { user_loading = true; user_error = undefined; Promise.resolve(fetchUser(login)).then(function(v) { user = v; user_loading = false; }).catch(function(e) { user_error = e; user_loading = false; }); }; __load_user(); }
    Component.onDestruction: { for (var i = 0; i < __cleanups.length; i++) __cleanups[i](); }
    Connections {
        target: __self
        function onLoginChanged() { __load_user(); }
    }
    cssClass: ["fetch-app"]
    W.Text {
        cssClass: ["fetch-h1"]
        text: "github"
    }
    W.TextField {
        id: __input0
        cssClass: ["fetch-search"]
        placeholder: "GitHub login"
        onTextEdited: { login = text }
        Binding {
            target: __input0
            property: "text"
            value: login
            restoreMode: Binding.RestoreNone
        }
    }
    W.Div {
        cssClass: ["fetch-card"]
        visible: !!((!(user_loading)) && (user))
        W.Image {
            cssClass: ["fetch-avatar"]
            src: (user || ({})).avatar_url || ""
        }
        W.Text {
            cssClass: ["fetch-name"]
            text: "" + ((user || ({})).name)
        }
        W.Text {
            cssClass: ["fetch-bio"]
            text: "" + ((user || ({})).bio)
        }
        W.Text {
            cssClass: ["fetch-repos"]
            text: "" + ((user || ({})).public_repos) + " public repos"
        }
    }
    W.Text {
        visible: (!(user_loading)) && !(user)
        cssClass: ["fetch-empty"]
        text: "no such user"
    }
    W.Text {
        visible: !(!(user_loading))
        cssClass: ["fetch-loading"]
        text: "loading…"
    }
}
