// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
Css.CssRect {
    id: __self
    property var view: "hello"
    cssClass: ["gallery"]
    cssPrimitive: "div"
    Css.CssRect {
        cssClass: ["hero-bg"]
        visible: !!(view === "hello")
        cssPrimitive: "div"
    }
    Css.CssRect {
        cssClass: ["nav"]
        cssPrimitive: "div"
        W.Button {
            cssClass: [].concat(view === "hello" ? ["active"] : [])
            text: "Hello"
            onClicked: view = "hello"
        }
        W.Button {
            cssClass: [].concat(view === "counters" ? ["active"] : [])
            text: "Counters"
            onClicked: view = "counters"
        }
        W.Button {
            cssClass: [].concat(view === "counter" ? ["active"] : [])
            text: "Counter (timer)"
            onClicked: view = "counter"
        }
        W.Button {
            cssClass: [].concat(view === "children" ? ["active"] : [])
            text: "props.children"
            onClicked: view = "children"
        }
        W.Button {
            cssClass: [].concat(view === "derived" ? ["active"] : [])
            text: "Derived"
            onClicked: view = "derived"
        }
        W.Button {
            cssClass: [].concat(view === "index" ? ["active"] : [])
            text: "Index"
            onClicked: view = "index"
        }
        W.Button {
            cssClass: [].concat(view === "dynamic" ? ["active"] : [])
            text: "Dynamic"
            onClicked: view = "dynamic"
        }
        W.Button {
            cssClass: [].concat(view === "props" ? ["active"] : [])
            text: "Prop helpers"
            onClicked: view = "props"
        }
        W.Button {
            cssClass: [].concat(view === "context" ? ["active"] : [])
            text: "Context"
            onClicked: view = "context"
        }
        W.Button {
            cssClass: [].concat(view === "refs" ? ["active"] : [])
            text: "Refs"
            onClicked: view = "refs"
        }
        W.Button {
            cssClass: [].concat(view === "fetch" ? ["active"] : [])
            text: "Fetch"
            onClicked: view = "fetch"
        }
        W.Button {
            cssClass: [].concat(view === "todomvc" ? ["active"] : [])
            text: "TodoMVC"
            onClicked: view = "todomvc"
        }
        W.Button {
            cssClass: [].concat(view === "nodeimports" ? ["active"] : [])
            text: "Node imports"
            onClicked: view = "nodeimports"
        }
        W.Button {
            cssClass: [].concat(view === "cssgaps" ? ["active"] : [])
            text: "CSS gaps"
            onClicked: view = "cssgaps"
        }
        W.Button {
            cssClass: [].concat(view === "dashboard" ? ["active"] : [])
            text: "Dashboard"
            onClicked: view = "dashboard"
        }
        W.Button {
            cssClass: [].concat(view === "widgets" ? ["active"] : [])
            text: "Widgets"
            onClicked: view = "widgets"
        }
        W.Button {
            cssClass: [].concat(view === "native" ? ["active"] : [])
            text: "Native"
            onClicked: view = "native"
        }
    }
    Css.CssIncubator {
        active: (view === "hello") ? true : false
        sourceComponent: Component {
            Hello {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "counters") && !((view === "hello"))) ? true : false
        sourceComponent: Component {
            Counters {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "counter") && !((view === "hello") || (view === "counters"))) ? true : false
        sourceComponent: Component {
            TimerCounter {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "children") && !((view === "hello") || (view === "counters") || (view === "counter"))) ? true : false
        sourceComponent: Component {
            Children {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "derived") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children"))) ? true : false
        sourceComponent: Component {
            Derived {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "index") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived"))) ? true : false
        sourceComponent: Component {
            IndexList {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "dynamic") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index"))) ? true : false
        sourceComponent: Component {
            DynamicTag {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "props") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic"))) ? true : false
        sourceComponent: Component {
            PropHelpers {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "context") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props"))) ? true : false
        sourceComponent: Component {
            ContextDemo {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "refs") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context"))) ? true : false
        sourceComponent: Component {
            Refs {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "fetch") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs"))) ? true : false
        sourceComponent: Component {
            Fetch {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "todomvc") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs") || (view === "fetch"))) ? true : false
        sourceComponent: Component {
            TodoMVC {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "nodeimports") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs") || (view === "fetch") || (view === "todomvc"))) ? true : false
        sourceComponent: Component {
            NodeImports {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "cssgaps") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs") || (view === "fetch") || (view === "todomvc") || (view === "nodeimports"))) ? true : false
        sourceComponent: Component {
            CssGaps {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "dashboard") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs") || (view === "fetch") || (view === "todomvc") || (view === "nodeimports") || (view === "cssgaps"))) ? true : false
        sourceComponent: Component {
            Dashboard {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "widgets") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs") || (view === "fetch") || (view === "todomvc") || (view === "nodeimports") || (view === "cssgaps") || (view === "dashboard"))) ? true : false
        sourceComponent: Component {
            Widgets {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "native") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs") || (view === "fetch") || (view === "todomvc") || (view === "nodeimports") || (view === "cssgaps") || (view === "dashboard") || (view === "widgets"))) ? true : false
        sourceComponent: Component {
            NativeOnly {
            }
        }
    }
}
