// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    property var view: "hello"
    cssClass: ["gallery"]
    cssPrimitive: "div"
    Css.CssRect {
        cssClass: ["hero-bg"]
        visible: !!(view === "hello")
        cssPrimitive: "div"
    }
    Css.CssRect {
        cssClass: ["nav"]
        cssPrimitive: "div"
        Css.CssFill {
            cssClass: [].concat(view === "hello" ? ["active"] : [])
            cssState: __hover0.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Hello"
            }
            MouseArea {
                id: __hover0
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "hello"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "counters" ? ["active"] : [])
            cssState: __hover1.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Counters"
            }
            MouseArea {
                id: __hover1
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "counters"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "counter" ? ["active"] : [])
            cssState: __hover2.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Counter (timer)"
            }
            MouseArea {
                id: __hover2
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "counter"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "children" ? ["active"] : [])
            cssState: __hover3.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "props.children"
            }
            MouseArea {
                id: __hover3
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "children"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "derived" ? ["active"] : [])
            cssState: __hover4.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Derived"
            }
            MouseArea {
                id: __hover4
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "derived"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "index" ? ["active"] : [])
            cssState: __hover5.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Index"
            }
            MouseArea {
                id: __hover5
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "index"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "dynamic" ? ["active"] : [])
            cssState: __hover6.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Dynamic"
            }
            MouseArea {
                id: __hover6
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "dynamic"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "props" ? ["active"] : [])
            cssState: __hover7.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Prop helpers"
            }
            MouseArea {
                id: __hover7
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "props"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "context" ? ["active"] : [])
            cssState: __hover8.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Context"
            }
            MouseArea {
                id: __hover8
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "context"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "refs" ? ["active"] : [])
            cssState: __hover9.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Refs"
            }
            MouseArea {
                id: __hover9
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "refs"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "fetch" ? ["active"] : [])
            cssState: __hover10.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Fetch"
            }
            MouseArea {
                id: __hover10
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "fetch"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "todomvc" ? ["active"] : [])
            cssState: __hover11.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "TodoMVC"
            }
            MouseArea {
                id: __hover11
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "todomvc"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "nodeimports" ? ["active"] : [])
            cssState: __hover12.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Node imports"
            }
            MouseArea {
                id: __hover12
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "nodeimports"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "cssgaps" ? ["active"] : [])
            cssState: __hover13.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "CSS gaps"
            }
            MouseArea {
                id: __hover13
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "cssgaps"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "dashboard" ? ["active"] : [])
            cssState: __hover14.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Dashboard"
            }
            MouseArea {
                id: __hover14
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "dashboard"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "widgets" ? ["active"] : [])
            cssState: __hover15.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Widgets"
            }
            MouseArea {
                id: __hover15
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "widgets"
            }
        }
        Css.CssFill {
            cssClass: [].concat(view === "native" ? ["active"] : [])
            cssState: __hover16.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Native"
            }
            MouseArea {
                id: __hover16
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: view = "native"
            }
        }
    }
    Css.CssIncubator {
        active: (view === "hello") ? true : false
        sourceComponent: Component {
            Hello {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "counters") && !((view === "hello"))) ? true : false
        sourceComponent: Component {
            Counters {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "counter") && !((view === "hello") || (view === "counters"))) ? true : false
        sourceComponent: Component {
            TimerCounter {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "children") && !((view === "hello") || (view === "counters") || (view === "counter"))) ? true : false
        sourceComponent: Component {
            Children {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "derived") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children"))) ? true : false
        sourceComponent: Component {
            Derived {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "index") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived"))) ? true : false
        sourceComponent: Component {
            IndexList {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "dynamic") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index"))) ? true : false
        sourceComponent: Component {
            DynamicTag {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "props") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic"))) ? true : false
        sourceComponent: Component {
            PropHelpers {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "context") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props"))) ? true : false
        sourceComponent: Component {
            ContextDemo {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "refs") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context"))) ? true : false
        sourceComponent: Component {
            Refs {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "fetch") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs"))) ? true : false
        sourceComponent: Component {
            Fetch {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "todomvc") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs") || (view === "fetch"))) ? true : false
        sourceComponent: Component {
            TodoMVC {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "nodeimports") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs") || (view === "fetch") || (view === "todomvc"))) ? true : false
        sourceComponent: Component {
            NodeImports {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "cssgaps") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs") || (view === "fetch") || (view === "todomvc") || (view === "nodeimports"))) ? true : false
        sourceComponent: Component {
            CssGaps {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "dashboard") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs") || (view === "fetch") || (view === "todomvc") || (view === "nodeimports") || (view === "cssgaps"))) ? true : false
        sourceComponent: Component {
            Dashboard {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "widgets") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs") || (view === "fetch") || (view === "todomvc") || (view === "nodeimports") || (view === "cssgaps") || (view === "dashboard"))) ? true : false
        sourceComponent: Component {
            Widgets {
            }
        }
    }
    Css.CssIncubator {
        active: ((view === "native") && !((view === "hello") || (view === "counters") || (view === "counter") || (view === "children") || (view === "derived") || (view === "index") || (view === "dynamic") || (view === "props") || (view === "context") || (view === "refs") || (view === "fetch") || (view === "todomvc") || (view === "nodeimports") || (view === "cssgaps") || (view === "dashboard") || (view === "widgets"))) ? true : false
        sourceComponent: Component {
            NativeOnly {
            }
        }
    }
}
