// Generated by the transpiler. Do not edit by hand.
import QtQuick
import "qrc:/qmlcss" as Css

Css.CssRect {
    id: __self
    property var events: 0
    cssClass: ["hello-stage"]
    cssPrimitive: "div"
    Css.CssRect {
        cssClass: ["hello-panel"]
        cssPrimitive: "div"
        Css.CssRect {
            cssClass: ["hello-mark"]
            cssPrimitive: "div"
            Css.CssRect {
                cssClass: ["hello-orbit"]
                cssPrimitive: "div"
                Css.CssRect {
                    cssClass: ["hello-spark", "hello-spark-a"]
                    cssPrimitive: "div"
                }
                Css.CssRect {
                    cssClass: ["hello-spark", "hello-spark-b"]
                    cssPrimitive: "div"
                }
                Css.CssRect {
                    cssClass: ["hello-spark", "hello-spark-c"]
                    cssPrimitive: "div"
                }
            }
            Css.CssRect {
                cssClass: ["hello-core"]
                cssPrimitive: "div"
                Css.CssText {
                    cssPrimitive: ""
                    text: "Q"
                }
            }
        }
        Css.CssRect {
            cssClass: ["hello-content"]
            cssPrimitive: "div"
            Css.CssText {
                cssClass: ["hello-eyebrow"]
                cssPrimitive: "text"
                text: "solid qml native"
            }
            Css.CssText {
                cssClass: ["hello-headline"]
                cssPrimitive: "text"
                text: "welcome to solid qml"
            }
            Css.CssText {
                cssClass: ["hello-copy"]
                cssPrimitive: "text"
                text: "A hello world in Solid.js — and the very same code already renders natively through QML."
            }
            Css.CssFill {
                cssClass: ["hello-cta"]
                cssPrimitive: "button"
                Css.CssText {
                    cssPrimitive: "text"
                    text: ""
                }
                Css.CssText {
                    cssClass: ["hello-cta-label"]
                    cssPrimitive: "span"
                    text: "count events"
                }
                Css.CssRect {
                    cssClass: ["hello-badge"]
                    cssPrimitive: "div"
                    Css.CssText {
                        cssPrimitive: ""
                        text: "" + (events)
                    }
                }
                MouseArea {
                    anchors.fill: parent
                    cursorShape: Qt.PointingHandCursor
                    onClicked: events = events + 1
                }
            }
        }
    }
}
