// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var pct: 0.25
    property var dlgOpen: false
    cssClass: ["nv-section"]
    W.Text {
        cssClass: ["nv-title"]
        text: "HTML widgets"
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "Progress"
        }
        W.Progress {
            cssClass: ["hw-progress"]
            max: 1
            value: pct
        }
        W.Button {
            cssClass: ["hw-btn"]
            text: "+25%"
            onClicked: pct = pct >= 1 ? 0 : pct + 0.25
        }
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "Busy"
        }
        W.Progress {
            cssClass: ["hw-progress"]
        }
    }
    W.Fieldset {
        cssClass: ["hw-fieldset"]
        Css.CssText {
            cssClass: ["legend"]
            cssPrimitive: "legend"
            text: "Shipping"
        }
        W.Text {
            cssClass: ["hw-line"]
            text: "Standard delivery takes 3 to 5 business days."
        }
        W.Text {
            cssClass: ["hw-line"]
            text: "Orders over $199 ship free anywhere."
        }
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "Dialog"
        }
        W.Button {
            cssClass: ["hw-btn"]
            text: "Open dialog"
            onClicked: dlgOpen = true
        }
    }
    W.Dialog {
        open: !!(dlgOpen)
        cssClass: ["hw-dialog"]
        onDialogClosed: { dlgOpen = false }
        W.Div {
            cssClass: ["hw-dialog-body"]
            W.Text {
                cssClass: ["hw-dialog-title"]
                text: "Native dialog"
            }
            W.Text {
                cssClass: ["hw-line"]
                text: "A modal T.Dialog centered on the window overlay."
            }
            W.Button {
                cssClass: ["hw-btn"]
                text: "Close"
                onClicked: dlgOpen = false
            }
        }
    }
    W.Details {
        cssClass: ["hw-details"]
        summaryContent: [
            Css.CssText {
                cssPrimitive: ""
                text: "More details"
            }
        ]
        W.Text {
            cssClass: ["hw-line"]
            text: "The disclosure content only occupies space while open."
        }
        W.Text {
            cssClass: ["hw-line"]
            text: "Click the summary row to toggle."
        }
    }
}
