// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import QtQuick.Window

import solidqml.Widgets 1.0 as W
Css.CssRect {
    id: __self
    property var pct: 0.25
    property var dlgOpen: false
    cssClass: ["nv-section"]
    cssPrimitive: "div"
    Css.CssText {
        cssClass: ["nv-title"]
        cssPrimitive: "text"
        text: "HTML widgets"
    }
    Css.CssRect {
        cssClass: ["nv-row"]
        cssPrimitive: "div"
        Css.CssText {
            cssClass: ["nv-label"]
            cssPrimitive: "text"
            text: "Progress"
        }
        W.Progress {
            cssClass: ["hw-progress"]
            max: 1
            value: pct
        }
        W.Button {
            cssClass: ["hw-btn"]
            text: "+25%"
            onClicked: pct = pct >= 1 ? 0 : pct + 0.25
        }
    }
    Css.CssRect {
        cssClass: ["nv-row"]
        cssPrimitive: "div"
        Css.CssText {
            cssClass: ["nv-label"]
            cssPrimitive: "text"
            text: "Busy"
        }
        W.Progress {
            cssClass: ["hw-progress"]
        }
    }
    W.Fieldset {
        cssClass: ["hw-fieldset"]
        Css.CssText {
            cssClass: ["legend"]
            cssPrimitive: "legend"
            text: "Shipping"
        }
        Css.CssText {
            cssClass: ["hw-line"]
            cssPrimitive: "text"
            text: "Standard delivery takes 3 to 5 business days."
        }
        Css.CssText {
            cssClass: ["hw-line"]
            cssPrimitive: "text"
            text: "Orders over $199 ship free anywhere."
        }
    }
    Css.CssRect {
        cssClass: ["nv-row"]
        cssPrimitive: "div"
        Css.CssText {
            cssClass: ["nv-label"]
            cssPrimitive: "text"
            text: "Dialog"
        }
        W.Button {
            cssClass: ["hw-btn"]
            text: "Open dialog"
            onClicked: dlgOpen = true
        }
    }
    Item {
        id: __dialog0W
        width: 0
        height: 0
        Window {
            id: __dialog0
            flags: Qt.Dialog
            modality: Qt.WindowModal
            transientParent: __dialog0W.Window.window
            title: ""
            visible: !!(dlgOpen)
            width: Math.max(1, __dialog0Root.implicitWidth)
            height: Math.max(1, __dialog0Root.implicitHeight)
            onClosing: { dlgOpen = false }
            Css.CssRect {
                id: __dialog0Root
                anchors.fill: parent
                property Item cssAncestor: __dialog0W
            cssClass: ["hw-dialog"]
                cssPrimitive: "dialog"
                Css.CssRect {
                    cssClass: ["hw-dialog-body"]
                    cssPrimitive: "div"
                    Css.CssText {
                        cssClass: ["hw-dialog-title"]
                        cssPrimitive: "text"
                        text: "Native dialog"
                    }
                    Css.CssText {
                        cssClass: ["hw-line"]
                        cssPrimitive: "text"
                        text: "A modal T.Dialog centered on the window overlay."
                    }
                    W.Button {
                        cssClass: ["hw-btn"]
                        text: "Close"
                        onClicked: dlgOpen = false
                    }
                }
            }
        }
        Binding {
            target: __dialog0
            property: "visible"
            value: !!(dlgOpen)
            restoreMode: Binding.RestoreNone
        }
    }
    Css.CssFill {
        cssClass: ["hw-details"]
        id: __details1
        cssPrimitive: "details"
        cssState: __details1.__open ? ["open"] : []
        property bool __open: !!(false)
        Css.CssFill {
            cssPrimitive: "summary"
            cssState: (__details1.__open ? ["open"] : []).concat(__hover0.containsMouse ? ["hover"] : [])
            Item {
                anchors.fill: parent
                Text {
                    text: "▸"
                    rotation: __details1.__open ? 90 : 0
                    anchors.left: parent.left
                    anchors.leftMargin: 6
                    anchors.verticalCenter: parent.verticalCenter
                    Css.CssItem { cssPrimitive: "text"; cssClass: ["marker"] }
                }
            }
            Css.CssText {
                cssPrimitive: ""
                text: "More details"
            }
            MouseArea {
                id: __hover0
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: __details1.__open = !__details1.__open
            }
        }
        Css.CssRect {
            cssPrimitive: "div"
            cssClass: ["content"]
            visible: __details1.__open
            Css.CssText {
                cssClass: ["hw-line"]
                cssPrimitive: "text"
                text: "The disclosure content only occupies space while open."
            }
            Css.CssText {
                cssClass: ["hw-line"]
                cssPrimitive: "text"
                text: "Click the summary row to toggle."
            }
        }
    }
}
