// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
Css.CssRect {
    id: __self
    property var items: ["alpha", "beta", "gamma"]
    cssClass: ["app"]
    cssPrimitive: "div"
    W.Button {
        text: "add"
        onClicked: items = [...items, "more"]
    }
    Repeater {
        model: items
        Css.CssText {
            cssPrimitive: "text"
            text: "" + (index) + ": " + (modelData)
        }
    }
}
