// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import Qt.labs.platform 1.1 as Platform

import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var lastAction: "none yet"
    property var trayOn: true
    property var trayEcho: "tray idle"
    property var notifyEcho: solidNotifications.available ? "notification server ready" : "no notification server"
    property var selNode: "nothing"
    property var selItem: "nothing"
    property var selRow: "nothing"
    readonly property var treeData: [({ label: "src", children: [({ label: "emit", children: [({ label: "qml.ts" }), ({ label: "expr.ts" })] }), ({ label: "resolve", children: [({ label: "node.ts" })] }), ({ label: "index.ts" })] }), ({ label: "docs", children: [({ label: "roadmap.md" })] }), ({ label: "package.json" })]
    function notifyPlain() { var id = solidNotifications.send(({ title: "solid-qml", body: "Hello from the native gallery" })); notifyEcho = "sent #" + id_; }
    function notifyActions() { var id = solidNotifications.send(({ title: "solid-qml", body: "Pick an action — or reply right here", actions: [({ id: "ok", label: "OK" }), ({ id: "later", label: "Later" })], reply: "Type a reply…" })); notifyEcho = "sent #" + id_ + " (actions" + (solidNotifications.supportsReply ? " + reply" : "") + ")"; }
    property var __cleanups: []
    Component.onCompleted: { solidNotifications.actionInvoked.connect(function(id_, action) { return notifyEcho = "#" + id_ + " action: " + action }); solidNotifications.replied.connect(function(id_, replyText) { return notifyEcho = "#" + id_ + " reply: " + replyText }); solidNotifications.closed.connect(function(id_, reason) { return notifyEcho = "#" + id_ + " closed (reason " + reason + ")" }); }
    Component.onDestruction: { for (var i = 0; i < __cleanups.length; i++) __cleanups[i](); }
    cssClass: ["nv-section", "nv-menus"]
    W.Text {
        cssClass: ["nv-title"]
        text: "Menus & views"
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "menu"
        }
        Css.CssRect {
            id: __menuHost0
            cssPrimitive: "div"
            Window.onActiveChanged: if (!Window.active) __menu0.close()
            W.Button {
                id: __mtrig0
                onClicked: { if (__menu0.visible) __menu0.close(); else if (Date.now() - __menu0.__closedAt > 250) __menu0.open() }
                text: "Actions ▾"
            }
            W.Menu {
                id: __menu0
                cssAncestor: __menuHost0
                y: __menuHost0.height + 2
                W.MenuItem {
                    text: "&New file"
                    onTriggered: { lastAction = "new file" }
                }
                W.MenuItem {
                    text: "&Duplicate"
                    onTriggered: { lastAction = "duplicate" }
                }
                W.MenuSeparator { }
                W.MenuItem {
                    text: "&Delete"
                    onTriggered: { lastAction = "delete" }
                }
            }
        }
        W.Text {
            cssClass: ["nv-echo"]
            text: "last action: " + (lastAction)
        }
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "menubar"
        }
        W.Text {
            cssClass: ["nv-echo"]
            text: "(OS chrome — see the window title bar / global menu)"
        }
        Platform.MenuBar {
            Platform.Menu {
                title: "&File"
                Platform.MenuItem {
                    text: "&Open…"
                    onTriggered: { lastAction = "open…" }
                }
                Platform.MenuItem {
                    text: "&Save"
                    onTriggered: { lastAction = "save" }
                }
                Platform.MenuSeparator { }
                Platform.MenuItem {
                    text: "&Quit"
                    onTriggered: { lastAction = "quit" }
                }
            }
            Platform.Menu {
                title: "&Edit"
                Platform.MenuItem {
                    text: "&Copy"
                    onTriggered: { lastAction = "copy" }
                }
                Platform.MenuItem {
                    text: "&Paste"
                    onTriggered: { lastAction = "paste" }
                }
            }
        }
    }
    W.Div {
        cssClass: ["nv-row", "nv-tree-row-host"]
        W.Text {
            cssClass: ["nv-label"]
            text: "treeview"
        }
        W.TreeView {
            cssClass: ["nv-tree"]
            __treeData: treeData
            onSelected: (node) => { selNode = node.label }
        }
        W.Text {
            cssClass: ["nv-echo"]
            text: "selected: " + (selNode)
        }
    }
    W.Div {
        cssClass: ["nv-row", "nv-tree-row-host"]
        W.Text {
            cssClass: ["nv-label"]
            text: "listview"
        }
        W.ListView {
            cssClass: ["nv-list"]
            __listData: ["Inbox", "Starred", "Sent", "Drafts", "Spam", "Trash", "Archive"]
            onSelected: (item, index) => { selItem = item }
        }
        W.Text {
            cssClass: ["nv-echo"]
            text: "selected: " + (selItem)
        }
    }
    W.Div {
        cssClass: ["nv-row", "nv-tree-row-host"]
        W.Text {
            cssClass: ["nv-label"]
            text: "tableview"
        }
        W.TableView {
            cssClass: ["nv-table"]
            __columns: [({ key: "name", label: "Name" }), ({ key: "role", label: "Role" }), ({ key: "lang", label: "Lang" })]
            __rows: [({ name: "Ada Lovelace", role: "Analyst", lang: "Note G" }), ({ name: "Alan Turing", role: "Logician", lang: "Machine" }), ({ name: "Grace Hopper", role: "Compiler", lang: "COBOL" }), ({ name: "Dennis Ritchie", role: "Systems", lang: "C" })]
            onSelected: (row, index) => { selRow = row.name }
        }
        W.Text {
            cssClass: ["nv-echo"]
            text: "selected: " + (selRow)
        }
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "Tray"
        }
        W.Tray {
            shown: !!(trayOn)
            tooltip: "solid-qml gallery"
            iconSource: "assets/logo.png"
            onActivated: { trayEcho = "icon activated" }
            menu: Platform.Menu {
                Platform.MenuItem {
                    text: "&Open gallery"
                    onTriggered: { trayEcho = "tray menu: open" }
                }
                Platform.MenuItem {
                    text: "&Notify"
                    onTriggered: { notifyPlain() }
                }
                Platform.MenuItem { separator: true }
                Platform.MenuItem {
                    text: "&Remove icon"
                    onTriggered: { trayOn = false }
                }
            }
        }
        W.Button {
            cssClass: ["hw-btn"]
            text: "" + (trayOn ? "remove tray icon" : "show tray icon")
            onClicked: trayOn = !trayOn
        }
        W.Text {
            cssClass: ["nv-echo"]
            text: "" + (trayEcho)
        }
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "notify"
        }
        W.Button {
            cssClass: ["hw-btn"]
            text: "simple"
            onClicked: notifyPlain()
        }
        W.Button {
            cssClass: ["hw-btn"]
            text: "actions + reply"
            onClicked: notifyActions()
        }
        W.Text {
            cssClass: ["nv-echo"]
            text: "" + (notifyEcho)
        }
    }
}
