// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W

import QtQuick.Templates 6.0 as T
W.Div {
    id: __self
    property var lastAction: "none yet"
    property var selNode: "nothing"
    readonly property var treeData: [({ label: "src", children: [({ label: "emit", children: [({ label: "qml.ts" }), ({ label: "expr.ts" })] }), ({ label: "resolve", children: [({ label: "node.ts" })] }), ({ label: "index.ts" })] }), ({ label: "docs", children: [({ label: "roadmap.md" })] }), ({ label: "package.json" })]
    cssClass: ["nv-section", "nv-menus"]
    W.Text {
        cssClass: ["nv-title"]
        text: "Menus & views"
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "menu"
        }
        Item {
            id: __menuHost0
            implicitWidth: __mtrig0.implicitWidth
            implicitHeight: __mtrig0.implicitHeight
            Window.onActiveChanged: if (!Window.active) __menu0.close()
            W.Button {
                id: __mtrig0
                onClicked: { if (__menu0.visible) __menu0.close(); else if (Date.now() - __menu0.__closedAt > 250) __menu0.open() }
                text: "Actions ▾"
            }
            W.Menu {
                id: __menu0
                cssAncestor: __menuHost0
                y: __menuHost0.height + 2
                W.MenuItem {
                    text: "&New file"
                    onTriggered: { lastAction = "new file" }
                }
                W.MenuItem {
                    text: "&Duplicate"
                    onTriggered: { lastAction = "duplicate" }
                }
                W.MenuSeparator { }
                W.MenuItem {
                    text: "&Delete"
                    onTriggered: { lastAction = "delete" }
                }
            }
        }
        W.Text {
            cssClass: ["nv-echo"]
            text: "last action: " + (lastAction)
        }
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "menubar"
        }
        Css.CssFill {
            cssClass: ["nv-menubar"]
            cssPrimitive: "div"
            implicitWidth: __mbar1.implicitWidth
            implicitHeight: __mbar1.implicitHeight
            T.MenuBar {
                id: __mbar1
                anchors.fill: parent
                implicitWidth: Math.max(implicitBackgroundWidth + leftInset + rightInset, implicitContentWidth + leftPadding + rightPadding)
                implicitHeight: Math.max(implicitBackgroundHeight + topInset + bottomInset, implicitContentHeight + topPadding + bottomPadding)
                contentItem: Row {
                    spacing: __mbar1.spacing
                    Repeater { model: __mbar1.contentModel }
                }
                background: Css.CssFill {
                    cssPrimitive: "div"
                    cssClass: ["menubar"]
                }
                T.MenuBarItem {
                    id: __mbi2
                    hoverEnabled: true
                    implicitWidth: implicitContentWidth + leftPadding + rightPadding
                    implicitHeight: implicitContentHeight + topPadding + bottomPadding
                    leftPadding: 12
                    rightPadding: 12
                    topPadding: 6
                    bottomPadding: 6
                    Window.onActiveChanged: if (!Window.active && __mbi2.menu) __mbi2.menu.close()
                    menu: W.Menu {
                        id: __menu3
                        cssAncestor: __mbi2
                        title: "File"
                        W.MenuItem {
                            text: "Open…"
                            onTriggered: { lastAction = "open…" }
                        }
                        W.MenuItem {
                            text: "Save"
                            onTriggered: { lastAction = "save" }
                        }
                        W.MenuSeparator { }
                        W.MenuItem {
                            text: "Quit"
                            onTriggered: { lastAction = "quit" }
                        }
                    }
                    background: Css.CssFill {
                        cssPrimitive: "div"
                        cssClass: ["menubar-item"]
                        cssState: (__mbi2.hovered ? ["hover"] : []).concat(__mbi2.highlighted ? ["open"] : [])
                    }
                    contentItem: Css.CssText {
                        cssPrimitive: ""
                        cssClass: ["menubar-label"]
                        text: __mbi2.menu ? __mbi2.menu.title : ""
                    }
                }
                T.MenuBarItem {
                    id: __mbi4
                    hoverEnabled: true
                    implicitWidth: implicitContentWidth + leftPadding + rightPadding
                    implicitHeight: implicitContentHeight + topPadding + bottomPadding
                    leftPadding: 12
                    rightPadding: 12
                    topPadding: 6
                    bottomPadding: 6
                    Window.onActiveChanged: if (!Window.active && __mbi4.menu) __mbi4.menu.close()
                    menu: W.Menu {
                        id: __menu5
                        cssAncestor: __mbi4
                        title: "Edit"
                        W.MenuItem {
                            text: "Copy"
                            onTriggered: { lastAction = "copy" }
                        }
                        W.MenuItem {
                            text: "Paste"
                            onTriggered: { lastAction = "paste" }
                        }
                    }
                    background: Css.CssFill {
                        cssPrimitive: "div"
                        cssClass: ["menubar-item"]
                        cssState: (__mbi4.hovered ? ["hover"] : []).concat(__mbi4.highlighted ? ["open"] : [])
                    }
                    contentItem: Css.CssText {
                        cssPrimitive: ""
                        cssClass: ["menubar-label"]
                        text: __mbi4.menu ? __mbi4.menu.title : ""
                    }
                }
            }
        }
    }
    W.Div {
        cssClass: ["nv-row", "nv-tree-row-host"]
        W.Text {
            cssClass: ["nv-label"]
            text: "treeview"
        }
        W.TreeView {
            cssClass: ["nv-tree"]
            __treeData: treeData
            onSelected: (node) => { selNode = node.label }
        }
        W.Text {
            cssClass: ["nv-echo"]
            text: "selected: " + (selNode)
        }
    }
    W.Div {
        cssClass: ["nv-row"]
        W.Text {
            cssClass: ["nv-label"]
            text: "Tray"
        }
        W.Text {
            cssClass: ["nv-echo"]
            text: "<Tray> — native SystemTrayIcon (not shown here; see tests)"
        }
    }
}
