// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    readonly property var isNative: typeof process !== "undefined" && !!(process.versions && process.versions.solidQml)
    cssClass: ["native"]
    Repeater {
        model: (isNative) ? 1 : 0
        HtmlWidgets {
        }
    }
    Repeater {
        model: (isNative) ? 1 : 0
        Containers {
        }
    }
    Repeater {
        model: (isNative) ? 1 : 0
        ExtraInputs {
        }
    }
    Repeater {
        model: (isNative) ? 1 : 0
        MenusAndViews {
        }
    }
    Repeater {
        model: (isNative) ? 1 : 0
        CustomQml {
        }
    }
    Repeater {
        model: (!(isNative)) ? 1 : 0
        W.Div {
            cssClass: ["native-fallback"]
            W.Text {
                cssClass: ["native-fallback-t"]
                text: "native-only widgets — run this view in the QML loader"
            }
        }
    }
}
