// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    readonly property var isNative: typeof process !== "undefined" && !!process.versions && process.versions.solidQml
    cssClass: ["native"]
    HtmlWidgets {
        visible: !!(isNative)
    }
    Containers {
        visible: !!(isNative)
    }
    ExtraInputs {
        visible: !!(isNative)
    }
    MenusAndViews {
        visible: !!(isNative)
    }
    CustomQml {
        visible: !!(isNative)
    }
    W.Div {
        visible: !(isNative)
        cssClass: ["native-fallback"]
        W.Text {
            cssClass: ["native-fallback-t"]
            text: "native-only widgets — run this view in the QML loader"
        }
    }
}
