// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    readonly property var isNative: typeof process !== "undefined" && !!process.versions && process.versions.solidQml
    cssClass: ["native"]
    cssPrimitive: "div"
    HtmlWidgets {
        visible: !!(isNative)
    }
    Containers {
        visible: !!(isNative)
    }
    ExtraInputs {
        visible: !!(isNative)
    }
    MenusAndViews {
        visible: !!(isNative)
    }
    CustomQml {
        visible: !!(isNative)
    }
    Css.CssRect {
        visible: !(isNative)
        cssClass: ["native-fallback"]
        cssPrimitive: "div"
        Css.CssText {
            cssClass: ["native-fallback-t"]
            cssPrimitive: "text"
            text: "native-only widgets — run this view in the QML loader"
        }
    }
}
