// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css
import "modules/base64_5bfa1dd3aa.mjs" as Js0
import "modules/index_1602359716.mjs" as Js1


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    readonly property var runtime: typeof process !== "undefined" && process.versions && process.versions.solidQml ? "solid-qml " + process.versions.solidQml + " (Qt " + process.versions.qt + ", " + process.platform + ")" : "browser"
    readonly property var encoded: Js0.Base64.encode("solid-qml")
    readonly property var decoded: Js0.Base64.decode(encoded)
    readonly property var wrapped: Js1.Default("wrap-ansi pulls a small dependency tree with a diamond on strip-ansi", 24)
    cssClass: ["app"]
    W.Text {
        cssClass: ["title"]
        text: "node module imports"
    }
    W.Text {
        text: "runtime: " + (runtime)
    }
    W.Text {
        text: "Base64.encode(\"solid-qml\") = " + (encoded)
    }
    W.Text {
        text: "Base64.decode(...) = " + (decoded)
    }
    W.Text {
        text: "wrapAnsi(text, 24) →"
    }
    W.Text {
        text: "" + (wrapped)
    }
}
