// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    cssClass: ["app"]
    cssPrimitive: "div"
    Greeting {
    }
    Greeting {
        name: "Solid"
    }
    Greeting {
        greeting: "Hi"
        name: "QML"
    }
    Tag {
        label: "native"
    }
}
