// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    cssClass: ["app"]
    Greeting {
    }
    Greeting {
        name: "Solid"
    }
    Greeting {
        greeting: "Hi"
        name: "QML"
    }
    Tag {
        label: "native"
    }
}
