// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssText {
    id: __self
    property var label
    cssClass: ["bio"]
    cssPrimitive: "text"
    text: "#" + (label)
}
