// Generated by the transpiler. Do not edit by hand.
import QtQuick
import "qrc:/qmlcss" as Css

Css.CssRect {
    id: __self
    property var count: 0
    property var __cleanups: []
    Component.onCompleted: { var timer = setInterval(function() { return count = count + 1 }, 1000); __cleanups.push(function() { return clearInterval(timer) }); }
    Component.onDestruction: { for (var i = 0; i < __cleanups.length; i++) __cleanups[i](); }
    cssClass: ["app"]
    cssPrimitive: "div"
    Css.CssText {
        cssPrimitive: "text"
        text: "Count value is " + (count)
    }
}
