// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var todo
    property var onToggle
    property var onRemove
    cssClass: ["todo-row"].concat(todo.done ? ["completed"] : [])
    W.Button {
        cssClass: ["todo-toggle"]
        text: "" + (todo.done ? "✓" : "○")
        onClicked: onToggle(todo.id)
    }
    W.Text {
        cssClass: ["todo-title"]
        text: "" + (todo.title)
    }
    W.Button {
        cssClass: ["todo-remove"]
        text: "✕"
        onClicked: onRemove(todo.id)
    }
}
