// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    property var todos: []
    property var draft: ""
    property var filter: "all"
    readonly property var remaining: todos.filter(function(t) { return !t.done }).length
    readonly property var visible_: (function() { var f = filter; return todos.filter(function(t) { return f === "all" ? true : f === "active" ? !t.done : t.done }); })()
    property var nextId: 1
    function add() { var title = draft.trim(); if (!title) { return undefined; } todos = (function() { var __d = todos.slice(); (function(list) { return list.push(({ id: nextId++, title: title, done: false })) })(__d); return __d; })(); draft = ""; }
    function toggle(id_) { todos = todos.map(function(__t) { return (function(t) { return t.id === id_ })(__t) ? (function() { var __o = Object.assign({}, __t); __o["done"] = (function(d) { return !d })(__t["done"]); return __o; })() : __t; }); }
    function remove(id_) { todos = (function(list) { return list.filter(function(t) { return t.id !== id_ }) })(todos); }
    function selectAll() { for (var t of todos) { if (!t.done) { toggle(t.id); } } }
    property var __cleanups: []
    Component.onCompleted: { var saved = localStorage.getItem("todos"); if (saved) { var restored = JSON.parse(saved); todos = restored; nextId = restored.reduce(function(max, todo) { return Math.max(max, todo.id) }, 0) + 1; } localStorage.setItem("todos", JSON.stringify(todos)); }
    Component.onDestruction: { for (var i = 0; i < __cleanups.length; i++) __cleanups[i](); }
    cssClass: ["todo-app"]
    cssPrimitive: "div"
    Css.CssText {
        cssClass: ["todo-h1"]
        cssPrimitive: "text"
        text: "todos"
    }
    Css.CssRect {
        cssClass: ["todo-newline"]
        cssPrimitive: "div"
        Css.CssFill {
            cssClass: ["todo-new"]
            TextInput {
                id: __input0
                anchors.fill: parent
                anchors.leftMargin: 12
                anchors.rightMargin: 12
                verticalAlignment: TextInput.AlignVCenter
                clip: true
                selectByMouse: true
                activeFocusOnTab: true
                color: parent.style && parent.style["color"] ? cssTheme.parseColor(parent.style["color"]) : "#2b2b2b"
                font.family: parent.style && parent.style["font-family"] ? cssTheme.resolveFontFamily(parent.style["font-family"], "Sans Serif") : cssTheme.resolveFontFamily("Sans Serif")
                font.pointSize: parent.style && parent.style["font-size"] ? cssTheme.parseFontSize(parent.style["font-size"], 13) : 13
                Component.onCompleted: text = draft
                onTextEdited: { draft = text }
                Keys.onPressed: (event) => { (event.key === Qt.Key_Return || event.key === Qt.Key_Enter) && add() }
                Text {
                    anchors.verticalCenter: parent.verticalCenter
                    anchors.left: parent.left
                    visible: parent.text.length === 0
                    text: "What needs to be done?"
                    color: "#9aa0a6"
                    font: parent.font
                }
                Connections {
                    target: __self
                    function onDraftChanged() { if (__input0.text !== draft) __input0.text = draft }
                }
            }
        }
        Css.CssFill {
            cssClass: ["todo-add"]
            cssState: __hover0.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "add"
            }
            MouseArea {
                id: __hover0
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: add()
            }
        }
    }
    Css.CssRect {
        cssClass: ["todo-list"]
        visible: !!(todos.length > 0)
        cssPrimitive: "div"
        Repeater {
            model: visible_
            TodoRow {
                todo: modelData
                onToggle: toggle
                onRemove: remove
            }
        }
    }
    Css.CssRect {
        cssClass: ["todo-footer"]
        visible: !!(todos.length > 0)
        cssPrimitive: "div"
        Css.CssText {
            cssClass: ["todo-count"]
            cssPrimitive: "text"
            text: "" + (remaining) + " left"
        }
        Css.CssRect {
            cssClass: ["todo-filters"]
            cssPrimitive: "div"
            Css.CssIncubator {
                active: (remaining > 0 && remaining < todos.length) ? true : false
                sourceComponent: Component {
                    Css.CssFill {
                        cssState: __hover1.containsMouse ? ["hover"] : []
                        cssPrimitive: "button"
                        Css.CssText {
                            cssPrimitive: "text"
                            text: "all"
                        }
                        MouseArea {
                            id: __hover1
                            anchors.fill: parent
                            hoverEnabled: true
                            cursorShape: Qt.PointingHandCursor
                            onClicked: selectAll()
                        }
                    }
                }
            }
            Css.CssFill {
                cssState: __hover2.containsMouse ? ["hover"] : []
                cssPrimitive: "button"
                Css.CssText {
                    cssPrimitive: "text"
                    text: "active"
                }
                MouseArea {
                    id: __hover2
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor
                    onClicked: filter = "active"
                }
            }
            Css.CssFill {
                cssState: __hover3.containsMouse ? ["hover"] : []
                cssPrimitive: "button"
                Css.CssText {
                    cssPrimitive: "text"
                    text: "done"
                }
                MouseArea {
                    id: __hover3
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor
                    onClicked: filter = "completed"
                }
            }
        }
    }
    Css.CssText {
        visible: !(todos.length > 0)
        cssClass: ["todo-empty"]
        cssPrimitive: "text"
        text: "no todos yet"
    }
}
