// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var todos: []
    property var draft: ""
    property var filter: "all"
    readonly property var remaining: todos.filter(function(t) { return !t.done }).length
    readonly property var visible_: (function() { var f = filter; return todos.filter(function(t) { return f === "all" ? true : f === "active" ? !t.done : t.done }); })()
    property var nextId: 1
    function add() { var title = draft.trim(); if (!title) { return undefined; } todos = (function() { var __d = todos.slice(); (function(list) { return list.push(({ id: nextId++, title: title, done: false })) })(__d); return __d; })(); draft = ""; }
    function toggle(id_) { todos = todos.map(function(__t) { return (function(t) { return t.id === id_ })(__t) ? (function() { var __o = Object.assign({}, __t); __o["done"] = (function(d) { return !d })(__t["done"]); return __o; })() : __t; }); }
    function remove(id_) { todos = (function(list) { return list.filter(function(t) { return t.id !== id_ }) })(todos); }
    function selectAll() { for (var t of todos) { if (!t.done) { toggle(t.id); } } }
    property var __cleanups: []
    Component.onCompleted: { var saved = localStorage.getItem("todos"); if (saved) { var restored = JSON.parse(saved); todos = restored; nextId = restored.reduce(function(max, todo) { return Math.max(max, todo.id) }, 0) + 1; } localStorage.setItem("todos", JSON.stringify(todos)); }
    Component.onDestruction: { for (var i = 0; i < __cleanups.length; i++) __cleanups[i](); }
    cssClass: ["todo-app"]
    W.Text {
        cssClass: ["todo-h1"]
        text: "todos"
    }
    W.Div {
        cssClass: ["todo-newline"]
        W.TextField {
            id: __input0
            cssClass: ["todo-new"]
            placeholder: "What needs to be done?"
            onTextEdited: { draft = text }
            onKeyPressed: (event) => { (event.key === Qt.Key_Return || event.key === Qt.Key_Enter) && add() }
            Binding {
                target: __input0
                property: "text"
                value: draft
                restoreMode: Binding.RestoreNone
            }
        }
        W.Button {
            cssClass: ["todo-add"]
            text: "add"
            onClicked: add()
        }
    }
    W.Div {
        cssClass: ["todo-list"]
        visible: !!(todos.length > 0)
        Css.CssRepeater {
            model: visible_
            delegate: Component {
                TodoRow {
                    todo: modelData
                    onToggle: toggle
                    onRemove: remove
                }
            }
        }
    }
    W.Div {
        cssClass: ["todo-footer"]
        visible: !!(todos.length > 0)
        W.Text {
            cssClass: ["todo-count"]
            text: "" + (remaining) + " left"
        }
        W.Div {
            cssClass: ["todo-filters"]
            Css.CssIncubator {
                active: (remaining > 0 && remaining < todos.length) ? true : false
                sourceComponent: Component {
                    W.Button {
                        text: "all"
                        onClicked: selectAll()
                    }
                }
            }
            W.Button {
                text: "active"
                onClicked: filter = "active"
            }
            W.Button {
                text: "done"
                onClicked: filter = "completed"
            }
        }
    }
    W.Text {
        visible: !(todos.length > 0)
        cssClass: ["todo-empty"]
        text: "no todos yet"
    }
}
