// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    property var todo
    property var onToggle
    property var onRemove
    cssClass: ["todo-row"].concat(todo.done ? ["completed"] : [])
    cssPrimitive: "div"
    Css.CssFill {
        cssClass: ["todo-toggle"]
        cssState: __hover0.containsMouse ? ["hover"] : []
        cssPrimitive: "button"
        Css.CssText {
            cssPrimitive: "text"
            text: "" + (todo.done ? "✓" : "○")
        }
        MouseArea {
            id: __hover0
            anchors.fill: parent
            hoverEnabled: true
            cursorShape: Qt.PointingHandCursor
            onClicked: onToggle(todo.id)
        }
    }
    Css.CssText {
        cssClass: ["todo-title"]
        cssPrimitive: "text"
        text: "" + (todo.title)
    }
    Css.CssFill {
        cssClass: ["todo-remove"]
        cssState: __hover1.containsMouse ? ["hover"] : []
        cssPrimitive: "button"
        Css.CssText {
            cssPrimitive: "text"
            text: "✕"
        }
        MouseArea {
            id: __hover1
            anchors.fill: parent
            hoverEnabled: true
            cursorShape: Qt.PointingHandCursor
            onClicked: onRemove(todo.id)
        }
    }
}
