// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W

import QtQuick.Templates 6.0 as T
W.Div {
    id: __self
    property var inputName: ""
    property var inputPass: ""
    property var inputSearch: ""
    property var inputNotes: ""
    property var chk1: false
    property var chk2: true
    property var sw: false
    property var tabs: true
    property var plan: "free"
    property var fruit: "apple"
    property var volume: 50
    property var qty: 1
    property var inputDate: null
    property var calDate: null
    function reset() { inputName = ""; inputPass = ""; inputSearch = ""; inputNotes = ""; chk1 = false; chk2 = true; sw = false; plan = "free"; fruit = "apple"; volume = 50; qty = 1; inputDate = null; calDate = null; }
    T.ButtonGroup { id: __group_plan; readonly property var order: [__input10, __input11, __input12] }
    cssClass: ["widgets"]
    W.Div {
        cssClass: ["wg-cols"]
        W.Div {
            cssClass: ["wg-section"]
            W.Text {
                cssClass: ["wg-title"]
                text: "Text"
            }
            W.Div {
                cssClass: ["wg-field"]
                W.Text {
                    cssClass: ["wg-label"]
                    text: "Name"
                }
                W.TextField {
                    id: __input0
                    cssClass: ["wg-input"]
                    placeholder: "Your name"
                    onTextEdited: { inputName = text }
                    Binding {
                        target: __input0
                        property: "text"
                        value: inputName
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
            W.Div {
                cssClass: ["wg-field"]
                W.Text {
                    cssClass: ["wg-label"]
                    text: "Password"
                }
                W.TextField {
                    id: __input1
                    cssClass: ["wg-input"]
                    echoMode: TextInput.Password
                    placeholder: "Secret"
                    onTextEdited: { inputPass = text }
                    Binding {
                        target: __input1
                        property: "text"
                        value: inputPass
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
            W.Div {
                cssClass: ["wg-field"]
                W.Text {
                    cssClass: ["wg-label"]
                    text: "Search (max 20)"
                }
                W.TextField {
                    id: __input2
                    cssClass: ["wg-input"]
                    maximumLength: 20
                    placeholder: "Search…"
                    onTextEdited: { inputSearch = text }
                    Binding {
                        target: __input2
                        property: "text"
                        value: inputSearch
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
            W.Div {
                cssClass: ["wg-field"]
                W.Text {
                    cssClass: ["wg-label"]
                    text: "Disabled"
                }
                W.TextField {
                    id: __input3
                    cssClass: ["wg-input"]
                    enabled: false
                    placeholder: "Not editable"
                }
            }
            W.Div {
                cssClass: ["wg-field"]
                W.Text {
                    cssClass: ["wg-label"]
                    text: "Notes"
                }
                W.TextArea {
                    id: __input4
                    cssClass: ["wg-textarea"]
                    placeholder: "Add notes…"
                    onTextChanged: { inputNotes = text }
                    Binding {
                        target: __input4
                        property: "text"
                        value: inputNotes
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
        }
        W.Div {
            cssClass: ["wg-section"]
            W.Text {
                cssClass: ["wg-title"]
                text: "Toggles"
            }
            W.Div {
                cssClass: ["wg-check-row"]
                W.Checkbox {
                    id: __input5
                    cssClass: ["wg-checkbox"]
                    onToggled: { chk1 = __input5.checked }
                    Binding {
                        target: __input5
                        property: "checked"
                        value: chk1
                        restoreMode: Binding.RestoreNone
                    }
                }
                W.Text {
                    cssClass: ["wg-check-label"]
                    text: "Accept terms"
                }
            }
            W.Div {
                cssClass: ["wg-check-row"]
                W.Checkbox {
                    id: __input6
                    cssClass: ["wg-checkbox"]
                    onToggled: { chk2 = __input6.checked }
                    Binding {
                        target: __input6
                        property: "checked"
                        value: chk2
                        restoreMode: Binding.RestoreNone
                    }
                }
                W.Text {
                    cssClass: ["wg-check-label"]
                    text: "Send updates (pre-checked)"
                }
            }
            W.Div {
                cssClass: ["wg-check-row"]
                W.Toggle {
                    id: __input7
                    cssClass: ["wg-switch"]
                    onToggled: { sw = __input7.checked }
                    Binding {
                        target: __input7
                        property: "checked"
                        value: sw
                        restoreMode: Binding.RestoreNone
                    }
                }
                W.Text {
                    cssClass: ["wg-check-label"]
                    text: "Dark mode"
                }
            }
            W.Div {
                cssClass: ["wg-check-row"]
                W.Checkbox {
                    id: __input8
                    cssClass: ["wg-checkbox"]
                    enabled: false
                }
                W.Text {
                    cssClass: ["wg-check-label"]
                    text: "Disabled checkbox"
                }
            }
            W.Div {
                cssClass: ["wg-check-row"]
                W.Toggle {
                    id: __input9
                    cssClass: ["wg-switch"]
                    onToggled: { tabs = __input9.checked; solidTabstop.enabled = __input9.checked; }
                    Binding {
                        target: __input9
                        property: "checked"
                        value: tabs
                        restoreMode: Binding.RestoreNone
                    }
                }
                W.Text {
                    cssClass: ["wg-check-label"]
                    text: "Tab navigation (native only)"
                }
            }
            W.Text {
                cssClass: ["wg-sublabel"]
                text: "Plan"
            }
            W.Div {
                cssClass: ["wg-check-row"]
                Css.CssFill {
                    cssClass: ["wg-radio"]
                    cssPrimitive: "input"
                    cssState: (__input10.activeFocus ? ["focus"] : []).concat(__input10.checked ? ["checked"] : []).concat(!__input10.enabled ? ["disabled"] : [])
                    implicitWidth: __input10.implicitWidth
                    implicitHeight: __input10.implicitHeight
                    T.RadioButton {
                        id: __input10
                        anchors.fill: parent
                        background: null
                        contentItem: null
                        activeFocusOnTab: solidTabstop.enabled && (__input10.checked || (!__group_plan.checkedButton && __group_plan.buttons.length > 0 && __group_plan.buttons[0] === __input10))
                        T.ButtonGroup.group: __group_plan
                        function __step(d) { var bs = __group_plan.order; var j = (bs.indexOf(__input10) + d + bs.length) % bs.length; bs[j].checked = true; bs[j].forceActiveFocus(Qt.TabFocusReason) }
                        Keys.onDownPressed: __step(1)
                        Keys.onRightPressed: __step(1)
                        Keys.onUpPressed: __step(-1)
                        Keys.onLeftPressed: __step(-1)
                        indicator: Css.CssFill {
                            cssPrimitive: "span"
                            cssClass: ["indicator"]
                            cssState: (__input10.activeFocus ? ["focus"] : []).concat(__input10.checked ? ["checked"] : []).concat(!__input10.enabled ? ["disabled"] : [])
                            width: 20
                            height: 20
                            implicitWidth: 20
                            implicitHeight: 20
                            Item {
                                anchors.fill: parent
                                Rectangle {
                                    visible: __input10.checked
                                    anchors.centerIn: parent
                                    width: 8
                                    height: 8
                                    radius: 4
                                    color: "#2b2b2b"
                                    Css.CssItem { cssPrimitive: "rect"; cssClass: __input10.checked ? ["indicator-dot", "checked"] : ["indicator-dot"] }
                                }
                            }
                        }
                        onCheckedChanged: { if (__input10.checked) { plan = "free" } }
                    }
                    Binding {
                        target: __input10
                        property: "checked"
                        value: plan === "free"
                        restoreMode: Binding.RestoreNone
                    }
                }
                W.Text {
                    cssClass: ["wg-check-label"]
                    text: "Free"
                }
            }
            W.Div {
                cssClass: ["wg-check-row"]
                Css.CssFill {
                    cssClass: ["wg-radio"]
                    cssPrimitive: "input"
                    cssState: (__input11.activeFocus ? ["focus"] : []).concat(__input11.checked ? ["checked"] : []).concat(!__input11.enabled ? ["disabled"] : [])
                    implicitWidth: __input11.implicitWidth
                    implicitHeight: __input11.implicitHeight
                    T.RadioButton {
                        id: __input11
                        anchors.fill: parent
                        background: null
                        contentItem: null
                        activeFocusOnTab: solidTabstop.enabled && (__input11.checked || (!__group_plan.checkedButton && __group_plan.buttons.length > 0 && __group_plan.buttons[0] === __input11))
                        T.ButtonGroup.group: __group_plan
                        function __step(d) { var bs = __group_plan.order; var j = (bs.indexOf(__input11) + d + bs.length) % bs.length; bs[j].checked = true; bs[j].forceActiveFocus(Qt.TabFocusReason) }
                        Keys.onDownPressed: __step(1)
                        Keys.onRightPressed: __step(1)
                        Keys.onUpPressed: __step(-1)
                        Keys.onLeftPressed: __step(-1)
                        indicator: Css.CssFill {
                            cssPrimitive: "span"
                            cssClass: ["indicator"]
                            cssState: (__input11.activeFocus ? ["focus"] : []).concat(__input11.checked ? ["checked"] : []).concat(!__input11.enabled ? ["disabled"] : [])
                            width: 20
                            height: 20
                            implicitWidth: 20
                            implicitHeight: 20
                            Item {
                                anchors.fill: parent
                                Rectangle {
                                    visible: __input11.checked
                                    anchors.centerIn: parent
                                    width: 8
                                    height: 8
                                    radius: 4
                                    color: "#2b2b2b"
                                    Css.CssItem { cssPrimitive: "rect"; cssClass: __input11.checked ? ["indicator-dot", "checked"] : ["indicator-dot"] }
                                }
                            }
                        }
                        onCheckedChanged: { if (__input11.checked) { plan = "pro" } }
                    }
                    Binding {
                        target: __input11
                        property: "checked"
                        value: plan === "pro"
                        restoreMode: Binding.RestoreNone
                    }
                }
                W.Text {
                    cssClass: ["wg-check-label"]
                    text: "Pro"
                }
            }
            W.Div {
                cssClass: ["wg-check-row"]
                Css.CssFill {
                    cssClass: ["wg-radio"]
                    cssPrimitive: "input"
                    cssState: (__input12.activeFocus ? ["focus"] : []).concat(__input12.checked ? ["checked"] : []).concat(!__input12.enabled ? ["disabled"] : [])
                    implicitWidth: __input12.implicitWidth
                    implicitHeight: __input12.implicitHeight
                    T.RadioButton {
                        id: __input12
                        anchors.fill: parent
                        background: null
                        contentItem: null
                        activeFocusOnTab: solidTabstop.enabled && (__input12.checked || (!__group_plan.checkedButton && __group_plan.buttons.length > 0 && __group_plan.buttons[0] === __input12))
                        T.ButtonGroup.group: __group_plan
                        function __step(d) { var bs = __group_plan.order; var j = (bs.indexOf(__input12) + d + bs.length) % bs.length; bs[j].checked = true; bs[j].forceActiveFocus(Qt.TabFocusReason) }
                        Keys.onDownPressed: __step(1)
                        Keys.onRightPressed: __step(1)
                        Keys.onUpPressed: __step(-1)
                        Keys.onLeftPressed: __step(-1)
                        indicator: Css.CssFill {
                            cssPrimitive: "span"
                            cssClass: ["indicator"]
                            cssState: (__input12.activeFocus ? ["focus"] : []).concat(__input12.checked ? ["checked"] : []).concat(!__input12.enabled ? ["disabled"] : [])
                            width: 20
                            height: 20
                            implicitWidth: 20
                            implicitHeight: 20
                            Item {
                                anchors.fill: parent
                                Rectangle {
                                    visible: __input12.checked
                                    anchors.centerIn: parent
                                    width: 8
                                    height: 8
                                    radius: 4
                                    color: "#2b2b2b"
                                    Css.CssItem { cssPrimitive: "rect"; cssClass: __input12.checked ? ["indicator-dot", "checked"] : ["indicator-dot"] }
                                }
                            }
                        }
                        onCheckedChanged: { if (__input12.checked) { plan = "team" } }
                    }
                    Binding {
                        target: __input12
                        property: "checked"
                        value: plan === "team"
                        restoreMode: Binding.RestoreNone
                    }
                }
                W.Text {
                    cssClass: ["wg-check-label"]
                    text: "Team"
                }
            }
        }
    }
    W.Div {
        cssClass: ["wg-cols"]
        W.Div {
            cssClass: ["wg-section"]
            W.Text {
                cssClass: ["wg-title"]
                text: "Pickers"
            }
            W.Div {
                cssClass: ["wg-field"]
                W.Text {
                    cssClass: ["wg-label"]
                    text: "Fruit"
                }
                W.Select {
                    id: __input13
                    cssClass: ["wg-select"]
                    model: ["Apple", "Banana", "Cherry", "Mango"]
                    values: ["apple", "banana", "cherry", "mango"]
                    onActivated: (index) => { fruit = __input13.values[index] }
                    Binding {
                        target: __input13
                        property: "currentIndex"
                        value: __input13.values.indexOf(fruit)
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
            W.Div {
                cssClass: ["wg-field"]
                W.Div {
                    cssClass: ["wg-range-header"]
                    W.Text {
                        cssClass: ["wg-label"]
                        text: "Volume"
                    }
                    W.Text {
                        cssClass: ["wg-range-val"]
                        text: "" + (volume)
                    }
                }
                W.Slider {
                    id: __input14
                    cssClass: ["wg-range"]
                    from: 0
                    to: 100
                    stepSize: 1
                    onMoved: { volume = __input14.value }
                    Binding {
                        target: __input14
                        property: "value"
                        value: volume
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
            W.Div {
                cssClass: ["wg-field"]
                W.Text {
                    cssClass: ["wg-label"]
                    text: "Quantity"
                }
                W.SpinBox {
                    id: __input15
                    cssClass: ["wg-number"]
                    from: 1
                    to: 10
                    stepSize: 1
                    onValueModified: { qty = __input15.value }
                    Binding {
                        target: __input15
                        property: "value"
                        value: qty
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
            W.Div {
                cssClass: ["wg-field"]
                W.Text {
                    cssClass: ["wg-label"]
                    text: "Date"
                }
                W.DateField {
                    cssClass: ["wg-date"]
                    value: inputDate
                    onDayPicked: (date) => { inputDate = date }
                }
            }
        }
        W.Div {
            cssClass: ["wg-section", "wg-cal-section"]
            W.Text {
                cssClass: ["wg-title"]
                text: "Calendar"
            }
            W.Calendar {
                cssClass: ["wg-cal"]
                value: calDate
                onDayPicked: (date) => { calDate = date }
            }
        }
    }
    W.Div {
        cssClass: ["wg-summary"]
        W.Text {
            cssClass: ["wg-title"]
            text: "Form state"
        }
        W.Div {
            cssClass: ["wg-kv-grid"]
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "name"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (inputName)
                }
            }
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "pass"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (inputPass ? "set" : "—")
                }
            }
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "search"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (inputSearch)
                }
            }
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "notes"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (inputNotes ? "set" : "—")
                }
            }
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "check1"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (chk1 ? "on" : "off")
                }
            }
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "check2"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (chk2 ? "on" : "off")
                }
            }
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "switch"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (sw ? "on" : "off")
                }
            }
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "plan"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (plan)
                }
            }
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "fruit"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (fruit)
                }
            }
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "volume"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (volume)
                }
            }
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "qty"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (qty)
                }
            }
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "date"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (inputDate ? "selected" : "—")
                }
            }
            W.Div {
                cssClass: ["wg-kv-row"]
                W.Text {
                    cssClass: ["wg-kv"]
                    text: "cal"
                }
                W.Text {
                    cssClass: ["wg-kv-v"]
                    text: "" + (calDate ? "selected" : "—")
                }
            }
        }
        W.Button {
            cssClass: ["wg-reset"]
            text: "Reset"
            onClicked: reset()
        }
    }
}
