// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import QtQuick.Templates 6.8 as T
Css.CssRect {
    id: __self
    property var inputName: ""
    property var inputPass: ""
    property var inputSearch: ""
    property var inputNotes: ""
    property var chk1: false
    property var chk2: true
    property var sw: false
    property var tabs: true
    property var plan: "free"
    property var fruit: "apple"
    property var volume: 50
    property var qty: 1
    property var inputDate: null
    property var calDate: null
    function reset() { inputName = ""; inputPass = ""; inputSearch = ""; inputNotes = ""; chk1 = false; chk2 = true; sw = false; plan = "free"; fruit = "apple"; volume = 50; qty = 1; inputDate = null; calDate = null; }
    T.ButtonGroup { id: __group_plan }
    cssClass: ["widgets"]
    cssPrimitive: "div"
    Css.CssRect {
        cssClass: ["wg-cols"]
        cssPrimitive: "div"
        Css.CssRect {
            cssClass: ["wg-section"]
            cssPrimitive: "div"
            Css.CssText {
                cssClass: ["wg-title"]
                cssPrimitive: "text"
                text: "Text"
            }
            Css.CssRect {
                cssClass: ["wg-field"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-label"]
                    cssPrimitive: "text"
                    text: "Name"
                }
                Css.CssFill {
                    cssClass: ["wg-input"]
                    cssPrimitive: "input"
                    cssState: (__input0.activeFocus ? ["focus"] : []).concat(!__input0.enabled ? ["disabled"] : [])
                    implicitWidth: __input0.implicitWidth
                    implicitHeight: __input0.implicitHeight
                    T.TextField {
                        id: __input0
                        anchors.fill: parent
                        background: null
                        color: cssTheme.parseColor(parent.inheritedColor || "#2b2b2b")
                        font.family: cssTheme.resolveFontFamily(parent.inheritedFontFamily || "Sans Serif")
                        font.pixelSize: cssTheme.parseFontSize(parent.inheritedFontSize || "13px", 13)
                        leftPadding: 12
                        rightPadding: 12
                        verticalAlignment: TextInput.AlignVCenter
                        selectByMouse: true
                        activeFocusOnTab: solidTabstop.enabled
                        onTextEdited: { inputName = text }
                        Text {
                            anchors.verticalCenter: parent.verticalCenter
                            anchors.left: parent.left
                            anchors.leftMargin: parent.leftPadding
                            visible: parent.text.length === 0 && !parent.activeFocus
                            text: "Your name"
                            color: "#9aa0a6"
                            font: parent.font
                        }
                    }
                    Binding {
                        target: __input0
                        property: "text"
                        value: inputName
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
            Css.CssRect {
                cssClass: ["wg-field"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-label"]
                    cssPrimitive: "text"
                    text: "Password"
                }
                Css.CssFill {
                    cssClass: ["wg-input"]
                    cssPrimitive: "input"
                    cssState: (__input1.activeFocus ? ["focus"] : []).concat(!__input1.enabled ? ["disabled"] : [])
                    implicitWidth: __input1.implicitWidth
                    implicitHeight: __input1.implicitHeight
                    T.TextField {
                        id: __input1
                        anchors.fill: parent
                        background: null
                        color: cssTheme.parseColor(parent.inheritedColor || "#2b2b2b")
                        font.family: cssTheme.resolveFontFamily(parent.inheritedFontFamily || "Sans Serif")
                        font.pixelSize: cssTheme.parseFontSize(parent.inheritedFontSize || "13px", 13)
                        leftPadding: 12
                        rightPadding: 12
                        verticalAlignment: TextInput.AlignVCenter
                        selectByMouse: true
                        activeFocusOnTab: solidTabstop.enabled
                        echoMode: TextInput.Password
                        onTextEdited: { inputPass = text }
                        Text {
                            anchors.verticalCenter: parent.verticalCenter
                            anchors.left: parent.left
                            anchors.leftMargin: parent.leftPadding
                            visible: parent.text.length === 0 && !parent.activeFocus
                            text: "Secret"
                            color: "#9aa0a6"
                            font: parent.font
                        }
                    }
                    Binding {
                        target: __input1
                        property: "text"
                        value: inputPass
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
            Css.CssRect {
                cssClass: ["wg-field"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-label"]
                    cssPrimitive: "text"
                    text: "Search (max 20)"
                }
                Css.CssFill {
                    cssClass: ["wg-input"]
                    cssPrimitive: "input"
                    cssState: (__input2.activeFocus ? ["focus"] : []).concat(!__input2.enabled ? ["disabled"] : [])
                    implicitWidth: __input2.implicitWidth
                    implicitHeight: __input2.implicitHeight
                    T.TextField {
                        id: __input2
                        anchors.fill: parent
                        background: null
                        color: cssTheme.parseColor(parent.inheritedColor || "#2b2b2b")
                        font.family: cssTheme.resolveFontFamily(parent.inheritedFontFamily || "Sans Serif")
                        font.pixelSize: cssTheme.parseFontSize(parent.inheritedFontSize || "13px", 13)
                        leftPadding: 12
                        rightPadding: 12
                        verticalAlignment: TextInput.AlignVCenter
                        selectByMouse: true
                        activeFocusOnTab: solidTabstop.enabled
                        maximumLength: 20
                        onTextEdited: { inputSearch = text }
                        Text {
                            anchors.verticalCenter: parent.verticalCenter
                            anchors.left: parent.left
                            anchors.leftMargin: parent.leftPadding
                            visible: parent.text.length === 0 && !parent.activeFocus
                            text: "Search…"
                            color: "#9aa0a6"
                            font: parent.font
                        }
                    }
                    Binding {
                        target: __input2
                        property: "text"
                        value: inputSearch
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
            Css.CssRect {
                cssClass: ["wg-field"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-label"]
                    cssPrimitive: "text"
                    text: "Disabled"
                }
                Css.CssFill {
                    cssClass: ["wg-input"]
                    cssPrimitive: "input"
                    cssState: (__input3.activeFocus ? ["focus"] : []).concat(!__input3.enabled ? ["disabled"] : [])
                    implicitWidth: __input3.implicitWidth
                    implicitHeight: __input3.implicitHeight
                    T.TextField {
                        id: __input3
                        anchors.fill: parent
                        background: null
                        color: cssTheme.parseColor(parent.inheritedColor || "#2b2b2b")
                        font.family: cssTheme.resolveFontFamily(parent.inheritedFontFamily || "Sans Serif")
                        font.pixelSize: cssTheme.parseFontSize(parent.inheritedFontSize || "13px", 13)
                        leftPadding: 12
                        rightPadding: 12
                        verticalAlignment: TextInput.AlignVCenter
                        selectByMouse: true
                        activeFocusOnTab: solidTabstop.enabled
                        enabled: false
                        Text {
                            anchors.verticalCenter: parent.verticalCenter
                            anchors.left: parent.left
                            anchors.leftMargin: parent.leftPadding
                            visible: parent.text.length === 0 && !parent.activeFocus
                            text: "Not editable"
                            color: "#9aa0a6"
                            font: parent.font
                        }
                    }
                }
            }
            Css.CssRect {
                cssClass: ["wg-field"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-label"]
                    cssPrimitive: "text"
                    text: "Notes"
                }
                Css.CssFill {
                    cssClass: ["wg-textarea"]
                    cssPrimitive: "textarea"
                    cssState: (__input4.activeFocus ? ["focus"] : []).concat(!__input4.enabled ? ["disabled"] : [])
                    implicitWidth: __input4.implicitWidth
                    implicitHeight: __input4.implicitHeight
                    T.TextArea {
                        id: __input4
                        anchors.fill: parent
                        background: null
                        wrapMode: TextEdit.Wrap
                        color: cssTheme.parseColor(parent.inheritedColor || "#2b2b2b")
                        font.family: cssTheme.resolveFontFamily(parent.inheritedFontFamily || "Sans Serif")
                        font.pixelSize: cssTheme.parseFontSize(parent.inheritedFontSize || "13px", 13)
                        padding: 12
                        selectByMouse: true
                        activeFocusOnTab: solidTabstop.enabled
                        onTextChanged: { inputNotes = text }
                        Text {
                            anchors.top: parent.top
                            anchors.left: parent.left
                            anchors.topMargin: parent.padding
                            anchors.leftMargin: parent.padding
                            visible: parent.text.length === 0 && !parent.activeFocus
                            text: "Add notes…"
                            color: "#9aa0a6"
                            font: parent.font
                        }
                    }
                    Binding {
                        target: __input4
                        property: "text"
                        value: inputNotes
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
        }
        Css.CssRect {
            cssClass: ["wg-section"]
            cssPrimitive: "div"
            Css.CssText {
                cssClass: ["wg-title"]
                cssPrimitive: "text"
                text: "Toggles"
            }
            Css.CssRect {
                cssClass: ["wg-check-row"]
                cssPrimitive: "div"
                Css.CssFill {
                    cssClass: ["wg-checkbox"]
                    cssPrimitive: "input"
                    cssState: (__input5.activeFocus ? ["focus"] : []).concat(__input5.checked ? ["checked"] : []).concat(!__input5.enabled ? ["disabled"] : [])
                    implicitWidth: __input5.implicitWidth
                    implicitHeight: __input5.implicitHeight
                    T.CheckBox {
                        id: __input5
                        anchors.fill: parent
                        background: null
                        contentItem: null
                        activeFocusOnTab: solidTabstop.enabled
                        Keys.onDownPressed: { if (solidTabstop.enabled) { var __n = __input5.nextItemInFocusChain(true); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onRightPressed: { if (solidTabstop.enabled) { var __n = __input5.nextItemInFocusChain(true); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onUpPressed: { if (solidTabstop.enabled) { var __n = __input5.nextItemInFocusChain(false); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onLeftPressed: { if (solidTabstop.enabled) { var __n = __input5.nextItemInFocusChain(false); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        indicator: Css.CssFill {
                            cssPrimitive: "span"
                            cssClass: ["indicator"]
                            cssState: (__input5.activeFocus ? ["focus"] : []).concat(__input5.checked ? ["checked"] : []).concat(!__input5.enabled ? ["disabled"] : [])
                            width: 20
                            height: 20
                            implicitWidth: 20
                            implicitHeight: 20
                            Item {
                                anchors.fill: parent
                                Text {
                                    text: "✓"
                                    visible: __input5.checked
                                    anchors.centerIn: parent
                                    Css.CssItem { cssPrimitive: "text"; cssClass: ["indicator-glyph"] }
                                }
                            }
                        }
                        onToggled: { chk1 = __input5.checked }
                    }
                    Binding {
                        target: __input5
                        property: "checked"
                        value: chk1
                        restoreMode: Binding.RestoreNone
                    }
                }
                Css.CssText {
                    cssClass: ["wg-check-label"]
                    cssPrimitive: "text"
                    text: "Accept terms"
                }
            }
            Css.CssRect {
                cssClass: ["wg-check-row"]
                cssPrimitive: "div"
                Css.CssFill {
                    cssClass: ["wg-checkbox"]
                    cssPrimitive: "input"
                    cssState: (__input6.activeFocus ? ["focus"] : []).concat(__input6.checked ? ["checked"] : []).concat(!__input6.enabled ? ["disabled"] : [])
                    implicitWidth: __input6.implicitWidth
                    implicitHeight: __input6.implicitHeight
                    T.CheckBox {
                        id: __input6
                        anchors.fill: parent
                        background: null
                        contentItem: null
                        activeFocusOnTab: solidTabstop.enabled
                        Keys.onDownPressed: { if (solidTabstop.enabled) { var __n = __input6.nextItemInFocusChain(true); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onRightPressed: { if (solidTabstop.enabled) { var __n = __input6.nextItemInFocusChain(true); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onUpPressed: { if (solidTabstop.enabled) { var __n = __input6.nextItemInFocusChain(false); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onLeftPressed: { if (solidTabstop.enabled) { var __n = __input6.nextItemInFocusChain(false); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        indicator: Css.CssFill {
                            cssPrimitive: "span"
                            cssClass: ["indicator"]
                            cssState: (__input6.activeFocus ? ["focus"] : []).concat(__input6.checked ? ["checked"] : []).concat(!__input6.enabled ? ["disabled"] : [])
                            width: 20
                            height: 20
                            implicitWidth: 20
                            implicitHeight: 20
                            Item {
                                anchors.fill: parent
                                Text {
                                    text: "✓"
                                    visible: __input6.checked
                                    anchors.centerIn: parent
                                    Css.CssItem { cssPrimitive: "text"; cssClass: ["indicator-glyph"] }
                                }
                            }
                        }
                        onToggled: { chk2 = __input6.checked }
                    }
                    Binding {
                        target: __input6
                        property: "checked"
                        value: chk2
                        restoreMode: Binding.RestoreNone
                    }
                }
                Css.CssText {
                    cssClass: ["wg-check-label"]
                    cssPrimitive: "text"
                    text: "Send updates (pre-checked)"
                }
            }
            Css.CssRect {
                cssClass: ["wg-check-row"]
                cssPrimitive: "div"
                Css.CssFill {
                    cssClass: ["wg-switch"]
                    cssPrimitive: "input"
                    cssState: (__input7.activeFocus ? ["focus"] : []).concat(__input7.checked ? ["checked"] : []).concat(!__input7.enabled ? ["disabled"] : [])
                    implicitWidth: __input7.implicitWidth
                    implicitHeight: __input7.implicitHeight
                    T.Switch {
                        id: __input7
                        anchors.fill: parent
                        background: null
                        contentItem: null
                        activeFocusOnTab: solidTabstop.enabled
                        Keys.onDownPressed: { if (solidTabstop.enabled) { var __n = __input7.nextItemInFocusChain(true); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onRightPressed: { if (solidTabstop.enabled) { var __n = __input7.nextItemInFocusChain(true); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onUpPressed: { if (solidTabstop.enabled) { var __n = __input7.nextItemInFocusChain(false); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onLeftPressed: { if (solidTabstop.enabled) { var __n = __input7.nextItemInFocusChain(false); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        indicator: Css.CssFill {
                            cssPrimitive: "span"
                            cssClass: ["track"]
                            cssState: (__input7.activeFocus ? ["focus"] : []).concat(__input7.checked ? ["checked"] : []).concat(!__input7.enabled ? ["disabled"] : [])
                            width: 36
                            height: 20
                            implicitWidth: 36
                            implicitHeight: 20
                            Item {
                                anchors.fill: parent
                                Rectangle {
                                    width: 16
                                    height: 16
                                    radius: 8
                                    color: "#ffffff"
                                    y: (parent.height - height) / 2
                                    x: __input7.visualPosition * (parent.width - width)
                                    Behavior on x { NumberAnimation { duration: 120 } }
                                    Css.CssItem { cssPrimitive: "rect"; cssClass: ["knob"] }
                                }
                            }
                        }
                        onToggled: { sw = __input7.checked }
                    }
                    Binding {
                        target: __input7
                        property: "checked"
                        value: sw
                        restoreMode: Binding.RestoreNone
                    }
                }
                Css.CssText {
                    cssClass: ["wg-check-label"]
                    cssPrimitive: "text"
                    text: "Dark mode"
                }
            }
            Css.CssRect {
                cssClass: ["wg-check-row"]
                cssPrimitive: "div"
                Css.CssFill {
                    cssClass: ["wg-checkbox"]
                    cssPrimitive: "input"
                    cssState: (__input8.activeFocus ? ["focus"] : []).concat(__input8.checked ? ["checked"] : []).concat(!__input8.enabled ? ["disabled"] : [])
                    implicitWidth: __input8.implicitWidth
                    implicitHeight: __input8.implicitHeight
                    T.CheckBox {
                        id: __input8
                        anchors.fill: parent
                        background: null
                        contentItem: null
                        activeFocusOnTab: solidTabstop.enabled
                        Keys.onDownPressed: { if (solidTabstop.enabled) { var __n = __input8.nextItemInFocusChain(true); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onRightPressed: { if (solidTabstop.enabled) { var __n = __input8.nextItemInFocusChain(true); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onUpPressed: { if (solidTabstop.enabled) { var __n = __input8.nextItemInFocusChain(false); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onLeftPressed: { if (solidTabstop.enabled) { var __n = __input8.nextItemInFocusChain(false); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        indicator: Css.CssFill {
                            cssPrimitive: "span"
                            cssClass: ["indicator"]
                            cssState: (__input8.activeFocus ? ["focus"] : []).concat(__input8.checked ? ["checked"] : []).concat(!__input8.enabled ? ["disabled"] : [])
                            width: 20
                            height: 20
                            implicitWidth: 20
                            implicitHeight: 20
                            Item {
                                anchors.fill: parent
                                Text {
                                    text: "✓"
                                    visible: __input8.checked
                                    anchors.centerIn: parent
                                    Css.CssItem { cssPrimitive: "text"; cssClass: ["indicator-glyph"] }
                                }
                            }
                        }
                        enabled: false
                    }
                }
                Css.CssText {
                    cssClass: ["wg-check-label"]
                    cssPrimitive: "text"
                    text: "Disabled checkbox"
                }
            }
            Css.CssRect {
                cssClass: ["wg-check-row"]
                cssPrimitive: "div"
                Css.CssFill {
                    cssClass: ["wg-switch"]
                    cssPrimitive: "input"
                    cssState: (__input9.activeFocus ? ["focus"] : []).concat(__input9.checked ? ["checked"] : []).concat(!__input9.enabled ? ["disabled"] : [])
                    implicitWidth: __input9.implicitWidth
                    implicitHeight: __input9.implicitHeight
                    T.Switch {
                        id: __input9
                        anchors.fill: parent
                        background: null
                        contentItem: null
                        activeFocusOnTab: solidTabstop.enabled
                        Keys.onDownPressed: { if (solidTabstop.enabled) { var __n = __input9.nextItemInFocusChain(true); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onRightPressed: { if (solidTabstop.enabled) { var __n = __input9.nextItemInFocusChain(true); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onUpPressed: { if (solidTabstop.enabled) { var __n = __input9.nextItemInFocusChain(false); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        Keys.onLeftPressed: { if (solidTabstop.enabled) { var __n = __input9.nextItemInFocusChain(false); if (__n) __n.forceActiveFocus(Qt.TabFocusReason) } }
                        indicator: Css.CssFill {
                            cssPrimitive: "span"
                            cssClass: ["track"]
                            cssState: (__input9.activeFocus ? ["focus"] : []).concat(__input9.checked ? ["checked"] : []).concat(!__input9.enabled ? ["disabled"] : [])
                            width: 36
                            height: 20
                            implicitWidth: 36
                            implicitHeight: 20
                            Item {
                                anchors.fill: parent
                                Rectangle {
                                    width: 16
                                    height: 16
                                    radius: 8
                                    color: "#ffffff"
                                    y: (parent.height - height) / 2
                                    x: __input9.visualPosition * (parent.width - width)
                                    Behavior on x { NumberAnimation { duration: 120 } }
                                    Css.CssItem { cssPrimitive: "rect"; cssClass: ["knob"] }
                                }
                            }
                        }
                        onToggled: { tabs = __input9.checked; solidTabstop.enabled = __input9.checked; }
                    }
                    Binding {
                        target: __input9
                        property: "checked"
                        value: tabs
                        restoreMode: Binding.RestoreNone
                    }
                }
                Css.CssText {
                    cssClass: ["wg-check-label"]
                    cssPrimitive: "text"
                    text: "Tab navigation (native only)"
                }
            }
            Css.CssText {
                cssClass: ["wg-sublabel"]
                cssPrimitive: "text"
                text: "Plan"
            }
            Css.CssRect {
                cssClass: ["wg-check-row"]
                cssPrimitive: "div"
                Css.CssFill {
                    cssClass: ["wg-radio"]
                    cssPrimitive: "input"
                    cssState: (__input10.activeFocus ? ["focus"] : []).concat(__input10.checked ? ["checked"] : []).concat(!__input10.enabled ? ["disabled"] : [])
                    implicitWidth: __input10.implicitWidth
                    implicitHeight: __input10.implicitHeight
                    T.RadioButton {
                        id: __input10
                        anchors.fill: parent
                        background: null
                        contentItem: null
                        activeFocusOnTab: solidTabstop.enabled
                        T.ButtonGroup.group: __group_plan
                        function __step(d) { var bs = __group_plan.buttons; var j = (bs.indexOf(__input10) + d + bs.length) % bs.length; var b = bs[j]; b.forceActiveFocus(Qt.TabFocusReason); b.checked = true; b.toggled() }
                        Keys.onDownPressed: __step(1)
                        Keys.onRightPressed: __step(1)
                        Keys.onUpPressed: __step(-1)
                        Keys.onLeftPressed: __step(-1)
                        indicator: Css.CssFill {
                            cssPrimitive: "span"
                            cssClass: ["indicator"]
                            cssState: (__input10.activeFocus ? ["focus"] : []).concat(__input10.checked ? ["checked"] : []).concat(!__input10.enabled ? ["disabled"] : [])
                            width: 20
                            height: 20
                            implicitWidth: 20
                            implicitHeight: 20
                            Item {
                                anchors.fill: parent
                                Rectangle {
                                    visible: __input10.checked
                                    anchors.centerIn: parent
                                    width: 8
                                    height: 8
                                    radius: 4
                                    color: "#2b2b2b"
                                    Css.CssItem { cssPrimitive: "rect"; cssClass: __input10.checked ? ["indicator-dot", "checked"] : ["indicator-dot"] }
                                }
                            }
                        }
                        onToggled: { plan = "free" }
                    }
                    Binding {
                        target: __input10
                        property: "checked"
                        value: plan === "free"
                        restoreMode: Binding.RestoreNone
                    }
                }
                Css.CssText {
                    cssClass: ["wg-check-label"]
                    cssPrimitive: "text"
                    text: "Free"
                }
            }
            Css.CssRect {
                cssClass: ["wg-check-row"]
                cssPrimitive: "div"
                Css.CssFill {
                    cssClass: ["wg-radio"]
                    cssPrimitive: "input"
                    cssState: (__input11.activeFocus ? ["focus"] : []).concat(__input11.checked ? ["checked"] : []).concat(!__input11.enabled ? ["disabled"] : [])
                    implicitWidth: __input11.implicitWidth
                    implicitHeight: __input11.implicitHeight
                    T.RadioButton {
                        id: __input11
                        anchors.fill: parent
                        background: null
                        contentItem: null
                        activeFocusOnTab: solidTabstop.enabled
                        T.ButtonGroup.group: __group_plan
                        function __step(d) { var bs = __group_plan.buttons; var j = (bs.indexOf(__input11) + d + bs.length) % bs.length; var b = bs[j]; b.forceActiveFocus(Qt.TabFocusReason); b.checked = true; b.toggled() }
                        Keys.onDownPressed: __step(1)
                        Keys.onRightPressed: __step(1)
                        Keys.onUpPressed: __step(-1)
                        Keys.onLeftPressed: __step(-1)
                        indicator: Css.CssFill {
                            cssPrimitive: "span"
                            cssClass: ["indicator"]
                            cssState: (__input11.activeFocus ? ["focus"] : []).concat(__input11.checked ? ["checked"] : []).concat(!__input11.enabled ? ["disabled"] : [])
                            width: 20
                            height: 20
                            implicitWidth: 20
                            implicitHeight: 20
                            Item {
                                anchors.fill: parent
                                Rectangle {
                                    visible: __input11.checked
                                    anchors.centerIn: parent
                                    width: 8
                                    height: 8
                                    radius: 4
                                    color: "#2b2b2b"
                                    Css.CssItem { cssPrimitive: "rect"; cssClass: __input11.checked ? ["indicator-dot", "checked"] : ["indicator-dot"] }
                                }
                            }
                        }
                        onToggled: { plan = "pro" }
                    }
                    Binding {
                        target: __input11
                        property: "checked"
                        value: plan === "pro"
                        restoreMode: Binding.RestoreNone
                    }
                }
                Css.CssText {
                    cssClass: ["wg-check-label"]
                    cssPrimitive: "text"
                    text: "Pro"
                }
            }
            Css.CssRect {
                cssClass: ["wg-check-row"]
                cssPrimitive: "div"
                Css.CssFill {
                    cssClass: ["wg-radio"]
                    cssPrimitive: "input"
                    cssState: (__input12.activeFocus ? ["focus"] : []).concat(__input12.checked ? ["checked"] : []).concat(!__input12.enabled ? ["disabled"] : [])
                    implicitWidth: __input12.implicitWidth
                    implicitHeight: __input12.implicitHeight
                    T.RadioButton {
                        id: __input12
                        anchors.fill: parent
                        background: null
                        contentItem: null
                        activeFocusOnTab: solidTabstop.enabled
                        T.ButtonGroup.group: __group_plan
                        function __step(d) { var bs = __group_plan.buttons; var j = (bs.indexOf(__input12) + d + bs.length) % bs.length; var b = bs[j]; b.forceActiveFocus(Qt.TabFocusReason); b.checked = true; b.toggled() }
                        Keys.onDownPressed: __step(1)
                        Keys.onRightPressed: __step(1)
                        Keys.onUpPressed: __step(-1)
                        Keys.onLeftPressed: __step(-1)
                        indicator: Css.CssFill {
                            cssPrimitive: "span"
                            cssClass: ["indicator"]
                            cssState: (__input12.activeFocus ? ["focus"] : []).concat(__input12.checked ? ["checked"] : []).concat(!__input12.enabled ? ["disabled"] : [])
                            width: 20
                            height: 20
                            implicitWidth: 20
                            implicitHeight: 20
                            Item {
                                anchors.fill: parent
                                Rectangle {
                                    visible: __input12.checked
                                    anchors.centerIn: parent
                                    width: 8
                                    height: 8
                                    radius: 4
                                    color: "#2b2b2b"
                                    Css.CssItem { cssPrimitive: "rect"; cssClass: __input12.checked ? ["indicator-dot", "checked"] : ["indicator-dot"] }
                                }
                            }
                        }
                        onToggled: { plan = "team" }
                    }
                    Binding {
                        target: __input12
                        property: "checked"
                        value: plan === "team"
                        restoreMode: Binding.RestoreNone
                    }
                }
                Css.CssText {
                    cssClass: ["wg-check-label"]
                    cssPrimitive: "text"
                    text: "Team"
                }
            }
        }
    }
    Css.CssRect {
        cssClass: ["wg-cols"]
        cssPrimitive: "div"
        Css.CssRect {
            cssClass: ["wg-section"]
            cssPrimitive: "div"
            Css.CssText {
                cssClass: ["wg-title"]
                cssPrimitive: "text"
                text: "Pickers"
            }
            Css.CssRect {
                cssClass: ["wg-field"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-label"]
                    cssPrimitive: "text"
                    text: "Fruit"
                }
                Css.CssFill {
                    cssClass: ["wg-select"]
                    cssPrimitive: "select"
                    cssState: (__input13.activeFocus ? ["focus"] : []).concat(!__input13.enabled ? ["disabled"] : [])
                    implicitWidth: __input13.implicitWidth
                    implicitHeight: __input13.implicitHeight
                    T.ComboBox {
                        id: __input13
                        anchors.fill: parent
                        activeFocusOnTab: solidTabstop.enabled
                        Window.onActiveChanged: if (!Window.active) __input13.popup.close()
                        background: null
                        leftPadding: 12
                        readonly property var __values: ["apple", "banana", "cherry", "mango"]
                        model: ["Apple", "Banana", "Cherry", "Mango"]
                        contentItem: Css.CssText {
                            cssPrimitive: ""
                            cssClass: ["value"]
                            text: __input13.displayText
                        }
                        Css.CssText {
                            cssPrimitive: ""
                            cssClass: ["chevron"]
                            text: "▾"
                            anchors.right: parent.right
                            anchors.rightMargin: 8
                            anchors.verticalCenter: parent.verticalCenter
                        }
                        delegate: T.ItemDelegate {
                            id: __optDel13
                            highlighted: __input13.highlightedIndex === index
                            width: __input13.popup.width
                            implicitHeight: 36
                            background: Css.CssFill {
                                cssPrimitive: "div"
                                cssClass: ["option"]
                                cssState: (__optDel13.highlighted ? ["hover"] : []).concat(__input13.currentIndex === index ? ["selected"] : [])
                            }
                            contentItem: Css.CssText {
                                cssPrimitive: ""
                                cssClass: ["option-label"]
                                text: modelData
                            }
                        }
                        popup: T.Popup {
                            popupType: T.Popup.Window
                            y: (__input13.mapToGlobal(0, __input13.height + 2).y + height > Screen.height) ? -(height + 2) : __input13.height + 2
                            width: __input13.width
                            implicitHeight: contentHeight + topPadding + bottomPadding
                            padding: 1
                            background: Css.CssFill {
                                property Item cssAncestor: __input13
                                cssPrimitive: "div"
                                cssClass: ["popup"]
                            }
                            contentItem: ListView {
                                property Item cssAncestor: __input13
                                clip: true
                                model: __input13.delegateModel
                                currentIndex: __input13.highlightedIndex
                                implicitHeight: Math.min(contentHeight, 240)
                            }
                        }
                        onActivated: (index) => { fruit = __input13.__values[index] }
                    }
                    Binding {
                        target: __input13
                        property: "currentIndex"
                        value: __input13.__values.indexOf(fruit)
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
            Css.CssRect {
                cssClass: ["wg-field"]
                cssPrimitive: "div"
                Css.CssRect {
                    cssClass: ["wg-range-header"]
                    cssPrimitive: "div"
                    Css.CssText {
                        cssClass: ["wg-label"]
                        cssPrimitive: "text"
                        text: "Volume"
                    }
                    Css.CssText {
                        cssClass: ["wg-range-val"]
                        cssPrimitive: "text"
                        text: "" + (volume)
                    }
                }
                Css.CssFill {
                    cssClass: ["wg-range"]
                    cssPrimitive: "input"
                    cssState: (__input14.activeFocus ? ["focus"] : []).concat(!__input14.enabled ? ["disabled"] : [])
                    implicitWidth: __input14.implicitWidth
                    implicitHeight: __input14.implicitHeight
                    T.Slider {
                        id: __input14
                        anchors.fill: parent
                        activeFocusOnTab: solidTabstop.enabled
                        background: Css.CssFill {
                            cssPrimitive: ""
                            cssClass: ["track"]
                            x: __input14.leftPadding
                            y: __input14.topPadding + (__input14.availableHeight - height) / 2
                            width: __input14.availableWidth
                            height: 6
                            implicitHeight: 6
                            Css.CssRect {
                                cssClass: ["track-fill"]
                                width: __input14.visualPosition * parent.width
                                height: parent.height
                            }
                        }
                        handle: Css.CssRect {
                            cssClass: ["handle"]
                            width: 18
                            height: 18
                            implicitWidth: 18
                            implicitHeight: 18
                            x: __input14.leftPadding + __input14.visualPosition * (__input14.availableWidth - width)
                            y: __input14.topPadding + __input14.availableHeight / 2 - height / 2
                        }
                        from: 0
                        to: 100
                        stepSize: 1
                        WheelHandler {
                            property real __acc: 0
                            enabled: __input14.activeFocus
                            acceptedDevices: PointerDevice.Mouse | PointerDevice.TouchPad
                            onWheel: (ev) => { __acc += ev.angleDelta.y !== 0 ? ev.angleDelta.y : ev.pixelDelta.y * 8; var s = 0; while (__acc >= 120) { __acc -= 120; s++ } while (__acc <= -120) { __acc += 120; s-- } if (s !== 0) { __input14.value = Math.max(__input14.from, Math.min(__input14.to, __input14.value + s * __input14.stepSize)); __input14.moved() } }
                        }
                        onMoved: { volume = __input14.value }
                    }
                    Binding {
                        target: __input14
                        property: "value"
                        value: volume
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
            Css.CssRect {
                cssClass: ["wg-field"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-label"]
                    cssPrimitive: "text"
                    text: "Quantity"
                }
                Css.CssFill {
                    cssClass: ["wg-number"]
                    cssPrimitive: "input"
                    cssState: (__input15.activeFocus ? ["focus"] : []).concat(!__input15.enabled ? ["disabled"] : [])
                    implicitWidth: __input15.implicitWidth
                    implicitHeight: __input15.implicitHeight
                    T.SpinBox {
                        id: __input15
                        anchors.fill: parent
                        background: null
                        from: 1
                        to: 10
                        stepSize: 1
                        editable: true
                        activeFocusOnTab: solidTabstop.enabled
                        leftPadding: 12
                        rightPadding: 32
                        WheelHandler {
                            property real __acc: 0
                            enabled: __input15.activeFocus
                            acceptedDevices: PointerDevice.Mouse | PointerDevice.TouchPad
                            onWheel: (ev) => { __acc += ev.angleDelta.y !== 0 ? ev.angleDelta.y : ev.pixelDelta.y * 8; var s = 0; while (__acc >= 120) { __acc -= 120; s++ } while (__acc <= -120) { __acc += 120; s-- } if (s !== 0) { __input15.value = Math.max(__input15.from, Math.min(__input15.to, __input15.value + s * __input15.stepSize)); __input15.valueModified() } }
                        }
                        contentItem: TextInput {
                            focus: true
                            text: __input15.displayText
                            validator: __input15.validator
                            readOnly: !__input15.editable
                            color: cssTheme.parseColor(__input15.parent.inheritedColor || "#2b2b2b")
                            font.family: cssTheme.resolveFontFamily(__input15.parent.inheritedFontFamily || "Sans Serif")
                            font.pixelSize: cssTheme.parseFontSize(__input15.parent.inheritedFontSize || "13px", 13)
                            horizontalAlignment: Qt.AlignHCenter
                            verticalAlignment: Qt.AlignVCenter
                            selectByMouse: true
                        }
                        up.indicator: Css.CssFill {
                            cssPrimitive: ""
                            cssClass: ["spin-up"]
                            cssState: __input15.up.pressed ? ["active"] : []
                            x: parent.width - width - 2
                            y: 2
                            width: 24
                            height: (parent.height - 4) / 2
                            implicitWidth: 24
                            implicitHeight: (parent.height - 4) / 2
                            Item {
                                anchors.fill: parent
                                Text {
                                    text: "+"
                                    anchors.centerIn: parent
                                    Css.CssItem { cssPrimitive: "text"; cssClass: ["spin-glyph"] }
                                }
                            }
                        }
                        down.indicator: Css.CssFill {
                            cssPrimitive: ""
                            cssClass: ["spin-down"]
                            cssState: __input15.down.pressed ? ["active"] : []
                            x: parent.width - width - 2
                            y: parent.height / 2
                            width: 24
                            height: (parent.height - 4) / 2
                            implicitWidth: 24
                            implicitHeight: (parent.height - 4) / 2
                            Item {
                                anchors.fill: parent
                                Text {
                                    text: "−"
                                    anchors.centerIn: parent
                                    Css.CssItem { cssPrimitive: "text"; cssClass: ["spin-glyph"] }
                                }
                            }
                        }
                        onValueModified: { qty = __input15.value }
                    }
                    Binding {
                        target: __input15
                        property: "value"
                        value: qty
                        restoreMode: Binding.RestoreNone
                    }
                }
            }
            Css.CssRect {
                cssClass: ["wg-field"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-label"]
                    cssPrimitive: "text"
                    text: "Date"
                }
                Css.CssFill {
                    cssClass: ["wg-date"]
                    id: __input16W
                    cssPrimitive: "input"
                    cssState: (__input16P.visible ? ["focus"] : []).concat(!__input16.enabled ? ["disabled"] : [])
                    implicitWidth: 200
                    implicitHeight: 36
                    property var __calVal16: inputDate
                    property int __calMonth16: __calVal16 instanceof Date ? __calVal16.getMonth() : new Date().getMonth()
                    property int __calYear16: __calVal16 instanceof Date ? __calVal16.getFullYear() : new Date().getFullYear()
                    Window.onActiveChanged: if (!Window.active) __input16P.close()
                    property var __calCursor16: null
                    function __calStep16(days) { var b = __calCursor16 instanceof Date ? __calCursor16 : (__calVal16 instanceof Date ? __calVal16 : new Date()); var d = new Date(b.getFullYear(), b.getMonth(), b.getDate() + days); __calCursor16 = d; __calMonth16 = d.getMonth(); __calYear16 = d.getFullYear() }
                    function __calCommit16() { if (!(__calCursor16 instanceof Date)) return; inputDate = __calCursor16; __input16P.close() }
                    Item {
                        anchors.fill: parent
                        T.TextField {
                            id: __input16
                            anchors.fill: parent
                            background: null
                            readOnly: true
                            activeFocusOnTab: solidTabstop.enabled
                            Keys.onReturnPressed: __input16P.visible ? __input16W.__calCommit16() : __input16P.open()
                            Keys.onSpacePressed: __input16P.visible ? __input16W.__calCommit16() : __input16P.open()
                            Keys.onDownPressed: __input16P.visible ? __input16W.__calStep16(7) : __input16P.open()
                            Keys.onUpPressed: { if (__input16P.visible) __input16W.__calStep16(-7) }
                            Keys.onLeftPressed: { if (__input16P.visible) __input16W.__calStep16(-1) }
                            Keys.onRightPressed: { if (__input16P.visible) __input16W.__calStep16(1) }
                            color: cssTheme.parseColor(__input16W.inheritedColor || "#2b2b2b")
                            font.family: cssTheme.resolveFontFamily(__input16W.inheritedFontFamily || "Sans Serif")
                            font.pixelSize: cssTheme.parseFontSize(__input16W.inheritedFontSize || "13px", 13)
                            leftPadding: 12
                            rightPadding: 36
                            verticalAlignment: TextInput.AlignVCenter
                        }
                        Binding {
                            target: __input16
                            property: "text"
                            value: __input16W.__calVal16 instanceof Date ? Qt.formatDate(__input16W.__calVal16, "yyyy-MM-dd") : ""
                            restoreMode: Binding.RestoreNone
                        }
                        Css.CssText {
                            cssPrimitive: ""
                            cssClass: ["chevron"]
                            text: "▾"
                            anchors.right: parent.right
                            anchors.rightMargin: 8
                            anchors.verticalCenter: parent.verticalCenter
                        }
                        MouseArea {
                            anchors.fill: parent
                            onClicked: { __input16.forceActiveFocus(); if (__input16P.visible) __input16P.close(); else if (Date.now() - __input16P.__closedAt > 150) __input16P.open() }
                        }
                    }
                    T.Popup {
                        id: __input16P
                        property double __closedAt: 0
                        onOpened: __input16W.__calCursor16 = __input16W.__calVal16 instanceof Date ? __input16W.__calVal16 : new Date()
                        onClosed: { __closedAt = Date.now(); __input16W.__calCursor16 = null }
                        popupType: T.Popup.Window
                        y: (__input16W.mapToGlobal(0, __input16W.height + 2).y + height > Screen.height) ? -(height + 2) : __input16W.height + 2
                        implicitWidth: contentWidth + leftPadding + rightPadding
                        implicitHeight: contentHeight + topPadding + bottomPadding
                        padding: 1
                        background: Css.CssFill {
                            property Item cssAncestor: __input16W
                            cssPrimitive: "div"
                            cssClass: ["popup"]
                        }
                        contentItem: Item {
                            property Item cssAncestor: __input16W
                            implicitWidth: 224
                            implicitHeight: 280
                            Css.CssFill {
                                cssPrimitive: "button"
                                cssClass: ["cal-nav"]
                                x: 0
                                y: 0
                                width: 32
                                height: 32
                                implicitWidth: 32
                                implicitHeight: 32
                                Css.CssText { cssPrimitive: ""; text: "‹"; anchors.centerIn: parent }
                                MouseArea {
                                    anchors.fill: parent
                                    onClicked: {
                                        if (__input16W.__calMonth16 === 0) { __input16W.__calYear16 = __input16W.__calYear16 - 1; __input16W.__calMonth16 = 11 }
                                        else __input16W.__calMonth16 = __input16W.__calMonth16 - 1
                                    }
                                }
                            }
                            Css.CssText {
                                cssPrimitive: ""
                                cssClass: ["cal-title"]
                                x: 32
                                y: 0
                                width: parent.width - 64
                                height: 32
                                text: Qt.locale().monthName(__input16W.__calMonth16) + " " + __input16W.__calYear16
                                style: ({"text-align": "center"})
                            }
                            Css.CssFill {
                                cssPrimitive: "button"
                                cssClass: ["cal-nav"]
                                x: parent.width - 32
                                y: 0
                                width: 32
                                height: 32
                                implicitWidth: 32
                                implicitHeight: 32
                                Css.CssText { cssPrimitive: ""; text: "›"; anchors.centerIn: parent }
                                MouseArea {
                                    anchors.fill: parent
                                    onClicked: {
                                        if (__input16W.__calMonth16 === 11) { __input16W.__calYear16 = __input16W.__calYear16 + 1; __input16W.__calMonth16 = 0 }
                                        else __input16W.__calMonth16 = __input16W.__calMonth16 + 1
                                    }
                                }
                            }
                            T.AbstractDayOfWeekRow {
                                id: __dow16
                                x: 0
                                y: 32
                                width: parent.width
                                height: 24
                                contentItem: Row {
                                    Repeater {
                                        model: __dow16.source
                                        delegate: __dow16.delegate
                                    }
                                }
                                delegate: Item {
                                    width: (__dow16.contentItem.width - 6 * __dow16.spacing) / 7
                                    height: __dow16.contentItem.height
                                    Css.CssText {
                                        cssPrimitive: ""
                                        cssClass: ["dow"]
                                        text: model.shortName
                                        anchors.centerIn: parent
                                    }
                                }
                            }
                            T.AbstractMonthGrid {
                                id: __mg16
                                x: 0
                                y: 56
                                width: parent.width
                                height: parent.height - 56
                                month: __input16W.__calMonth16
                                year: __input16W.__calYear16
                                contentItem: Grid {
                                    columns: 7
                                    rows: 6
                                    Repeater {
                                        model: __mg16.source
                                        delegate: __mg16.delegate
                                    }
                                }
                                delegate: T.AbstractButton {
                                    id: __mgDel16
                                    implicitWidth: 32
                                    implicitHeight: 32
                                    width: (__mg16.contentItem.width - 6 * __mg16.spacing) / 7
                                    height: (__mg16.contentItem.height - 5 * __mg16.spacing) / 6
                                    background: Css.CssFill {
                                        cssPrimitive: "div"
                                        cssClass: ["day"]
                                        cssState: (model.today ? ["today"] : []).concat((__input16W.__calVal16 instanceof Date && model.year === __input16W.__calVal16.getFullYear() && model.month === __input16W.__calVal16.getMonth() && model.day === __input16W.__calVal16.getDate()) ? ["selected"] : []).concat(model.month !== __mg16.month ? ["outside"] : []).concat(__mgDel16.hovered ? ["hover"] : []).concat((__input16W.__calCursor16 instanceof Date && model.year === __input16W.__calCursor16.getFullYear() && model.month === __input16W.__calCursor16.getMonth() && model.day === __input16W.__calCursor16.getDate()) ? ["focus"] : [])
                                    }
                                    contentItem: Css.CssText {
                                        cssPrimitive: ""
                                        cssClass: ["day-label"]
                                        cssState: (model.today ? ["today"] : []).concat((__input16W.__calVal16 instanceof Date && model.year === __input16W.__calVal16.getFullYear() && model.month === __input16W.__calVal16.getMonth() && model.day === __input16W.__calVal16.getDate()) ? ["selected"] : []).concat(model.month !== __mg16.month ? ["outside"] : []).concat(__mgDel16.hovered ? ["hover"] : []).concat((__input16W.__calCursor16 instanceof Date && model.year === __input16W.__calCursor16.getFullYear() && model.month === __input16W.__calCursor16.getMonth() && model.day === __input16W.__calCursor16.getDate()) ? ["focus"] : [])
                                        text: model.day
                                    }
                                    onClicked: { inputDate = new Date(model.year, model.month, model.day); __input16P.close() }
                                }
                            }
                        }
                    }
                }
            }
        }
        Css.CssRect {
            cssClass: ["wg-section", "wg-cal-section"]
            cssPrimitive: "div"
            Css.CssText {
                cssClass: ["wg-title"]
                cssPrimitive: "text"
                text: "Calendar"
            }
            Css.CssFill {
                cssClass: ["wg-cal"]
                id: __cal17
                cssPrimitive: "div"
                implicitWidth: 224
                implicitHeight: 280
                property var __calVal17: calDate
                property int __calMonth17: __calVal17 instanceof Date ? __calVal17.getMonth() : new Date().getMonth()
                property int __calYear17: __calVal17 instanceof Date ? __calVal17.getFullYear() : new Date().getFullYear()
                Item {
                    anchors.fill: parent
                    Css.CssFill {
                        cssPrimitive: "button"
                        cssClass: ["cal-nav"]
                        x: 0
                        y: 0
                        width: 32
                        height: 32
                        implicitWidth: 32
                        implicitHeight: 32
                        Css.CssText { cssPrimitive: ""; text: "‹"; anchors.centerIn: parent }
                        MouseArea {
                            anchors.fill: parent
                            onClicked: {
                                if (__cal17.__calMonth17 === 0) { __cal17.__calYear17 = __cal17.__calYear17 - 1; __cal17.__calMonth17 = 11 }
                                else __cal17.__calMonth17 = __cal17.__calMonth17 - 1
                            }
                        }
                    }
                    Css.CssText {
                        cssPrimitive: ""
                        cssClass: ["cal-title"]
                        x: 32
                        y: 0
                        width: parent.width - 64
                        height: 32
                        text: Qt.locale().monthName(__cal17.__calMonth17) + " " + __cal17.__calYear17
                        style: ({"text-align": "center"})
                    }
                    Css.CssFill {
                        cssPrimitive: "button"
                        cssClass: ["cal-nav"]
                        x: parent.width - 32
                        y: 0
                        width: 32
                        height: 32
                        implicitWidth: 32
                        implicitHeight: 32
                        Css.CssText { cssPrimitive: ""; text: "›"; anchors.centerIn: parent }
                        MouseArea {
                            anchors.fill: parent
                            onClicked: {
                                if (__cal17.__calMonth17 === 11) { __cal17.__calYear17 = __cal17.__calYear17 + 1; __cal17.__calMonth17 = 0 }
                                else __cal17.__calMonth17 = __cal17.__calMonth17 + 1
                            }
                        }
                    }
                    T.AbstractDayOfWeekRow {
                        id: __dow17
                        x: 0
                        y: 32
                        width: parent.width
                        height: 24
                        contentItem: Row {
                            Repeater {
                                model: __dow17.source
                                delegate: __dow17.delegate
                            }
                        }
                        delegate: Item {
                            width: (__dow17.contentItem.width - 6 * __dow17.spacing) / 7
                            height: __dow17.contentItem.height
                            Css.CssText {
                                cssPrimitive: ""
                                cssClass: ["dow"]
                                text: model.shortName
                                anchors.centerIn: parent
                            }
                        }
                    }
                    T.AbstractMonthGrid {
                        id: __mg17
                        x: 0
                        y: 56
                        width: parent.width
                        height: parent.height - 56
                        month: __cal17.__calMonth17
                        year: __cal17.__calYear17
                        contentItem: Grid {
                            columns: 7
                            rows: 6
                            Repeater {
                                model: __mg17.source
                                delegate: __mg17.delegate
                            }
                        }
                        delegate: T.AbstractButton {
                            id: __mgDel17
                            implicitWidth: 32
                            implicitHeight: 32
                            width: (__mg17.contentItem.width - 6 * __mg17.spacing) / 7
                            height: (__mg17.contentItem.height - 5 * __mg17.spacing) / 6
                            background: Css.CssFill {
                                cssPrimitive: "div"
                                cssClass: ["day"]
                                cssState: (model.today ? ["today"] : []).concat((__cal17.__calVal17 instanceof Date && model.year === __cal17.__calVal17.getFullYear() && model.month === __cal17.__calVal17.getMonth() && model.day === __cal17.__calVal17.getDate()) ? ["selected"] : []).concat(model.month !== __mg17.month ? ["outside"] : []).concat(__mgDel17.hovered ? ["hover"] : [])
                            }
                            contentItem: Css.CssText {
                                cssPrimitive: ""
                                cssClass: ["day-label"]
                                cssState: (model.today ? ["today"] : []).concat((__cal17.__calVal17 instanceof Date && model.year === __cal17.__calVal17.getFullYear() && model.month === __cal17.__calVal17.getMonth() && model.day === __cal17.__calVal17.getDate()) ? ["selected"] : []).concat(model.month !== __mg17.month ? ["outside"] : []).concat(__mgDel17.hovered ? ["hover"] : [])
                                text: model.day
                            }
                            onClicked: { calDate = new Date(model.year, model.month, model.day) }
                        }
                    }
                }
            }
        }
    }
    Css.CssRect {
        cssClass: ["wg-summary"]
        cssPrimitive: "div"
        Css.CssText {
            cssClass: ["wg-title"]
            cssPrimitive: "text"
            text: "Form state"
        }
        Css.CssRect {
            cssClass: ["wg-kv-grid"]
            cssPrimitive: "div"
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "name"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (inputName)
                }
            }
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "pass"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (inputPass ? "set" : "—")
                }
            }
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "search"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (inputSearch)
                }
            }
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "notes"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (inputNotes ? "set" : "—")
                }
            }
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "check1"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (chk1 ? "on" : "off")
                }
            }
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "check2"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (chk2 ? "on" : "off")
                }
            }
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "switch"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (sw ? "on" : "off")
                }
            }
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "plan"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (plan)
                }
            }
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "fruit"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (fruit)
                }
            }
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "volume"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (volume)
                }
            }
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "qty"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (qty)
                }
            }
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "date"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (inputDate ? "selected" : "—")
                }
            }
            Css.CssRect {
                cssClass: ["wg-kv-row"]
                cssPrimitive: "div"
                Css.CssText {
                    cssClass: ["wg-kv"]
                    cssPrimitive: "text"
                    text: "cal"
                }
                Css.CssText {
                    cssClass: ["wg-kv-v"]
                    cssPrimitive: "text"
                    text: "" + (calDate ? "selected" : "—")
                }
            }
        }
        Css.CssFill {
            cssClass: ["wg-reset"]
            cssState: __hover0.containsMouse ? ["hover"] : []
            cssPrimitive: "button"
            Css.CssText {
                cssPrimitive: "text"
                text: "Reset"
            }
            MouseArea {
                id: __hover0
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: reset()
            }
        }
    }
}
