// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
Window {
    id: __self
    visible: true
    width: 1000
    height: 640
    title: "solidterm"
    Shortcut {
        sequences: ["Ctrl+Tab"]
        enabled: solidTabstop.enabled
        onActivated: { var __it = __self.activeFocusItem || __self.contentItem; var __nx = __it.nextItemInFocusChain(true); if (__nx) __nx.forceActiveFocus(Qt.TabFocusReason) }
    }
    Shortcut {
        sequences: ["Ctrl+Shift+Tab", "Ctrl+Backtab"]
        enabled: solidTabstop.enabled
        onActivated: { var __it = __self.activeFocusItem || __self.contentItem; var __nx = __it.nextItemInFocusChain(false); if (__nx) __nx.forceActiveFocus(Qt.BacktabFocusReason) }
    }
    Css.CssRect {
        anchors.fill: parent
        cssClass: ["qml-window"]
        cssPrimitive: "window"
        Term {
        }
    }
    W.Tabstop { window: __self }
    Component.onCompleted: if (solidTabstop.enabled) Qt.callLater(function() { var f = __self.contentItem.nextItemInFocusChain(true); if (f) f.forceActiveFocus(Qt.TabFocusReason) })

    Timer {
        running: true; interval: 1200; repeat: false
        onTriggered: {
            function find(w, name) {
                var stack = [w];
                while (stack.length) {
                    var it = stack.pop();
                    for (var i = 0; i < it.children.length; i++) {
                        var c = it.children[i];
                        if (c.toString().indexOf(name) === 0) return c;
                        stack.push(c);
                    }
                }
                return null;
            }
            var t = find(contentItem, "TerminalView");
            console.log("PROBE term found=" + (t !== null) + " title='" + (t ? t.title : "?") + "'");
            t.sendText("echo SOLIDTERM_$((21+21))_OK\n");
        }
    }
}
