// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import SolidTerm 1.0 as QM_SolidTerm

import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var title: "solidterm"
    property var state_: "live"
    cssClass: ["term-root"]
    W.Div {
        cssClass: ["term-header"]
        W.Text {
            cssClass: ["term-title"]
            text: "" + (title)
        }
        W.Text {
            cssClass: ["term-badge"]
            text: "v0.1 — pane 1"
        }
    }
    W.Div {
        cssClass: ["term-body"]
        Css.CssRect {
            cssPrimitive: "div"
            cssClass: ["term-pane"]
            QM_SolidTerm.TerminalView {
                anchors.fill: parent
                onTitleChanged: function() { return 0 }
                onSessionFinished: function() { return state_ = "shell exited" }
            }
        }
    }
    W.Div {
        cssClass: ["term-status"]
        W.Text {
            cssClass: ["term-status-t"]
            text: "" + (state_)
        }
        W.Text {
            cssClass: ["term-hint"]
            text: "Ctrl+Shift+V paste · wheel scrollback"
        }
    }
}
