// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import SolidTerm 1.0 as QM_SolidTerm

import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var uiFontFamily: termConfig.getString("fontFamily", "monospace")
    property var uiFontSize: termConfig.getInt("fontSize", 15)
    property var scheme: termConfig.getString("scheme", "system")
    property var scrollback: termConfig.getInt("scrollback", 8000)
    property var cfgOpen: false
    property var title: "solidterm"
    property var kSplitRight: termConfig.getString("keys.splitRight", "Ctrl+Shift+E")
    property var kSplitDown: termConfig.getString("keys.splitDown", "Ctrl+Shift+O")
    property var kClosePane: termConfig.getString("keys.closePane", "Ctrl+Shift+W")
    property var kFocusNext: termConfig.getString("keys.focusNext", "Alt+Right")
    property var kFocusPrev: termConfig.getString("keys.focusPrev", "Alt+Left")
    readonly property var __const_SCHEMES: ({ midnight: ({ bg: "#161a21", fg: "#d4dae3" }), solarized: ({ bg: "#002b36", fg: "#93a1a1" }), gruvbox: ({ bg: "#282828", fg: "#ebdbb2" }), paper: ({ bg: "#f7f2e9", fg: "#3a3532" }) })
    readonly property var __const_ACTIONS: [({ key: "splitRight", label: "Split right", def: "Ctrl+Shift+E" }), ({ key: "splitDown", label: "Split down", def: "Ctrl+Shift+O" }), ({ key: "closePane", label: "Close pane", def: "Ctrl+Shift+W" }), ({ key: "focusNext", label: "Focus next pane", def: "Alt+Right" }), ({ key: "focusPrev", label: "Focus previous pane", def: "Alt+Left" })]
    function getKey(k) { return k === "splitRight" ? kSplitRight : k === "splitDown" ? kSplitDown : k === "closePane" ? kClosePane : k === "focusNext" ? kFocusNext : k === "focusPrev" ? kFocusPrev : termConfig.getString("keys." + k, ""); }
    function onAccel(seq) { if (seq === kSplitRight) { _ref_term.split(Qt.Horizontal); } else { if (seq === kSplitDown) { _ref_term.split(Qt.Vertical); } else { if (seq === kClosePane) { _ref_term.closeFocused(); } else { if (seq === kFocusNext) { _ref_term.focusNext(); } else { if (seq === kFocusPrev) { _ref_term.focusPrev(); } } } } } }
    function setKey(k, seq) { termConfig.set("keys." + k, seq); if (k === "splitRight") { kSplitRight = seq; } else { if (k === "splitDown") { kSplitDown = seq; } else { if (k === "closePane") { kClosePane = seq; } else { if (k === "focusNext") { kFocusNext = seq; } else { if (k === "focusPrev") { kFocusPrev = seq; } } } } } }
    cssClass: ["term-root"]
    W.Div {
        cssClass: ["term-header"]
        W.Text {
            cssClass: ["term-title"]
            text: "" + (title)
        }
        W.Button {
            cssClass: ["term-gear"]
            text: "⚙"
            onClicked: cfgOpen = true
        }
    }
    W.Div {
        cssClass: ["term-body"]
        Css.CssRect {
            cssPrimitive: "div"
            cssClass: ["term-pane"]
            QM_SolidTerm.TerminalPanes {
                id: _ref_term
                anchors.fill: parent
                fontFamily: uiFontFamily
                fontSize: uiFontSize
                background: scheme === "system" ? sysTheme.base : (__const_SCHEMES[scheme] || __const_SCHEMES.midnight).bg
                foreground: scheme === "system" ? sysTheme.text : (__const_SCHEMES[scheme] || __const_SCHEMES.midnight).fg
                scrollbackLimit: scrollback
                handleColor: sysTheme.window
                reservedSequences: [kSplitRight, kSplitDown, kClosePane, kFocusNext, kFocusPrev]
                onAccelerator: function(seq) { return onAccel(seq) }
                onTitleChanged: function(t) { return title = t }
                onAllClosed: function() { return process.exit(0) }
            }
        }
        Item {
            id: __menuHost0
            anchors.fill: parent
            Window.onActiveChanged: if (!Window.active) __menu0.close()
            MouseArea {
                anchors.fill: parent
                acceptedButtons: Qt.RightButton
                onClicked: function(mouse) { __menu0.popup(mouse.x, mouse.y) }
            }
            W.Menu {
                id: __menu0
                cssAncestor: __menuHost0
                authorClass: ["tmenu"]
                W.MenuItem {
                    text: "&Copy"
                    onTriggered: { _ref_term.copyFocused() }
                }
                W.MenuItem {
                    text: "&Paste"
                    onTriggered: { _ref_term.pasteFocused() }
                }
                W.MenuSeparator { }
                W.MenuItem {
                    text: "Split &right"
                    onTriggered: { _ref_term.split(Qt.Horizontal) }
                }
                W.MenuItem {
                    text: "Split &down"
                    onTriggered: { _ref_term.split(Qt.Vertical) }
                }
                W.MenuItem {
                    text: "Close &pane"
                    onTriggered: { _ref_term.closeFocused() }
                }
                W.MenuSeparator { }
                W.MenuItem {
                    text: "Clear scrollback"
                    onTriggered: { _ref_term.clearFocused() }
                }
                W.MenuItem {
                    text: "Pre&ferences…"
                    onTriggered: { cfgOpen = true }
                }
            }
        }
    }
    W.Div {
        cssClass: ["term-status"]
        W.Text {
            cssClass: ["term-status-t"]
            text: "solidterm"
        }
        W.Text {
            cssClass: ["term-hint"]
            text: "right-click for actions · shortcuts in Preferences"
        }
    }
    W.Dialog {
        open: !!(cfgOpen)
        title: "Preferences"
        cssClass: ["cfg"]
        onDialogClosed: { cfgOpen = false }
        W.Div {
            cssClass: ["cfg-body"]
            W.Text {
                cssClass: ["cfg-group"]
                text: "Appearance"
            }
            W.Div {
                cssClass: ["cfg-card"]
                W.Div {
                    cssClass: ["cfg-row"]
                    W.Text {
                        cssClass: ["cfg-l"]
                        text: "Font family"
                    }
                    W.TextField {
                        id: __input2
                        cssClass: ["cfg-in"]
                        onTextEdited: { uiFontFamily = text; termConfig.set("fontFamily", text); }
                        Binding {
                            target: __input2
                            property: "text"
                            value: uiFontFamily
                            restoreMode: Binding.RestoreNone
                        }
                    }
                }
                W.Div {
                    cssClass: ["cfg-div"]
                    cssPrimitive: "hr"
                }
                W.Div {
                    cssClass: ["cfg-row"]
                    W.Text {
                        cssClass: ["cfg-l"]
                        text: "Font size"
                    }
                    W.Select {
                        id: __input3
                        cssClass: ["cfg-sel"]
                        model: ["11 px", "12 px", "13 px", "14 px", "15 px", "16 px", "18 px", "20 px", "24 px"]
                        values: ["11", "12", "13", "14", "15", "16", "18", "20", "24"]
                        onActivated: (index) => { uiFontSize = parseInt(__input3.values[index]); termConfig.set("fontSize", parseInt(__input3.values[index])); }
                        Binding {
                            target: __input3
                            property: "currentIndex"
                            value: __input3.values.indexOf("" + uiFontSize)
                            restoreMode: Binding.RestoreNone
                        }
                    }
                }
                W.Div {
                    cssClass: ["cfg-div"]
                    cssPrimitive: "hr"
                }
                W.Div {
                    cssClass: ["cfg-row"]
                    W.Text {
                        cssClass: ["cfg-l"]
                        text: "Color scheme"
                    }
                    W.Select {
                        id: __input4
                        cssClass: ["cfg-sel"]
                        model: ["System", "Midnight", "Solarized Dark", "Gruvbox", "Paper (light)"]
                        values: ["system", "midnight", "solarized", "gruvbox", "paper"]
                        onActivated: (index) => { scheme = __input4.values[index]; termConfig.set("scheme", __input4.values[index]); }
                        Binding {
                            target: __input4
                            property: "currentIndex"
                            value: __input4.values.indexOf(scheme)
                            restoreMode: Binding.RestoreNone
                        }
                    }
                }
            }
            W.Text {
                cssClass: ["cfg-group"]
                text: "Behavior"
            }
            W.Div {
                cssClass: ["cfg-card"]
                W.Div {
                    cssClass: ["cfg-row"]
                    W.Text {
                        cssClass: ["cfg-l"]
                        text: "Scrollback"
                    }
                    W.Select {
                        id: __input5
                        cssClass: ["cfg-sel"]
                        model: ["1000 lines", "5000 lines", "8000 lines", "20000 lines", "100000 lines"]
                        values: ["1000", "5000", "8000", "20000", "100000"]
                        onActivated: (index) => { scrollback = parseInt(__input5.values[index]); termConfig.set("scrollback", parseInt(__input5.values[index])); }
                        Binding {
                            target: __input5
                            property: "currentIndex"
                            value: __input5.values.indexOf("" + scrollback)
                            restoreMode: Binding.RestoreNone
                        }
                    }
                }
            }
            W.Text {
                cssClass: ["cfg-group"]
                text: "Keyboard"
            }
            W.Div {
                cssClass: ["cfg-card"]
                Css.CssRepeater {
                    model: __const_ACTIONS
                    delegate: Component {
                        W.Div {
                            cssClass: ["cfg-krow"]
                            W.Text {
                                cssClass: ["cfg-l"]
                                text: "" + (modelData.label)
                            }
                            Css.CssRect {
                                cssPrimitive: "div"
                                cssClass: ["cfg-rec"]
                                QM_SolidTerm.KeyRecorder {
                                    anchors.fill: parent
                                    sequence: getKey(modelData.key)
                                    background: sysTheme.base
                                    foreground: sysTheme.text
                                    accent: sysTheme.accent
                                    border: sysTheme.window
                                    onSequenceChanged: function(s) { return setKey(modelData.key, s) }
                                }
                            }
                        }
                    }
                }
            }
            W.Text {
                cssClass: ["cfg-path"]
                text: "Saved to " + (termConfig.path)
            }
            W.Div {
                cssClass: ["cfg-actions"]
                W.Button {
                    cssClass: ["cfg-close"]
                    isDefault: true
                    text: "Done"
                    onClicked: cfgOpen = false
                }
            }
        }
    }
}
