// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssFill {
    id: __self
    property var label
    cssClass: ["btn"]
    cssPrimitive: "button"
    Css.CssText {
        cssPrimitive: "text"
        text: "" + (label)
    }
    MouseArea {
        anchors.fill: parent
        cursorShape: Qt.PointingHandCursor
    }
}
