// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var filter: "all"
    property var todos: ["a", "b"]
    readonly property var visible_: (function() { var f = filter; return todos.filter(function(t) { return f === "all" || t === f; }); })()
    cssClass: ["app"]
    W.Text {
        text: "" + (visible_.length)
    }
}
