// Generated by the transpiler. Do not edit by hand.
import QtQuick
import "qrc:/qmlcss" as Css

Css.CssText {
    id: __self
    property var name
    cssClass: ["hi"]
    cssPrimitive: "text"
    text: "hello " + (name)
}
