// Generated by the transpiler. Do not edit by hand.
import QtQuick
import "qrc:/qmlcss" as Css

Css.CssFill {
    id: __self
    property var __ctx_CounterContext
    cssPrimitive: "button"
    Css.CssText {
        cssPrimitive: "text"
        text: "increment"
    }
    MouseArea {
        anchors.fill: parent
        cursorShape: Qt.PointingHandCursor
        onClicked: __ctx_CounterContext.increment()
    }
}
