// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

CounterProvider {
    id: __ctxprov0
    count: 5
    Css.CssRect {
        cssClass: ["app"]
        cssPrimitive: "div"
        Display {
            __ctx_CounterContext: __ctxprov0
        }
        Increment {
            __ctx_CounterContext: __ctxprov0
        }
    }
}
