// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Button {
    id: __self
    property var count: 0
    cssClass: ["counter"]
    text: "count: " + (count)
    onClicked: count = count + 1
}
