// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var count: 2
    readonly property var double: count * 2
    cssClass: ["app"]
    W.Text {
        text: "count: " + (count)
    }
    W.Text {
        text: "double: " + (double)
    }
}
