// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    property var count: 2
    readonly property var double: count * 2
    cssClass: ["app"]
    cssPrimitive: "div"
    Css.CssText {
        cssPrimitive: "text"
        text: "count: " + (count)
    }
    Css.CssText {
        cssPrimitive: "text"
        text: "double: " + (double)
    }
}
