// Generated by the transpiler. Do not edit by hand.
import QtQuick
import "qrc:/qmlcss" as Css

Css.CssRect {
    id: __self
    property var tag: "h1"
    cssClass: ["app"]
    cssPrimitive: "div"
    Css.CssFill {
        cssPrimitive: "button"
        Css.CssText {
            cssPrimitive: "text"
            text: "toggle"
        }
        MouseArea {
            anchors.fill: parent
            cursorShape: Qt.PointingHandCursor
            onClicked: tag = tag === "h1" ? "bio" : "h1"
        }
    }
    Css.CssText {
        cssPrimitive: tag
        text: "polymorphic"
    }
}
