// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    property var a: 1
    property var b: 0
    property var __cleanups: []
    Component.onCompleted: { var t = setInterval(function() { return a = a + 1 }, 1000); __cleanups.push(function() { return clearInterval(t) }); b = a * 2; }
    Component.onDestruction: { for (var i = 0; i < __cleanups.length; i++) __cleanups[i](); }
    Connections {
        target: __self
        function onAChanged() { b = a * 2; }
    }
    cssClass: ["app"]
    cssPrimitive: "div"
    Css.CssText {
        cssPrimitive: "text"
        text: "a=" + (a) + " b=" + (b)
    }
}
