// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    property var count: 0
    function inc(n) { count = count + n; }
    function clampedInc() { if (count < 5) { inc(1); } }
    cssClass: ["app"]
    cssPrimitive: "div"
    Css.CssFill {
        cssClass: ["btn"]
        cssPrimitive: "button"
        Css.CssText {
            cssPrimitive: "text"
            text: "inc"
        }
        MouseArea {
            anchors.fill: parent
            cursorShape: Qt.PointingHandCursor
            onClicked: clampedInc()
        }
    }
    Css.CssText {
        cssClass: ["out"]
        cssPrimitive: "text"
        text: "" + (count)
    }
}
