// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
Css.CssRect {
    id: __self
    property var count: 0
    function inc(n) { count = count + n; }
    function clampedInc() { if (count < 5) { inc(1); } }
    cssClass: ["app"]
    cssPrimitive: "div"
    W.Button {
        cssClass: ["btn"]
        text: "inc"
        onClicked: clampedInc()
    }
    Css.CssText {
        cssClass: ["out"]
        cssPrimitive: "text"
        text: "" + (count)
    }
}
