// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
Css.CssRect {
    id: __self
    property var count: 0
    function inc() { count = count + 1; }
    cssClass: ["app"]
    cssPrimitive: "div"
    W.Button {
        cssClass: ["btn"]
        text: "click"
        onClicked: inc()
    }
    Css.CssText {
        cssClass: ["out"]
        cssPrimitive: "text"
        text: "" + (count)
    }
}
