// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    property var url: "qrc:/images/logo.png"
    cssClass: ["container"]
    cssPrimitive: "div"
    Css.CssImage {
        cssClass: ["hero"]
        source: url || ""
    }
}
