// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var items: ["alpha", "beta", "gamma"]
    cssClass: ["app"]
    W.Button {
        text: "add"
        onClicked: items = [...items, "more"]
    }
    Repeater {
        model: items
        W.Text {
            text: "" + (index) + ": " + (modelData)
        }
    }
}
