// Generated by the transpiler. Do not edit by hand.
import QtQuick
import "qrc:/qmlcss" as Css

Css.CssRect {
    id: __self
    property var s: ""
    cssClass: ["wrap"]
    cssPrimitive: "div"
    Css.CssFill {
        cssClass: ["search"]
        TextInput {
            id: __input0
            anchors.fill: parent
            anchors.leftMargin: 12
            anchors.rightMargin: 12
            verticalAlignment: TextInput.AlignVCenter
            clip: true
            selectByMouse: true
            activeFocusOnTab: true
            color: parent.style && parent.style["color"] ? cssTheme.parseColor(parent.style["color"]) : "#2b2b2b"
            font.family: parent.style && parent.style["font-family"] ? cssTheme.resolveFontFamily(parent.style["font-family"], "Sans Serif") : cssTheme.resolveFontFamily("Sans Serif")
            font.pointSize: parent.style && parent.style["font-size"] ? cssTheme.parseFontSize(parent.style["font-size"], 13) : 13
            Component.onCompleted: text = s
            onTextEdited: { s = text }
            Text {
                anchors.verticalCenter: parent.verticalCenter
                anchors.left: parent.left
                visible: parent.text.length === 0
                text: "search…"
                color: "#9aa0a6"
                font: parent.font
            }
            Connections {
                target: __self
                function onSChanged() { if (__input0.text !== s) __input0.text = s }
            }
        }
    }
}
