// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var s: ""
    cssClass: ["wrap"]
    W.TextField {
        id: __input0
        cssClass: ["search"]
        placeholder: "search…"
        onTextEdited: { s = text }
        Binding {
            target: __input0
            property: "text"
            value: s
            restoreMode: Binding.RestoreNone
        }
    }
}
