// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    id: __self
    property var items: ["a", "b", "c"]
    cssClass: ["app"]
    cssPrimitive: "div"
    Repeater {
        model: items
        Css.CssText {
            cssClass: ["row"]
            cssPrimitive: "text"
            text: "" + (modelData)
        }
    }
}
