// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var items: ["a", "b", "c"]
    cssClass: ["app"]
    Css.CssRepeater {
        model: items
        delegate: Component {
            W.Text {
                cssClass: ["row"]
                text: "" + (modelData)
            }
        }
    }
}
