// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    property var label: "(none)"
    property var nextId: 1
    cssClass: ["app"]
    W.Button {
        cssClass: ["btn"]
        text: "next"
        onClicked: label = "id:" + nextId++
    }
    W.Text {
        cssClass: ["out"]
        text: "" + (label)
    }
}
