// Generated by the transpiler. Do not edit by hand.
import QtQuick
import "qrc:/qmlcss" as Css

Css.CssText {
    id: __self
    property var greeting: "Hello"
    property var name: "stranger"
    cssClass: ["h1"]
    cssPrimitive: "text"
    text: "" + (greeting) + ", " + (name) + "!"
}
