// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Css.CssRect {
    property var __cleanups: []
    Component.onCompleted: { console.log("ref resolved:", _ref_myDiv); }
    Component.onDestruction: { for (var i = 0; i < __cleanups.length; i++) __cleanups[i](); }
    cssClass: ["app"]
    id: _ref_myDiv
    cssPrimitive: "div"
    Css.CssText {
        cssPrimitive: "text"
        text: "the box above this text is captured by ref"
    }
}
