// Generated by the transpiler. Do not edit by hand.
import QtQuick
import "qrc:/qmlcss" as Css

Css.CssRect {
    id: __self
    property var ok: true
    cssClass: ["wrap"]
    cssPrimitive: "div"
    Css.CssText {
        visible: !!(ok)
        cssPrimitive: "text"
        text: "yes"
    }
    Css.CssText {
        visible: !(ok)
        cssPrimitive: "text"
        text: "none"
    }
}
