// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css

Card {
    id: __self
    Css.CssText {
        cssClass: ["title"]
        cssPrimitive: "text"
        text: "hello"
    }
}
