// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
Card {
    id: __self
    W.Text {
        cssClass: ["title"]
        text: "hello"
    }
}
