// Generated by the transpiler. Do not edit by hand.
import QtQuick
import "qrc:/qmlcss" as Css

Css.CssRect {
    id: __self
    property var onToggle
    property var todo
    property var onRemove
    cssClass: ["todo-row"]
    cssPrimitive: "div"
    Css.CssFill {
        cssClass: ["todo-toggle"]
        cssPrimitive: "button"
        Css.CssText {
            cssPrimitive: "text"
            text: "" + (todo.done ? "✓" : "○")
        }
        MouseArea {
            anchors.fill: parent
            cursorShape: Qt.PointingHandCursor
            onClicked: onToggle(todo.id)
        }
    }
    Css.CssText {
        cssClass: ["todo-title"]
        cssPrimitive: "text"
        text: "" + (todo.title)
    }
    Css.CssFill {
        cssClass: ["todo-remove"]
        cssPrimitive: "button"
        Css.CssText {
            cssPrimitive: "text"
            text: "✕"
        }
        MouseArea {
            anchors.fill: parent
            cursorShape: Qt.PointingHandCursor
            onClicked: onRemove(todo.id)
        }
    }
}
