// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
Css.CssRect {
    id: __self
    property var onToggle
    property var todo
    property var onRemove
    cssClass: ["todo-row"]
    cssPrimitive: "div"
    W.Button {
        cssClass: ["todo-toggle"]
        text: "" + (todo.done ? "✓" : "○")
        onClicked: onToggle(todo.id)
    }
    Css.CssText {
        cssClass: ["todo-title"]
        cssPrimitive: "text"
        text: "" + (todo.title)
    }
    W.Button {
        cssClass: ["todo-remove"]
        text: "✕"
        onClicked: onRemove(todo.id)
    }
}
