// Generated by the transpiler. Do not edit by hand.
import QtQuick
import qmlcss 1.0 as Css


import solidqml.Widgets 1.0 as W
W.Div {
    id: __self
    cssClass: ["app"]
    TodoRow {
        todo: myTodo
        onToggle: handleToggle
        onRemove: handleRemove
    }
}
